### ISSUE TITLE
単語単位での選択の動作がおかしい

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/teraterm#116]
## 概要
マウス左ボタンダブルクリック+ドラッグでの単語単位での選択で、マウスポインタの位置がダブルクリックした単語より下の行、かつ左側に有る時に正しく選択されない。

## 期待した動作
マウスポインタが選択開始した単語より右に有る時は、選択開始した単語からマウスポインタの位置の単語までが選択される。
![word-select-1](https://github.com/TeraTermProject/teraterm/assets/1967759/2fe9627d-4721-425f-9c9f-8755a1096ae7)

## 問題のある動作
マウスポインタが選択開始した単語よりの左下方向に有る時は、マウスポインタの位置の単語の前の単語までしか選択されない。
![word-select-2](https://github.com/TeraTermProject/teraterm/assets/1967759/69209e93-3da4-4f82-a73d-692d89e16f8a)
また、この時クリップボードには選択開始した単語がコピーされない。
上記アニメーションの例だと`installed`がコピーされず、その後ろの`:`からがコピーされる。

## バージョン
5.1で発生。
4.108では問題なし。

**Comment by zmatsuo** [comment]
マウスポインタの下のwordが選択されないといけないですね。

調査します。

**Comment by zmatsuo** [comment]
修正しました。

1cellと2cellの変わり目も区切りとするようにしました。
従来と同じどうさになっていると思います。

[DelimList](https://teratermproject.github.io/manual/4/ja/setup/teraterm-win.html#delimiter)をUnicode化して
DelimDBCSをなくすのはどうかなと考えています。

**Comment by zmatsuo** [comment]
ddf5b0e で区切り文字に関する部分をUnicode化しました。

区切り文字に "😄" などが指定ができるようになりました。
実際にはかっこや句読点系を指定するのかなと思います。
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts

全角半角、区切り文字を織り交ぜた表示をしたときの
ダブルクリック時の選択がなんだか直感的に思った感じではないです。
[buffer.c#L3911](https://github.com/TeraTermProject/teraterm/blob/ba3bcfc2403fe6c6714e63cda0a3f1ccf2094006/teraterm/teraterm/buffer.c#L3911) このあたりが関連している気がしています。
もう少ししらべます。

**Comment by zmatsuo** [comment]
修正してmainに入れました。
ダブルクリック時の選択は自然になりました。

TERATERM.INI,[Tera Term]セクションの
```
DelimDBCS=on/off
```
は、1cell で表示されている文字と 1cell以外(2cell以上,漢字や絵文字など)で表示されている
文字の間を区切りとするかしないかの指定になっています。

**Comment by zmatsuo** [comment]
関連するドキュメント( [使いかた/マウス](https://teratermproject.github.io/manual/5/ja/usage/mouse.html) ) も修正もしました。
11d7cbb です。

INIファイルの DelimDBCS キーの名前がどうもいまいちですが、
しっくりしたキー名が思いつかないのでそのままにしようと思います。
[ダブルクリックによる単語選択の区切り文字](https://teratermproject.github.io/manual/5/ja/setup/teraterm-win.html#delimiter)

クローズします。
