### ISSUE TITLE
ttermpro.exe の FileDescription が長い

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#119]
VERSIONINFO の FileDescription がタスクマネージャーのプロセス名に使用される。
そのため「Tera Term is open source free software terminal emulator」と長くなる。

![taskmgr](https://github.com/TeraTermProject/teraterm/assets/5668936/fea7f823-b937-4496-8a81-7ae2eba38203)

commit: https://github.com/TeraTermProject/teraterm/commit/a069aba7a181798cc02cce2cef1bbd2330a79061

**Comment by zmatsuo** [comment]
リソースファイルを調べていて、何かを参考にファイルの説明("FileDescription")に追記しました。
元に戻しましょう。

これも直したほうがよい?

./teraterm/keycode/keycode-version.rc:26:            VALUE "FileDescription", "Keycode Checker"
./teraterm/ttpmacro/ttm-version.rc:26:            VALUE "FileDescription", "Tera Term Macro Interpreter"
./ttpmenu/ttpmenu-version.rc:29:            VALUE "FileDescription", "TeraTerm Menu"

Tera TermのFileDescription が長すぎただけで、
"TeraTerm Menu" とタスクマネージャに表示されていても違和感はないです。
keycode、ttpmacro はずっと動いているものでもなさそうです。
直さなくてもよいのかなと思います。


DLLなのでタスクマネージャに出てこないのでこれらは気にしなくてもよさそうです。

./TTProxy/TTProxy.rc:103:            VALUE "FileDescription", "プロキシプラグイン"
./TTProxy/TTProxy.rc:155:            VALUE "FileDescription", "Proxy plug-in"
./TTXKanjiMenu/ttxkanjimenu.rc:72:            VALUE "FileDescription", "TTX KanjiMenu Plug-in"
./teraterm/ttpcmn/ttpcmn-version.rc:30:            VALUE "FileDescription", "Tera Term Common Routines"
./ttssh2/ttxssh/ttxssh-version.rc:26:            VALUE "FileDescription", "Tera Term Secure Shell Extension"

> TTXProxyのリソースはバージョンに複数言語入っているんですね。

**Comment by zmatsuo** [comment]
mainにマージしました。
クローズします。

**Comment by nmaya** [comment]
ありがとうございました。
