### ISSUE TITLE
ダイアログのバージョン表示などを修正する

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#12]
installer/release.bat からビルドできるよう次の調整を行う
- buildtools/svnrev/svnrev.pl
- ダイアログのバージョン表示
- アーカイブファイル名

**Comment by nmaya** [comment]
[#2-move_to_github ](https://github.com/TeraTermProject/teraterm/tree/%232-move_to_github) ブランチで作業中（push済み）です。

**Comment by nmaya** [comment]
確認ですが、VCSバージョンの表示は以下のようになっていますが、意図通りでしょうか？
- ttermpro.exe の ProductVersion にリビジョンが入るのは、リリース版**ではない**ときだけ（teraterm/common/tt-version.h, teraterm/teraterm/tt-version.rc）
- ttxssh.dll の ProductVersion にリビジョンが入るのは、リリース版**ではない**ときだけ（ttssh2/ttxssh/ttxssh-version.h, ttssh2/ttxssh/ttxssh-version.rc）
- ttermpro.exe の About ダイアログにリビジョンが入るのは、リリース版**でもそうでなくても**（teraterm/ttpdlg/ttpdlg.c）
- ttxssh.dll の About ダイアログ にリビジョンが入るのは、リリース版**ではない**ときだけ（ttssh2/ttxssh.c）

**Comment by zmatsuo** [comment]
各々は意図通りだったんですが、統一したほうがよさそうですね。

後で何か調べるときには入っているほうが安心そうなので
いつも入れるに一票です。

**Comment by nmaya** [comment]
> いつも入れるに一票です。

了解しました。

**Comment by nmaya** [comment]
デバッグコードが残っていました。 26c2e88de66c9ab5802e02ff399f460946aabc4e
お騒がせしました。

**Comment by nmaya** [comment]
修正をコミットしました。

**Comment by nmaya** [comment]
ここからsnapshotをダウンロードできます。
https://ci.appveyor.com/project/teraterm/github-main/builds/48417739/artifacts
