### ISSUE TITLE
Teraterm Macro (ttpmacro.exe): xmodemsend - it doens't work

### ISSUE THREAD

**Issue by Userjavi** [TeraTermProject/teraterm#123]
It doens't work fine, when you run the command "xmodemsend" appears the windows of the command xmodemrecv.

![image](https://github.com/TeraTermProject/teraterm/assets/160261642/1c9a6c61-3c74-4561-89fe-8af08c0ad68c)

**Comment by zmatsuo** [comment]
Thanks for reporting.

Please try following fixed binary.
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts

**Comment by Userjavi** [comment]
Hello Matsuo san

ttpmacro.exe executed by command line with parameters doesn’t work.
But executed manually choosing the ttl file through dialog window (open macro), it works fine.


Thanks a lot.

__________________________________________________
Javier Agudo Alcázar
Test Engineering Department

***@***.***
P.I. Can Mitjans s/n
E08232 Viladecavalls (Barcelona) Spain
Tel: +34 662 302 629
***@***.******@***.***>
www.ficosa.com<http://www.ficosa.com/>

Follow us on:
***@***.***<http://www.facebook.com/ficosaofficialpage> ***@***.*** <https://twitter.com/FICOSA_Int>  ***@***.*** <https://plus.google.com/b/116818897630994478739/116818897630994478739/posts>  ***@***.*** <http://www.youtube.com/user/FicosaInternational>  ***@***.*** <http://www.flickr.com/photos/ficosaofficialpage>  ***@***.*** <http://www.linkedin.com/company/ficosa-international>

**Comment by zmatsuo** [comment]
> ttpmacro.exe executed by command line with parameters doesn’t work.

Currently it is not possible to communicate from ttpmacro.exe.

> But executed manually choosing the ttl file through dialog window (open macro), it works fine.

😄
I close this issue.
Thank you.

**Comment by Userjavi** [comment]
Hello Matsuo san

Last question:
To communicate from ttpmacro.exe executed by command line with parameters, will be possible with the final version 5.2?

Thank you.

__________________________________________________
Javier Agudo Alcázar
Test Engineering Department

***@***.***
P.I. Can Mitjans s/n
E08232 Viladecavalls (Barcelona) Spain
Tel: +34 662 302 629
***@***.******@***.***>
www.ficosa.com<http://www.ficosa.com/>

Follow us on:
***@***.***<http://www.facebook.com/ficosaofficialpage> ***@***.*** <https://twitter.com/FICOSA_Int>  ***@***.*** <https://plus.google.com/b/116818897630994478739/116818897630994478739/posts>  ***@***.*** <http://www.youtube.com/user/FicosaInternational>  ***@***.*** <http://www.flickr.com/photos/ficosaofficialpage>  ***@***.*** <http://www.linkedin.com/company/ficosa-international>
