### ISSUE TITLE
ttpmacro.exe executed by command line with parameters doesn’t work.

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#127]
Hello Matsuo san

ttpmacro.exe executed by command line with parameters doesn’t work.
But executed manually choosing the ttl file through dialog window (open macro), it works fine.

Thanks a lot.

_Originally posted by @Userjavi in https://github.com/TeraTermProject/teraterm/issues/123#issuecomment-1956412666_

**Comment by nmaya** [comment]
I could not reproduce this issue.
`run ttpmacro.exe with ttl file path` works fine for me.

```
# cmd
C:\Program Files (x86)\teraterm5>ttpmacro.exe z:\test.ttl
```

```
# test.ttl
messagebox 'messagebox' 'test'
```

**Comment by Userjavi** [comment]
Hello Nmaya san

With the version:

teraterm-5.2-dev-20240220_223407-f6954d67f-appveyor-snapshot.zip

it doesn’t work.

Thank you

__________________________________________________
Javier Agudo Alcázar
Test Engineering Department

***@***.***
P.I. Can Mitjans s/n
E08232 Viladecavalls (Barcelona) Spain
Tel: +34 662 302 629
***@***.******@***.***>
www.ficosa.com<http://www.ficosa.com/>

Follow us on:
***@***.***<http://www.facebook.com/ficosaofficialpage> ***@***.*** <https://twitter.com/FICOSA_Int>  ***@***.*** <https://plus.google.com/b/116818897630994478739/116818897630994478739/posts>  ***@***.*** <http://www.youtube.com/user/FicosaInternational>  ***@***.*** <http://www.flickr.com/photos/ficosaofficialpage>  ***@***.*** <http://www.linkedin.com/company/ficosa-international>

**Comment by nmaya** [comment]
Hi,

```
# cmd
C:\Users\maya\Desktop\teraterm-5.2-dev-20240220_223407-f6954d67f-appveyor-snapshot>ttpmacro.exe z:\test.ttl
```

works fine in my env, Appears a MessaegBox.

What do you mean `doesn’t work`?
Specified ttl file does not run? Nothing happens?
Or a argument you specified is not passed to params2 variable?
Is version 5.1 behaves same?


@zmatsuo どのバージョンからなのかわかりませんが、このようなことが起きそうなコードの変更がありますか？

**Comment by nmaya** [comment]
Hi,

Thank you for your testing.

> it works correctly

I think both are correct.
This issue may from difference between portable mode and not portable mode.
The current directory differs whether portable.ini is presence or not.
cf. https://teratermproject.github.io/manual/5/en/setup/folder.html

```
version: teraterm-5.2-dev-20240220_223407-f6954d67f-appveyor-snapshot
on C:\Users\maya\Desktop\teraterm-5.2-dev-20240220_223407-f6954d67f-appveyor-snapshot

a. without portable.ini
test.ttl (relative path) is parsed from %APPDATA%\teraterm5
cmd>ttpmacro.exe test.ttl
called C:\Users\maya\AppData\Roaming\teraterm5\test.ttl

b. with portable.ini
test.ttl (relative path) is parsed from exe folder
cmd>ttpmacro.exe test.ttl
called C:\Users\maya\Desktop\teraterm-5.2-dev-20240220_223407-f6954d67f-appveyor-snapshot\test.ttl
```

> The portable.ini file has no data inside but is necessary for command line execution of the ttpmacro.exe.

`portable.ini is exist or not exist` is a switch of behavior. Data of portable.ini does not affect to behavior.

> Also there are more DLL’s files inside the version 5.1 folder than inside the version 5.2 folder. Are required for version 5.2?

"5.2" you say is a snapshot of 5.2. It is not 5.2 release binary. 5.2 is not released yet.
Snapshot includes limited binaries. The installer contains other binaries.

Thanks,

**Comment by zmatsuo** [comment]
> @zmatsuo どのバージョンからなのかわかりませんが、このようなことが起きそうなコードの変更がありますか？

特に変更していないはずです。
動作を調べたところ…

1. explorer から test.ttl を ttpmacro.exe にドロップ
2. c:\path\to\ をカレントにした cmd.exe から
2-1. `ttpmacro.exe c:\path\to\test.ttl` を実行
2-2. `c:\path\to\ttpmacro.exe c:\path\to\test.ttl` で実行
2-3. `ttpmacro.exe test.ttl` で実行
2-4. `c:\path\to\ttpmacro.exe test.ttl` で実行

で、2-3,2-4のとき portable.ini が存在しないとき実行できていないようです。

引数のttlファイルは、portable.iniの有無にかかわらず、
ttpmacro.exe を実行したカレントディレクトリから読み込む動作が妥当に感じます。
ソース調べてみます。

コマンドラインから`ttpmacro send.ttl` 等で xmodem の送信ができるはずです。
```
# send.ttl
f = "C:\tmp\send.txt"
messagebox f "target file"
connect "/C=1"
xmodemsend f 1
```

**Comment by nmaya** [comment]
> ttpmacro.exe を実行したカレントディレクトリから読み込む動作が妥当に感じます。

この問題はポータブルとそうでないモードの切り替えに起因すると思います。
ファイルを書き込んだとき（logだけでなくマクロによる新規ファイルオープンでも）にUAC機構によりVirtualStore以下にファイルができてしまうのを回避するため、今の動作をするように変更されていると思います。
相対パスでttlファイルを指定して読み込むときにも同じ動作になっていて、これが副作用のようにも見えますが、その他のファイルの扱いと比較すると整合性があるように思います。

**Comment by nmaya** [comment]
詳細な確認ありがとうございます。5.2リリース後にしましょう。

**Comment by zmatsuo** [comment]
> > ドキュメントへの記載があったでしょうか。

> 無さそうです。

記載がありました。
現在の動作にあわせて修正を行いました。

**Comment by zmatsuo** [comment]
> ttpmacro.exe executed by command line with parameters doesn’t work.

This has been fixed.
Please try this binary. @Userjavi
https://ci.appveyor.com/project/teraterm/github-main/builds/49323906/artifacts

**Comment by Userjavi** [comment]
Hello Zmatsuo san

Great..
It Works by command line with parameters. (portable.ini file is not necessary).

Thanks a lot.

__________________________________________________
Javier Agudo Alcázar
Test Engineering Department

***@***.***
P.I. Can Mitjans s/n
E08232 Viladecavalls (Barcelona) Spain
Tel: +34 662 302 629
***@***.******@***.***>
www.ficosa.com<http://www.ficosa.com/>

Follow us on:
***@***.***<http://www.facebook.com/ficosaofficialpage> ***@***.*** <https://twitter.com/FICOSA_Int>  ***@***.*** <https://plus.google.com/b/116818897630994478739/116818897630994478739/posts>  ***@***.*** <http://www.youtube.com/user/FicosaInternational>  ***@***.*** <http://www.flickr.com/photos/ficosaofficialpage>  ***@***.*** <http://www.linkedin.com/company/ficosa-international>

**Comment by zmatsuo** [comment]
👍

「現在のディレクトリ」は削除してプロセスのカレントディレクトリのみとする修正は別の機会にしましょうか… @nmaya
