### ISSUE TITLE
モデムのCOMポートにV5だと接続できない（V4だと可能）

### ISSUE THREAD

**Issue by hosokawatakeshi** [TeraTermProject/teraterm#130]
mangOHなどSierra系のボードにUSBで接続した場合、COMポートおよびモデムと
接続可能となります。
V4であればモデムのCOMポートに接続ができるのですが、
V5だとモデムのCOMポートが一覧に表示されません。

こちらは既知の問題でしょうか？

以下モデムのCOM確認の参考URLです。
https://m2msupport.net/m2msupport/connect-sierra-wireless-modules-to-at-command-tester-software/

**Comment by nmaya** [comment]
私はモデムの COM ポートに Tera Term で接続したことがなく、またそのようなボードを持っていないので、手元で確認することができません。
しかしながら、v4 から v5 で、ポートを検出するコードを変える理由がないので、意図的に変えたつもりはないと思います。何かを踏んでしまったかもしれません。
@zmatsuo 怪しいところはありますか？

- 使っている PC の OS バージョンはなんですか？
- v4 と v5 の詳細なバージョンはなんですか？
- v4 と v5 を試しているのは、同じ PC・同じボードの組み合わせですか？

**Comment by hosokawatakeshi** [comment]
> 使っている PC の OS バージョンはなんですか？

エディション	Windows 10 Enterprise
バージョン	22H2
インストール日	‎2023/‎03/‎04
OS ビルド	19045.4046
エクスペリエンス	Windows Feature Experience Pack 1000.19053.1000.0

> v4 と v5 の詳細なバージョンはなんですか？

v4.108とv5.1です

> v4 と v5 を試しているのは、同じ PC・同じボードの組み合わせですか？

はい。同じPC・同じボードで確認しています。

**Comment by hosokawatakeshi** [comment]
スクリーンショットを貼ります。こんな感じで、V5だと選択肢がでなくなります。

v4
![v4](https://github.com/TeraTermProject/teraterm/assets/12977182/f1bde576-6247-415e-8f39-88dfb8686fdd)

v5
![v5](https://github.com/TeraTermProject/teraterm/assets/12977182/fa93455b-ccd2-48c3-9fee-271420d6f47c)

**Comment by zmatsuo** [comment]
COMポートをリストは、
Tera Term 4 は QueryDosDevice() だったのを
5 は SetupAPI系のAPIを使うように変更しました。

変更理由は新しいSetupAPIのほうが新しくて、取れる情報が多かったからです。
以前のほうが良ければ戻す(or切り替えできるようにする)のを検討しないといけないですね。

comポートをリストするテストプログラムがあります。
試していただけないでしょうか?

[lscom.zip](https://github.com/TeraTermProject/teraterm/files/14436972/lscom.zip)

```
$ lscom -h
lscom [option]
  list com devices
option
  -q, querydosdevice   list com devices by QueryDosDevice() API
  -a, all              show all devices with -q option
  -d, detectcomports   list by DetectComPorts()
  -f, fopen            list by fopen()
```

オプションなしが v5相当
-q が v4 相当です。

**Comment by hosokawatakeshi** [comment]
以下の結果になりました。
```
C:\Users\hosokawatakeshi\Downloads\lscom>lscom.exe
new
comport count 3
========
COM3:
-----
FRIENDLY:
Intel(R) Active Management Technology - SOL (COM3)
-----
DESC:
Device Friendly Name: Intel(R) Active Management Technology - SOL (COM3)
Device Instance ID: PCI\VEN_8086&DEV_A0E3&SUBSYS_004E1E26&REV_20\3&11583659&2&B3
Device Manufacturer: Intel
Provider Name: Intel
Driver Date: 10-14-2020
Driver Version: 2042.0.13.0
========
COM8:
-----
FRIENDLY:
Sierra Wireless NMEA Port (COM8)
-----
DESC:
Device Friendly Name: Sierra Wireless NMEA Port (COM8)
Device Instance ID: USB\VID_1199&PID_68C0&MI_02\6&20EC0070&0&0002
Device Manufacturer: Sierra Wireless Incorporated
Provider Name: Sierra Wireless Incorporated
Driver Date: 4-5-2018
Driver Version: 18.4.1005.44
========
COM10:
-----
FRIENDLY:
Sierra Wireless DM Port (COM10)
-----
DESC:
Device Friendly Name: Sierra Wireless DM Port (COM10)
Device Instance ID: USB\VID_1199&PID_68C0&MI_00\6&20EC0070&0&0000
Device Manufacturer: Sierra Wireless Incorporated
Provider Name: Sierra Wireless Incorporated
Driver Date: 4-5-2018
Driver Version: 18.4.1005.44
end

C:\Users\hosokawatakeshi\Downloads\lscom>lscom.exe -q
query
106: COM9
327: COM10
370: COM3
465: COM8

C:\Users\hosokawatakeshi\Downloads\lscom>
```

**Comment by nmaya** [comment]
@zmatsuo

> Tera Term 4 は QueryDosDevice() だったのを 5 は SetupAPI系のAPIを使うように変更しました。

確認しました。こうでしょうか。

|  | [4.108](https://github.com/TeraTermProject/teraterm/tree/v4.108) | [5.2](https://github.com/TeraTermProject/teraterm/tree/v5.2) |
|--|----|----|
|ComPortInfoGet() *1|SetupDiGetClassDevsA()|ComPortInfoGetByGetSetupAPI() -> SetupDiGetClassDevsA()|
|DetectComPorts() *2|QueryDosDeviceA() / QueryDosDeviceAがなければfopen()|ComPortInfoGetByGetSetupAPI() -> SetupDiGetClassDevsA()|
|CheckComPort()|QueryDosDevice() SetupDiGetClassDevs()|ComPortInfoGet() -> ComPortInfoGetByGetSetupAPI() -> SetupDiGetClassDevsA()|

- [v4 の Setup - Serial port ダイアログ](https://github.com/TeraTermProject/teraterm/blob/70c5279d3691829d67e70972a2ce44e15d568795/teraterm/ttpdlg/ttdlg.c#L1228)は *1
- [v5 の Setup - Serial port ダイアログ](https://github.com/TeraTermProject/teraterm/blob/176aed2671bda031f2d0c0b09af463feba8e428c/teraterm/ttpdlg/serialdlg.cpp#L440)は *1
- [v4 の File - New connection ダイアログ](https://github.com/TeraTermProject/teraterm/blob/70c5279d3691829d67e70972a2ce44e15d568795/teraterm/ttpdlg/ttdlg.c#L1746)は *2
- [v5 の File - New connection ダイアログ](https://github.com/TeraTermProject/teraterm/blob/176aed2671bda031f2d0c0b09af463feba8e428c/teraterm/ttpdlg/hostdlg.c#L89)は *1


@hosokawatakeshi

確認ありがとうございます。画面キャプチャ同様 COM9 が見えない状況がわかりました。
ちなみにですが、ver 4, ver 5 それぞれの Setup - Serail port でのリストアップはどうでしょうか？


@zmatsuo

- 引数を変えれば SetupDiGetClassDevsA() でモデムデバイスの存在も取得できるのか
- モデムデバイスでも [SetupDiGetDevicePropertyW() 等で詳細な情報が取得](https://github.com/TeraTermProject/teraterm/blob/176aed2671bda031f2d0c0b09af463feba8e428c/teraterm/common/comportinfo.cpp#L197)できるのか

このあたりが気になります。

**Comment by hosokawatakeshi** [comment]
> 確認ありがとうございます。画面キャプチャ同様 COM9 が見えない状況がわかりました。
ちなみにですが、ver 4, ver 5 それぞれの Setup - Serail port でのリストアップはどうでしょうか？

v4
モデムのポートも表示されますが、下のウィンドウはCOM3の内容が表示されています。
![スクリーンショット 2024-02-29 191427](https://github.com/TeraTermProject/teraterm/assets/12977182/25ef4b9a-42de-4002-8307-b3e902d72666)


v5
モデムのポートが表示されません。
![スクリーンショット 2024-02-29 191503](https://github.com/TeraTermProject/teraterm/assets/12977182/077c7432-658c-47bf-b7ed-bd137fb8ef01)

**Comment by hosokawatakeshi** [comment]
lscomとTeratermの結果です。想定通りですね。
```
C:\Users\hosokawatakeshi\Downloads\lscom_0301>lscom.exe
new
comport count 1
========
COM12:
-----
FRIENDLY:
Sierra Wireless WWAN Modem #2
-----
DESC:
Device Friendly Name: Sierra Wireless WWAN Modem #2
Device Instance ID: USB\VID_1199&PID_68C0&MI_03\6&20EC0070&0&0003
Device Manufacturer: Sierra Wireless Incorporated
Provider Name: Sierra Wireless Incorporated
Driver Date: 4-5-2018
Driver Version: 18.4.1005.44
end

C:\Users\hosokawatakeshi\Downloads\lscom_0301>
```
![スクリーンショット 2024-03-04 123932](https://github.com/TeraTermProject/teraterm/assets/12977182/b2388a31-6c08-4f96-b9f9-5ffca39c3375)

**Comment by hosokawatakeshi** [comment]
Setup画面も貼り付けます。
![スクリーンショット 2024-03-04 124141](https://github.com/TeraTermProject/teraterm/assets/12977182/bd44a3f8-88b0-483f-a40a-affe5ffd2010)

**Comment by zmatsuo** [comment]
確認ありがとうございます。
モデムも合わせて検出できるようにしました。
試してみてください。
https://ci.appveyor.com/project/teraterm/github-main/builds/49323906/artifacts

**Comment by hosokawatakeshi** [comment]
使ってみました。（COM12）が表示されていませんが、一律重複なので消したほうがよくないでしょうか？

![スクリーンショット 2024-03-06 150018](https://github.com/TeraTermProject/teraterm/assets/12977182/4b79b123-d882-4d83-8f07-cc62361736e3)

**Comment by nmaya** [comment]
> 使ってみました。

確認ありがとうございます。4.108 のように接続して使うことができますか？

> （COM12）が表示されていませんが、一律重複なので消したほうがよくないでしょうか？

プルダウンの文字列は「Setup画面の下のほうの詳細表示で『Device Friendly Name』の項目にある文字列」また「コントロールパネルでプロパティを見たときに出てくる文字列」（下図参照）と同様です。
この文字列は OS に問い合わせる帰ってくる値です。
ですので「（その）シリアルポート（ドライバ）は名前の末尾にCOMポート番号（例 『(COM12)』）を含めている」「（その）モデム（ドライバ）は名前の末尾にCOMポート番号を含めていない」ということになると思います。
Tera Term は OS の出力をそのまま使用しており、一部を消して出力するという選択肢は（少なくとも私には）ありません。

![Clipboard01](https://github.com/TeraTermProject/teraterm/assets/5668936/0d0a2926-faa2-4fc2-8f0c-372634181fef)

**Comment by hosokawatakeshi** [comment]
> 4.108 のように接続して使うことができますか？

はい。利用可能です。リリースをお願いします。

> プルダウンの文字列は「Setup画面の下のほうの詳細表示で『Device Friendly Name』の項目にある文字列」また「コントロールパネルでプロパティを見たときに出てくる文字列」（下図参照）と同様です。
この文字列は OS に問い合わせる帰ってくる値です。

なるほど。承知しました。

**Comment by zmatsuo** [comment]
調べていて[もう少し変更](https://github.com/TeraTermProject/teraterm/commit/b1d402ab7dc0097a7d496f813b308c78b76c9dff)したほうがよさそうなことがわかりました。

チームにはモデムデバイスを持っているものがいないため
モデムデバイスでテストすることがすることができません。

次のバイナリでポート一覧に問題ないか見ていただけないでしょうか。@hosokawatakeshi
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49353133/artifacts

よろしくお願いします。

**Comment by hosokawatakeshi** [comment]
ダメですね。ポートが無い状態になっています。
![スクリーンショット 2024-03-11 073016](https://github.com/TeraTermProject/teraterm/assets/12977182/f28951cd-4c06-4015-bc4e-da68823ce190)
![スクリーンショット 2024-03-11 073053](https://github.com/TeraTermProject/teraterm/assets/12977182/924bb532-4835-446c-98e3-b885431a9af6)

**Comment by zmatsuo** [comment]
@hosokawatakeshi
確認ありがとうございます。

少なくともCOMポートはリストされると予想していました
モデムもCOMポートもリストされないのはダメですね。

html/about/history.html だけ main に取りこんで、
ブランチ #130 はこのままおいておきましょうか @nmaya

**Comment by nmaya** [comment]
3d1fd57aebb3c733f8b353b2ea84004f724b424c, bee9e76134f08a3436b7ba3c4088d9861507a3d5 をmainに持ってきて、#130 は消してしまいましょうか。
b1d402ab7dc0097a7d496f813b308c78b76c9dff は、どのブランチからも辿れなくなってもこの issue からはたどれるんじゃないかと思います。

**Comment by zmatsuo** [comment]
調べていて次の情報を見つけました。
https://kougaku-navi.hatenablog.com/entry/20120723/p1

今のところCOMポートの検出できないという問題は出てきていないですが、
検出できないこともあるのかもしれません。

もしかして、
GUID_CLASS_COMPORT と GUID_DEVINTERFACE_COMPORT のリストを
混ぜるのかもしれない…?

それと、COMポートを無効化していてもリストされてしまう
というのもまだ未調査でした。
また別のissueで…。
