### ISSUE TITLE
Tamil.lng の取り込み

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#136]
@zmatsuo [以前に「あるだろう」と言ったことがある](https://github.com/TeraTermProject/osdn-download/issues/13)「[それ以外の修正が必要なPR](https://github.com/TeraTermProject/teraterm/pull/135)」が来ました。

必要なその他の修正

- 変更履歴の追加
- インストーラへの追加

「先方がこちらからforkして、先方のブランチへの修正」→「こちらがPRをマージすると、こちらのブランチになる」→「我々がこちらのブランチで上記の修正を入れる」→「我々がこちらの main へマージ」なら取り込みが可能だと思います。
しかしこれは「先方の main」に修正を入れているため、このような手順は取れません。「"tamil_lang" のようなブランチをそちらで切って、それを PR してほしい」とリクストしますか？

**Comment by zmatsuo** [comment]
最初はメール( [ttssh2-contact 250] )で送られてきました。

プルリクエストできる?
文字コードの変換やインストーラーの変更はやるよ、
と返事したところ、PRいただきました。

今回はわたしがPR取り込む形でブランチ作って
mainにマージしてみます。
5.2リリース後ですね。


GitHubに引っ越すときはIssueやPRがたくさん来て
大変になったらどうしたものかと思っていました。
でも、いまの感じなら
すぐにmergeできる状態のPRでなければ受け付けない、
というよりも、
メールでlngファイルをいただくよりは
PR経由でいただくほうが
履歴も残っていいかなと思います。

**Comment by nmaya** [comment]
> 5.2リリース後ですね。

はい。その段取りでお願いします。

> PR取り込む形でブランチ作って

forkのmainを修正したものがPRされているので、「先方のmainをこちらのブランチとしてマージ」ができるならできると思っています。できるならやり方を知りたいです。
できないのであれば、ブランチにを作ってもらわないと「ブランチとしてマージ」ができないと思います。

> [TamilNeram](https://github.com/TamilNeram) wants to merge 1 commit into [TeraTermProject:main](https://github.com/TeraTermProject/teraterm/tree/main) from [Nizhal:main](https://github.com/Nizhal/teraterm/tree/main)

となっているので、私にはできないように見えます。

**Comment by zmatsuo** [comment]
PR #135 を取り込んだ、branch #136 を作りました。

Tamilのコードページがわからず、
utf16le (Unicode版)のみとなっています。

ブランチはこんな感じで作りました。

- PR元のリモートリポジトリをローカルリポジトリに追加
- #136ブランチを作って、修正ピック (739f9e3)
- さらに修正をブランチに追加
- #136ブランチを TeraTermProject/teraterm リポジトリにpush

2,3日で main にマージしようと思います。

マージしたら、言語ファイル情報の更新が必要ですね。
https://teratermproject.github.io#localize

**Comment by nmaya** [comment]
> ブランチはこんな感じで作りました。

ありがとうございます。かなり手順が複雑なのであまり扱いたくないですが、取り込むことはできるんですね。
author/書いた人+commit/コミットした人、という[コミット](https://github.com/TeraTermProject/teraterm/commit/739f9e372854964ccdae1320363809d9e9bb47fc)になるんですね。一方[PRで取り込んだコミット](https://github.com/TeraTermProject/web/commit/790ce465c797b8cb2b3def821d9efe6a075e7fe3)はどちらも書いた人になるようですね。
また、作ってくれたPRは取り込めずrejectすることになるので、あまりいい印象にならなそうです。

むかし「そういうものだ」と聞いた記憶がありましたが、調べてみたらやはりブランチをPRするのが作法のようです。
[pull request の作成](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) (GitHub)
```
リポジトリへの変更の提案や共同作業を行うには、pull request を作成します。 これらの変更は "ブランチ" を介して提案され、既定のブランチには完成していて、かつ承認された作業のみが確実に含まれるようにします。
```
[Gitを使ってPull Requestを投げるまで](https://qiita.com/takamii228/items/80c0996a0b5fa39337bd)
```
2. 作業用ブランチを作成する
```
[GitHubを使うなら最低限知っておきたい、プルリクエストの送り方とレビュー、マージの基本](https://atmarkit.itmedia.co.jp/ait/articles/1702/27/news022.html)
```
プルリクエスト用のブランチ「edit-readme」を作成し、このブランチに切り替えます。
```


> 文字が途中までで切れる

これは言語ファイルでの対応は不可です。リソースのほうでコントロールやボタンの幅を広げるしかありません。

**Comment by zmatsuo** [comment]
ブランチを作ってPRを出してもらうと
REJECTなしに、きれいにマージできそうですね。
お願いしてみます。

**Comment by zmatsuo** [comment]
> > 文字が途中までで切れる
>
> これは言語ファイルでの対応は不可です。リソースのほうでコントロールやボタンの幅を広げるしかありません。

そうですね。
Themeタブなど余裕があるところはなるべく幅を広く取れるように
コントロールを配置しています。
今後の変更する時、幅を取れるよう考慮したほうがよさそうです。

それと、日本語の(日本語以外も?)Meiryo UI みたいな、
日本語Windowsではデフォルトでインストールされていない
ちょっと幅が狭くデザインされたタミル語フォントがあるのかもしれないですね。

**Comment by zmatsuo** [comment]
ちょっと違うと思ったのですがマージした後だったので
そのままmainで修正を入れました。

ひとまず取り込み完了でクローズします。

**Comment by nmaya** [comment]
> ちょっと違うと思ったのですがマージした後だったので
> そのままmainで修正を入れました。

足取りが割と複雑になり、たどりつらくなりましたね。

![tamil-](https://github.com/TeraTermProject/teraterm/assets/5668936/f39d7a50-3647-4e96-8539-0f514edcb7cd)

676cc98d795a1cf0d18a6c4f184cdd3811cb1cfb の内容までブランチで修正してマージしたかったです。

> ひとまず取り込み完了でクローズします。

ありがとうございました。
必要な修正は最終的にコミットできました。
