### ISSUE TITLE
プラグイン:WinSCPランチャー(TTXWinSCP.dll)のご紹介

### ISSUE THREAD

**Issue by hkanou** [TeraTermProject/teraterm#140]
はじめまして、hkanouです。

WinSCPを起動するランチャープラグイン(TTXWinSCP.dll)を紹介させて頂きます。
[https://github.com/hkanou/TTXSamples/tree/main](https://github.com/hkanou/TTXSamples/tree/main)

Issuesに投稿する内容では無いかもしれませんが、下記の関連ということでご了承頂ければ幸いです。  
[#128 コマンドライン(起動時のオプション)の削除](https://github.com/TeraTermProject/teraterm/issues/128)

**Comment by zmatsuo** [comment]
便利なプラグインを共有できれば良いかなと思い
[プラグイン](https://github.com/TeraTermProject/teraterm/wiki/Plugins-(draft))の紹介ページを作ってみました。

内容などどうでしょうか?

特に何もなければ1週間程度でこのissueはクローズしようと思います。

**Comment by hkanou** [comment]
> 便利なプラグインを共有できれば良いかなと思い
> [プラグイン](https://github.com/TeraTermProject/teraterm/wiki/Plugins-(draft))の紹介ページを作ってみました。

ありがとうございます、紹介ページまで作成いただき恐縮です。

> 内容などどうでしょうか?

ご迷惑をおかけしないよう、ソースツリー外のプラグインの不具合等は作者に連絡するよう記載頂くのが良いかもと感じました。
> 特に何もなければ1週間程度でこのissueはクローズしようと思います。

はい、承知いたしました。

**Comment by zmatsuo** [comment]
ありがとうございます。
作者に問い合わせくださいという一文を追加しました。
クローズします。

**Comment by zmatsuo** [comment]
ページのタイトルを変更したのでURLが変化しています。

https://github.com/TeraTermProject/teraterm/wiki/Plugins
