### ISSUE TITLE
Tera Term 5.2 Can't display some color text

### ISSUE THREAD

**Issue by FQDianYan** [TeraTermProject/teraterm#141]
Tera Term 5.2 can't display some color text like htop Mem Info and Swp Info.
  
![TT5 2](https://github.com/TeraTermProject/teraterm/assets/23021381/a1da300d-e729-42ec-94c0-fdb48b535788)

  Tera Term 4.108 does not have this problem.

![TT4 108](https://github.com/TeraTermProject/teraterm/assets/23021381/90815574-8847-4c2e-ac1b-64c12ff2e636)

  Tera Term 5.2 and Tera Term 4.108 use the same color profile.

**Comment by nmaya** [comment]
Hi,

I confirmed this issue.

@zmatsuo 
htop を実行すると、このようなデータが受信されています。
```
  1[39m(B[0;1m[[30m[28X[3;35H0.0%[39m]
```

"0.0%" のところは `ESC [ 30 m` の色を引き継いでいて、黒になるのが正しいのでしょうか？
5.x になって正しい動作をするようになった（4.x では誤っていた）ということでしょうか？
PuTTY でも該当部分は灰色で表示されるので不思議です。

**Comment by zmatsuo** [comment]
@FQDianYan

Thank you for this issue.
I also confirmed.

@nmaya

```
echo -e "\e[1mbold\e[30m+black\e[0mnormal"
```
で出力すると、"+black"のところが htop で見えなくなる部分と
同じ文字属性になります。

Tera Term 5では見えなくなります。
Tera Term 4, PuTTYでは灰色で見えます。

boldを取ってみると
```
echo -e "\e[30m+black\e[0mnormal"
```
Tera Term 4, PuTTYでも見えなくなります。
bold属性に何か秘密がありそうです。
Tera Term 4のソースを調べてみます。

**Comment by nmaya** [comment]
@zmatsuo もしかして black + bold を bright black で表示する処理が入っている（そして5になるときに抜けた）のでしょうか？

**Comment by zmatsuo** [comment]
@nmaya

3202742 (22-09-19) に行った、
カラーテーブルの色並びを変更した際にミスしていました。
Tera Term 5.0 からこの不具合は入っていました。
失礼しました。

@FQDianYan

I fixed. Please try next binary.
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49342594/artifacts

**Comment by FQDianYan** [comment]
After I tested Tera Term 5.3 dev 20240307, this issue has been resolved. I'm going to close this issue.
![屏幕截图 2024-03-09 172956](https://github.com/TeraTermProject/teraterm/assets/23021381/8e2c4428-d6ee-42e6-8fde-1ec5984fbfd6)
