### ISSUE TITLE
ウィンドウタイトルが文字化けする

### ISSUE THREAD

**Issue by mulder-3bvh** [TeraTermProject/teraterm#142]
マクロファイルを使用していますが、
Ｖ４（４．１０８）では文字化けしませんでしたが、
Ｖ５（５．１、５．２とも）では文字化けします
マクロファイルには、以下の内容を別設定ファイルへ出力し参照させています
Title=ＡＢＣーあいうえお（日本語）
TitleFormat=5
AcceptTitleChangeRequest=last

使用環境は以下の内容です
エディション	Windows 11 Pro
バージョン	23H2
インストール日	‎2022/‎10/‎06
OS ビルド	22631.3155
エクスペリエンス	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by nmaya** [comment]
マクロでINIファイルを生成し、そのINIファイルをttermproに渡している（connect の引数に INI ファイルを指定している？）ということでしょうか？
NIファイルの文字コードはどうなっていますか？
