### ISSUE TITLE
マクロファイル名が日本語名だと文字化けする

### ISSUE THREAD

**Issue by mulder-3bvh** [TeraTermProject/teraterm#143]
日本語のマクロファイルを使用していますが、
マクロファイル実行時に表示されるダイアログに表示されるファイル名が
文字化けしていました
Ｖ４（４．１０８）では文字化けしませんでしたが、
Ｖ５（５．１、５．２とも）では文字化けします

使用環境は以下の内容です
エディション	Windows 11 Pro
バージョン	23H2
インストール日	‎2022/‎10/‎06
OS ビルド	22631.3155
エクスペリエンス	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by nmaya** [comment]
報告ありがとうございます。現象を確認しました。

**Comment by zmatsuo** [comment]
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49367072/artifacts
修正したバイナリです。
試していただけないでしょうか

**Comment by nmaya** [comment]
ありがとうございます。
日本語ファイル名が化けずに表示されることを確認しました。

**Comment by zmatsuo** [comment]
ありがとうございます。
mainにマージしました。
クローズします
