### ISSUE TITLE
ダブルクリック選択範囲が期待と異なる

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#146]
## 概要
ダブルクリック選択範囲が 5.1 と 5.2 で異なります。

## 再現手順
事象１）
echo '===###@@@' のようにして、
```
===###@@@
```
と表示します。
「###」部分をダブルクリックします。
5.1 では ### だけが選択されます。
5.2 では 行が選択されます。

事象２）
echo '===  aaa  ###  bbb  (((@@@)))  ccc  ===' のようにして、
```
===  aaa  ###  bbb  (((@@@)))  ccc  ===
```
と表示します。
「###」部分をダブルクリックしたとき、5.1 では ### だけが選択されますが 5.2 では 「  ###  」が選択されます。
「@@@」部分をダブルクリックしたとき、5.1 では @@@ だけが選択されますが 5.2 では「  (((@@@)))  」が選択されます。

## 期待の動作
5.1 の挙動のように、ダブルクリック選択が Delimiter characters に指定の文字で区切られることを期待します。

## 環境
Windows10 Pro 22H2
zip 展開後 ttermpro.exe をダブルクリックにて起動（デフォルト iniファイル）

**Comment by nmaya** [comment]
@zmatsuo #116 の対応の影響でしょうか？

**Comment by nmaya** [comment]
@zmatsuo 確認ありがとうございます。

> 連続してる前の行、次の行まで選択する動作にしたほうが

前後の行まで選択されるかどうかを制御する EnableContinuedLineCopy という設定があります。

> それと行頭行末で必ず選択が止まる

行頭行末で止まるのは EnableContinuedLineCopy が off のときの動作ですが、5.2 ではそのように動作しないことを確認しました。
行をまたぐときの動作に関する話題は #148 に移動していただけるでしょうか。

**Comment by sempreff** [comment]
対応ありがとうございます。期待通りの動作になりました。

**Comment by zmatsuo** [comment]
mainにマージしました。クローズします。
