### ISSUE TITLE
EnableContinuedLineCopy を off にしても on の動作をする

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#148]
それと行頭行末で必ず選択が止まるのではなくて
連続してる前の行、次の行まで選択する動作にしたほうが
4系と同等動作となりそうです。
![image](https://github.com/TeraTermProject/teraterm/assets/6488847/b200bc23-08cd-4167-9930-30b52abf87ff)
(cをダブルクリックするとbからdが選択される)

修正します。

_Originally posted by @zmatsuo in https://github.com/TeraTermProject/teraterm/issues/146#issuecomment-1979119953_

-----
5.2 では、EnableContinuedLineCopy の設定にかかわらず、ダブルクリックで前後の行も連続して選択されます。5.1, 4.108 では問題ありません。
以下テスト結果です。

4.108 / EnableContinuedLineCopy=on / aまたはcまたはeの部分をダブルクリック
期待した動作をする
![4_108-on](https://github.com/TeraTermProject/teraterm/assets/5668936/83032860-8d33-437f-93fb-cbfa68797e1d)

4.108 / EnableContinuedLineCopy=off / aの部分をダブルクリック
期待した動作をする
![4_108-off-a](https://github.com/TeraTermProject/teraterm/assets/5668936/0f9b64e8-fafc-4225-ac27-09486dabfcb2)

4.108 / EnableContinuedLineCopy=off / cの部分をダブルクリック
期待した動作をする
![4_108-off-c](https://github.com/TeraTermProject/teraterm/assets/5668936/eff7bd8a-36fa-47c7-8143-3f55c4b7f8b2)

4.108 / EnableContinuedLineCopy=off / eの部分をダブルクリック
期待した動作をする
![4_108-off-e](https://github.com/TeraTermProject/teraterm/assets/5668936/9b0c4510-2b4c-42dd-be5e-00d896e96baf)

5.1 / EnableContinuedLineCopy=on / aまたはcまたはeの部分をダブルクリック
期待した動作をする
![5_1-on](https://github.com/TeraTermProject/teraterm/assets/5668936/ab4f9a76-88da-49cf-88fb-eb23124d74f2)

5.1 / EnableContinuedLineCopy=off / aの部分をダブルクリック
期待した動作をする
![5_1-off-a](https://github.com/TeraTermProject/teraterm/assets/5668936/c6030e4e-5392-4e98-b19e-2c7d4d2869ff)

5.1 / EnableContinuedLineCopy=off / cの部分をダブルクリック
期待した動作をする
![5_1-off-c](https://github.com/TeraTermProject/teraterm/assets/5668936/74d286e5-a10a-48d2-9e43-6d7cc1e4ebf9)

5.1 / EnableContinuedLineCopy=off / eの部分をダブルクリック
期待した動作をする
![5_1-off-e](https://github.com/TeraTermProject/teraterm/assets/5668936/8d816287-4c7e-468d-bc61-cd74f435ed90)

5.2 / EnableContinuedLineCopy=on / aまたはcまたはeの部分をダブルクリック
期待した動作をする
![5_2](https://github.com/TeraTermProject/teraterm/assets/5668936/5239a328-37aa-4e50-9251-5656536b80d8)

5.2 / EnableContinuedLineCopy=off / aの部分をダブルクリック, cの部分をダブルクリック, eの部分をダブルクリック
5.1, 4.108 と同じ動作を期待するが、そうはならない。onの時と同じ動作をする。
![5_2](https://github.com/TeraTermProject/teraterm/assets/5668936/5239a328-37aa-4e50-9251-5656536b80d8)

**Comment by zmatsuo** [comment]
#148ブランチ 4092f66c をビルドしました。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49369411/artifacts
試してみてください。

**Comment by nmaya** [comment]
> 設定を反映していませんでした。

確認しました。

TODO
- [ ] 変更履歴

> ダブルクリックでワード選択後のドラッグでも

こちらも確認しましたが、#148 の不具合とは別の修正であると考えます。

TODO
- [ ] 変更履歴（バグ修正ではなく変更のほうへ）

**Comment by zmatsuo** [comment]
変更履歴を追加して
main にマージしました。
クローズします。
