### ISSUE TITLE
Tera Term 5.2 - Problem displaying French characters

### ISSUE THREAD

**Issue by Amdien** [TeraTermProject/teraterm#150]
Since the version 5, there is problem with French characters.
Exemple in 4.106 :
![TT4 106](https://github.com/TeraTermProject/teraterm/assets/162688392/19850662-b58b-4590-9089-a3f68c174576)
In 5.2 :
![TT5 2](https://github.com/TeraTermProject/teraterm/assets/162688392/13f92108-5d01-4eaf-9a75-f5904c87fc20)

My config is in the 2  case :
![TTconfig](https://github.com/TeraTermProject/teraterm/assets/162688392/eecc7991-50f9-404a-a1c9-61a652cd76af)

Thanks !

**Comment by nmaya** [comment]
Hi,

I don't have French Windows environment, don't know what font is installed by default, can not try combination of settings.
Please look for a setting which displays accent characters well.

- "Setup" - "Additional settings" - "Font" - "VTWindow Font" - "font"
- "Setup" - "Additional settings" - "Font" - "VTWindow Font" - "script"
- "Setup" - "Additional settings" - "Coding" - "Anbiguous Character width"

Thanks,

**Comment by Amdien** [comment]
Yes !
I find with change the code in "Coding" - "Coding  receive"
Thank !
