### ISSUE TITLE
Tera Term 5.2 - Full screen don't work the first time

### ISSUE THREAD

**Issue by Amdien** [TeraTermProject/teraterm#151]
Since 5.0, when you click on the square to have the full screen, it doesn't work.
![image](https://github.com/TeraTermProject/teraterm/assets/162688392/ad24ee77-7fbf-41a9-8631-ee9870fb361e)

It's ok only the 3rd time.
It was ok in version 4.

Thanks !

**Comment by nmaya** [comment]
Hmm, I could not reproduce this issue.

**Comment by Amdien** [comment]
I have find this :
It's only with the option "PopupMenu=on"

**Comment by zmatsuo** [comment]
Thank you for reporting.

I confirmed this issue.

**Comment by Amdien** [comment]
I confirme the solution.
It's ok for me.
Thanks.
