### ISSUE TITLE
SelectOnActivate は右クリックも無効化してしまう

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#155]
## 概要
SelectOnActivate が off の時、
左クリックだけが無効になってほしいのですが
右クリックも無効になっています。

## 期待の動作
非アクティブなウィンドウに左クリックしたときにマウスが滑って選択を開始してしまうことを避けつつ、
非アクティブなウィンドウに右クリックしたときにはウィンドウをアクティブにし、かつペーストできる
という動きになると良いと思っています。

## 環境
Windows10 Pro 22H2

**Comment by nmaya** [comment]
確認したいことがあります。

この「期待する動作」は 4.x の動作と同じ（5.0 から期待しない動作になった）ですか？

**Comment by sempreff** [comment]
いいえ。
4.107 は、期待の動作ではありません。

**Comment by sempreff** [comment]
history.html と teraterm-win.html を更新しました。

**Comment by zmatsuo** [comment]
main にマージしました。 3fab9e4 です。
