### ISSUE TITLE
TTSSH に相対パスを渡した場合の扱いが Tera Term と異なる

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#159]
Tera Term 5 では [/F=](https://teratermproject.github.io/manual/5/ja/commandline/teraterm.html#f) 引数のファイル名が絶対パスでないときは、%APPDATA%\teraterm5\ からの相対パスと見なされるようになりました。

TTSSH の INI ファイルの指定 [/f](https://teratermproject.github.io/manual/5/ja/commandline/ttssh.html#f), [/ssh-f](https://teratermproject.github.io/manual/5/ja/commandline/ttssh.html#ssh-f), [/ssh-consume](https://teratermproject.github.io/manual/5/ja/commandline/ttssh.html#ssh-consume) はこの変更に対応できていないようです。
また、[/keyfile](https://teratermproject.github.io/manual/5/ja/commandline/ttssh.html#keyfile) の扱いも一貫しているべきと思います。

> ファイル名が絶対パスでないときは、ttxssh.dll からの相対パスと見なされます。

### origin
https://osdn.net/projects/ttssh2/ticket/57660

TeraTerm 5.2 document for /F option says If this value is not a full path, it is understood as a relative path from %APPDATA%\teraterm5\

I made a copy of the TERATERM.INI file to modified new file to %APPDATA%\teraterm5\TERATERM_AM.INI and make sure it's saved in UTF-16LE with BOM format
I then changed 3 options in TERATERM_AM.INI

```
AutoWinClose=off
CipherOrder=MKN>H:J=G09
LogLevel=200
```

if I launch like this, only AutoWinClose takes effect. CipherOrder (reported by SSH server) and LogLevel (TTSSH.LOG doesn't have detailed content) doesn't do anything. if I add /ssh-v to command then LogLevel works, but CipherOrder still doesn't work
```
"C:\Program Files (x86)\teraterm5\ttermpro.exe" 10.10.227.1:22 /F="TERATERM_AM.INI" /ssh /2 /auth=password /user=guest /passwd=guest
```

if I launch like this with full path to file, then AutoWinClose, CipherOrder and LogLevel all take effect
```
"C:\Program Files (x86)\teraterm5\ttermpro.exe" 10.10.227.1:22 /F="%APPDATA%\teraterm5\TERATERM_AM.INI" /ssh /2 /auth=password /user=guest /passwd=guest
```

**Comment by zmatsuo** [comment]
修正しました。
チェックしていただけないでしょうか。

**Comment by nmaya** [comment]
確認しました。ありがとうございます。

**Comment by zmatsuo** [comment]
ありがとうございます。
mainにマージしました。
クローズします。
