### ISSUE TITLE
AppVeyor で実行される処理を調整

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#16]
### リリースで使わない処理が呼び出されているので整理する

- Cygwin へ cmake をインストール
  - Visual Studio の cmake が入っていればそれでよくないか？
- install_cygwin.cmake の実行
  - ビルドのたびに時間（ネットワーク負荷・電力）がかかる
  - 元々 Cygwin が入っているので不要？
    - 最新版の Cygwin を使うために実行している？
    - 最新版にしたければ、元々入っている Cygwin をコマンドラインで更新すればよくないか？
  - これを使うと 32bit コンパイラのインストールができる
    - もう 32bit バイナリはインストーラに含めなくなったのでいらない
- pacman.exe
  - AppVeyor でのビルドで msys は使わない

**Comment by zmatsuo** [comment]
### Cygwin の cmake

cygwinのツールと cygwinではない普通のcmake を混ぜて使っていると
何かでフルパスの判定を誤るんだと思うのですが、
"c:/～～" と "/cygdrive/c/～～" が混ざって "/cygdrive/c/c:/～～"
などとなってしまうことがありました。
cygwin に関連するツールを使ったビルドは
cygwin の cmake を使うほうが問題が出にくいなということで
そのようにしていました。
ただ、どうやったら発生するのかは忘れてしまったのと、
今はこういう問題は出ないようになっているかもしれないです。

### install_cygwin.cmake の実行

- ビルドのたびに時間（ネットワーク負荷・電力）がかかる

インストール済みのcygwinが普通に使えるならそちらを使ったほうが
楽かもしれないです。(パッケージは何か入れないといけないかも)

appveyor_vs2022_bat.yml の cache: に
buildtools/cygwin64 を追加すると解決するかもしれないです。

- 元々 Cygwin が入っているので不要？

AppVeyor環境のCygwinを更新
(必要なパッケージをインストール)すればよさそうです。

最初は自分の環境の cygwin に
32bitコンパイラを入れるのに気が引けるので
buildtools/cygwin64 にビルド用 cygwin を準備していました。

ビルド用 cygwinが準備できれば、
cygwinが無い環境(AppVeyor以外、GitHubも?、Cygwinの入っていないPCなど)でも
ビルドできるので便利です。

## pacman

msys2term、MinGW で Tera Term をビルドしたくて入れています。
使っていないなら削除したほうがビルドが安定しそうです。

**Comment by nmaya** [comment]
### Cygwin の cmake

> cygwin に関連するツールを使ったビルドは
> cygwin の cmake を使うほうが問題が出にくいなということで

AppVeyor でのビルド（rebease.bat を使ったビルド）で、これらは確認していますが

- download.cmake でのダウンロード
- iscc.bat での tar, rename

cygwin 配下ののビルドに cmake が使われていましたっけ？


### install_cygwin.cmake の実行

> パッケージは何か入れないといけないかも

これは調べてみないとわかりませんね。

> appveyor_vs2022_bat.yml の cache: に
> buildtools/cygwin64 を追加すると解決するかもしれないです。

それも一案ですが、1GB を超えてしまうので厳しいです。

https://www.appveyor.com/docs/build-cache/#cache-size-beta

> cygwinが無い環境

有用性は理解していますし便利に使っていますが、appveyor_xxx_bat.yml, build_appveyor_xxx.bat の話をしています。

**Comment by nmaya** [comment]
> > パッケージは何か入れないといけないかも
> 
> これは調べてみないとわかりませんね。

install-cygwin.cmake で setup に指定しているパッケージを見てみました。
```
appveyor@appveyor-vm ~
$ cygcheck -c cmake bash tar make perl gcc-core gcc-g++ iconutils
Cygwin Package Information
Package              Version        Status
bash                 5.2.15-3       OK
gcc-core             11.4.0-1       OK
gcc-g++              11.4.0-1       OK
make                 4.4.1-2        OK
perl                 5.36.1-1       OK
tar                  1.35-1         OK

appveyor@appveyor-vm ~
$ cygcheck -c perl-JSON perl-LWP-Protocol-https
Cygwin Package Information
Package              Version        Status
```

必要最低限のものは入っていそうです。

**Comment by zmatsuo** [comment]
> cygwin 配下ののビルドに cmake が使われていましたっけ？

install\release.bat (installer\build.bat) からは
使っていませんでした。

> それも一案ですが、1GB を超えてしまうので厳しいです。

キャッシュサイズ制限にかかるなら使えないですね。

> 有用性は理解していますし便利に使っていますが、appveyor_xxx_bat.yml, build_appveyor_xxx.bat の話をしています。

いつもダウンロードだと
環境によって場合分けなくていいかなと思っていました。
制限があるのと、ビルド速くしたいのはあるので
インストール済みを使うのがよさそうです。

> 追加で discord への通知用のを入れるか、cmake を入れるか、あとは全体の更新をかけるかどうかですね。

まずは、通知を外して安定したビルドを目指しましょうか

全体の更新はどうしましょう。悩ましいです。
更新するよりもAppVeyorの準備したイメージが安定しているであろう、
という方針(dockerでよく使う方針だと思っています)で、
そのまま全体の更新はしないのはどうでしょう。

**Comment by nmaya** [comment]
修正をコミットしました。

以下の4つを別の bat にしました。

- 独自 Cygwin のインストール
  - 呼び出さないようにしました
- システムの Cygwin に cmake と perl-JSON,perl-LWP-Protocol-https のインストール
  - これは呼び出すようにしました
- システムの Cygwin のアップデート
  - これは呼び出さないようにしました
- pacman.exe で cmake を入れる
  - これは呼び出さないようにしました
 
呼び出すかどうかは yml への記述で選択が可能です（「ローカルでは独自Cygwinを入れる」など）。

**Comment by nmaya** [comment]
> https://ci.appveyor.com/project/teraterm/github-main

リポジトリを、プロジェクトのほうを見るようにさせてもらいました。

> https://ci.appveyor.com/project/teraterm/github-main/builds/48417739

最後まで走りました。
