### ISSUE TITLE
/V 指定で起動した ttermpro.exe がクラッシュする

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#160]
## 再現方法
- 4.108 の zip版を展開し、コマンドプロンプトで展開先ディレクトリに cd する。
- ttermpro.exe /V [ENTER] で New Connection ダイアログを出し、リモートホストに ssh でログインする。
- ttermpro.exe [ENTER] でウィンドウを開き、New Connection ダイアログをキャンセルする。
- Broadcast command で先に接続した方を選択し、入力欄に exit と打鍵して Submit する。
- Application fault ダイアログが出る。

5.2 でも同様の手順でクラッシュしました。
5.2 の場合は Application fault ダイアログの前に teraterm_176aed267_yyyymmdd-hhmmss.dmp と書かれた OKダイアログが出ます。

#157 の動作を確認しようとして気づきました。
/V オプションで起動したプロセスを安全に終了させる方法が不明です。

## 環境
Windows10 Pro 22H2

**Comment by sempreff** [comment]
旧バージョンの挙動を確認しました。
4.74 ～ 4.99 はクラッシュしません。
4.100 ～ はクラッシュします。

**Comment by zmatsuo** [comment]
> 5.2 の場合は Application fault ダイアログの前に teraterm_176aed267_yyyymmdd-hhmmss.dmp と書かれた OKダイアログが出ます。

ダンプファイルが %LOCALAPPDATA%\teraterm5 にできています。

ビルドしたPCと、ttermpro.exeを実行していてダンプが出たPCが同一なら
dmpファイルをダブルクリックするとVisual Studioが起動します。
そのまま▶(ネイティブのみでデバグ)を押すとプログラムの様子を見ることができます。
exeがdebugビルドならソース付きで見ることができます。

[release.md](https://github.com/TeraTermProject/teraterm/blob/main/installer/release.md)の最後に少しだけ書いてあります。参照ください。

**Comment by sempreff** [comment]
おかげさまでクラッシュ回避できるようになったと思います。

**Comment by zmatsuo** [comment]
GitHubの便利機能を使ってPRを楽にマージできないかなと思っています。
詳しかったらコメントいただけないでしょうか。 #177 です。

**Comment by zmatsuo** [comment]
mainにマージしました。
クローズします。
