### ISSUE TITLE
マクロでパスワードファイルが読み込めない

### ISSUE THREAD

**Issue by taimorin** [TeraTermProject/teraterm#161]
TeraTerm 5.x にてNASに保存したttlファイルをttpmacro.exeで開くとgetpasswordでパスワードを読み込めずパスワード入力ダイアログボックスが表示される。4.108では問題なく動作する。

**Comment by nmaya** [comment]
パスワードファイルを相対パスで指定していますか？
getdir で得られる「マクロの現在のディレクトリ」は、4.108と5.xで異なりますか？

**Comment by taimorin** [comment]
ttlとパスワードは同じディレクトリに保存しており相対パスで指定しています。
getdirで取得したディレクトリは4.108と5.xで同じ結果でした。

追加検証したところローカルのHDDでもディレクトリ名に日本語を含むとパスワードファイルが読めませんでした。
共有フォルダかどうかは関係なさそうです。

**Comment by zmatsuo** [comment]
指摘ありがとうございます。
パスワードファイルがUnicodeに対応していませんでした。

修正しました。試してみてください。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49412908

**Comment by taimorin** [comment]
ご対応ありがとうございます。
パスワードファイル問題なく読み込めるようになりました。

**Comment by zmatsuo** [comment]
確認ありがとうございました。
修正はmainにマージしました。
クローズします。
