### ISSUE TITLE
開発作業メモへの追記

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#162]
### 対象
reference/develop-memo.html

### 内容
- [x] TERATERM.INI
  - 「項目名」の命名規則だけある
  - デフォルトのファイル（installer\release\TERATERM.INI）への追加
  - Tera Term 設定ファイルの全項目一覧（setup/teraterm-ini.html）への追加
  - UIがある場合は menu/setup.html 配下のどこか（該当するダイアログのページ）に説明を追加
  - UIがない場合（special options）は setup/teraterm.html（該当する分類のページ）に説明を追加
- [x] [国際化メッセージの追加](https://github.com/TeraTermProject/teraterm/wiki/Add-i18n-message) に関する記述
  - オンラインだけでなく、開発作業メモにも載せたらよい内容だと思う
- [x] [ライブラリバージョンアップ時の変更箇所](https://github.com/TeraTermProject/teraterm/wiki/Update-library)に関する記述
  - オンラインだけでなく、開発作業メモにも載せたらよい内容だと思う

**Comment by nmaya** [comment]
TERATERM.INIについて改稿(a213349), i18nについて追記(de45462), ライブラリのアップデートについて追記(cbf799c) しました。
しばらくしたらマージします。

**Comment by zmatsuo** [comment]
👍

かっこがくっついているようです。
```
--- a/doc/en/html/reference/develop-memo.html
+++ b/doc/en/html/reference/develop-memo.html
@@ -53,7 +53,7 @@ It recommends that the new name like as Baz....
     </ul>
   </li>
   <li>Default INI file<br />
-      installer\release\TERATERM.INI)</li>
+      installer\release\TERATERM.INI</li>
 </ul>

--- a/doc/ja/html/reference/develop-memo.html
+++ b/doc/ja/html/reference/develop-memo.html
@@ -53,7 +53,7 @@
     </ul>
   </li>
   <li>デフォルトの INI ファイル<br />
-      installer\release\TERATERM.INI）</li>
+      installer\release\TERATERM.INI</li>
 </ul>

```

**Comment by nmaya** [comment]
マージしました。確認ありがとうございました。
