### ISSUE TITLE
マクロコマンド拡張コマンドの追加

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#167]
Cコンパイラの(-std=c++20のような)オプション、
perl use、visual basic の Option のようなキーワードを追加して
互換性を保ちつつ拡張できるようにする提案です。

仮にキーワードをextendとすると、
例えば

```
extend listbox v2
```

とすると、listboxの動作がversion2に切り替わります。
元に戻すときは v1 とします。

文字列を渡すとしたほうが拡張性が高いでしょうか

```
extend "listbox" "doubleclick=on,minmaxbutton=on,large=on"
```

**Comment by nmaya** [comment]
> extend listbox v2

「2 とは何か」というのがわかりづらいように思います。

> extend "listbox" "doubleclick=on,minmaxbutton=on,large=on"

こちらのほうが、なにをしているか分かりやすそうです。

-----
「拡張された機能への引数の渡し方」が問題になりませんか？

これまでの拡張は、[logopen](https://teratermproject.github.io/manual/5/ja/macro/command/logopen.html)のように引数を増やしていくやり方でした。
新しい機能の引数を追加し、デフォルトを「今までどおりの動作」に振っていました。

```
listbox <message> <title> <string array> [<selected>]
```

#154 に書いたようなオプションを取らせる場合、「機能Aが有効な場合の引数」「機能Bが有効な場合の引数」があり得ます。
どの組み合わせの場合でも同じ指定ができるようにするべきです。「minmaxbutton=onの場合は第5引数が最小化/最小化の指定」「resizable=onの場合は第5引数が幅、第6引数が高さ」というような仕様は、煩雑かつ破綻しています。

```
; listbox <message> <title> <string array> [<selected> [<minmax> [<width> [<height>]]]]
extend "listbox" "resizable=on"
listbox 'message' 'title' ary_list 0 **0** 400 300
; minmax 機能は有効ではないが、width 引数を指定するには minmax の引数を指定しなければならない
```

**Comment by zmatsuo** [comment]
>>    extend listbox v2
>
> 「2 とは何か」というのがわかりづらいように思います。

version2 という感じです。
-std=c++20 の20ってなに?と同じ感じですね。
ドキュメント参照くださいになりそうです。

> 煩雑かつ破綻しています。

確かにこれは破綻します。

**Comment by zmatsuo** [comment]
キーワード引数がlistboxで導入されました。

キーワード引数を使用してコマンドの拡張を行っていけば
拡張コマンドを導入しなくてもよさそうです。

このissueはクローズします。
