### ISSUE TITLE
Broadcast command ダイアログのリストボックスがステータスバーにカブっている

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#168]
## 概要
ウィンドウ一覧のリストボックスがステータスバーにカブってしまっています。
windowsのテーマの設定が悪いのだろうと思っていましたが、調整できると良いと思います。

## 事例
4.106 windows7 OK
![4-106-win7](https://github.com/TeraTermProject/teraterm/assets/8304186/76c89054-01ba-4c5c-b1e9-64b1c7cd7828)
4.106 windows10 カブっている
![4-106-win10](https://github.com/TeraTermProject/teraterm/assets/8304186/4f66840d-3cb6-4b7b-a08d-e9ff6845b52c)
4.106 windows11 カブっている
![4-106-win11](https://github.com/TeraTermProject/teraterm/assets/8304186/69c8ee8a-9f9d-408c-bc94-49904596ff2e)
5.2 windows7 カブっている
![5-2-win7](https://github.com/TeraTermProject/teraterm/assets/8304186/8d491ca4-cd9b-4f76-8bab-4b2fe6a3a673)

**Comment by zmatsuo** [comment]
mainにマージしました。
クローズします。
