### ISSUE TITLE
カラー反転時(白背景、黒文字)にマウスで文字選択しても選択された文字は色が反転しない

### ISSUE THREAD

**Issue by YoshiYoshiYoshy** [TeraTermProject/teraterm#172]
背景色を黒、文字色を白の状態でマウスを用いて文字を選択すると、選択された文字は色が反転して表示されます (背景 黒、文字 白)。

しかしながら、背景色を白、文字色を黒の状態でマウスを用いて文字を選択しても、選択された文字は色が反転しません。
そのため、本当に文字が選択されたのかが見た目では分かりません。
Ver. 4 までは、そのようなことは無かったです。
長らく、背景色を白、文字色を黒の状態で使ってきたので、現行バージョンでも そのようにして欲しいです。

**Comment by sempreff** [comment]
修正されるまでの回避策として、「設定」→「その他の設定」→「表示」の「反転属性色を有効にする」のチェックを外してみるとどうでしょうか。

**Comment by sempreff** [comment]
初期状態では「標準の色は黒背景・白文字」かつ「反転の色は白背景・黒文字」なので、もしかすると

「設定」→「ウィンドウ」で下段の「カラー」の「属性」ドロップダウンの「標準」について「反転ボタン」しただけだと、
標準の表示が白背景・黒文字になっただけで、「属性」が「反転」の時の色と同じになってしまっている、という状況ではないでしょうか。
（「反転」ボタンは、選択されている「属性」だけに作用する、ということのようです。）

「属性」のドロップダウンで「反転」を選んで「反転ボタン」で色を変えておくと、選択部分がわかるようになると思います。

**Comment by nmaya** [comment]
@YoshiYoshiYoshy これは #58 で議論された内容と同じですか？

**Comment by YoshiYoshiYoshy** [comment]
> 修正されるまでの回避策として、「設定」→「その他の設定」→「表示」の「反転属性色を有効にする」のチェックを外してみるとどうでしょうか。

試したところ、反転表示されるようになりました。ありがとうございます。

**Comment by YoshiYoshiYoshy** [comment]
> @YoshiYoshiYoshy これは #58 で議論された内容と同じですか？

確かに #58 の内容です。ご指摘ありがとうございます。

**Comment by zmatsuo** [comment]
反転表示しているのがわからない色設定のとき警告出す機能があればよいのかな・・
もう少し様子を見ようと思います。
クローズします。
