### ISSUE TITLE
additional settings menu

### ISSUE THREAD

**Issue by LaurV2** [TeraTermProject/teraterm#179]
the "Tray test" and "popup test" buttons are reversed
(maybe already reported, but I can't read Japanese, sorry)
pressing "tray" opens a popup
pressing "popup" opens a tray
windows 10, downloaded the zip (not compiled by myself)

**Comment by nmaya** [comment]
Thank you for your reporting. I was not aware of that.

I am not a developer who put them, but I guess these buttons are present for largely debugging.

Thanks,

**Comment by zmatsuo** [comment]
tray image:

![tray_marked](https://github.com/TeraTermProject/teraterm/assets/6488847/f20d9146-8b49-4cbd-aeda-b871b07d5ba0)


popup image:

![popup_marked](https://github.com/TeraTermProject/teraterm/assets/6488847/2a5c2cd1-5b80-44d1-a5fe-88d7b7c4b43a)


[tray test] button is very important on Windows 10.

When select "Tera Term のすべての通知をオフにする(Turn off all Tera Term notifications)", very difficult to turn on again without [tray test] button.
![tray_off](https://github.com/TeraTermProject/teraterm/assets/6488847/d9450e21-5585-4a1b-97b4-ab1d83fdc7e8)


see next (Japanese)
https://osdn.net/projects/ttssh2/ticket/46094

**Comment by nmaya** [comment]
### 動作テスト結果
![test-botton](https://github.com/TeraTermProject/teraterm/assets/5668936/74fa4afc-8f73-43c4-88b0-22268bd27631)


### Popup test の動作

- Win7, Win8.1
  - (1) 通知領域（タスクトレイ）にアイコンが表示される
  - (2) バルーン通知が表示される
- Win10, Win11
  - (1) 通知領域（タスクトレイ）にアイコンが表示される
  - (2)' アプリ通知が表示される

(2) は「吹き出し状の[ポップアップメッセージ](https://www.ipentec.com/document/csharp-show-popup-message-on-tasktray)」と呼ばれることがある。
(2)' は「[通知バナー](https://ascii.jp/elem/000/001/114/1114188/)」や「[トースト通知](https://learn.microsoft.com/ja-jp/windows/apps/design/shell/tiles-and-notifications/toast-notifications-overview)」と呼ばれることがある。今は「[アプリ通知](https://learn.microsoft.com/ja-jp/windows/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts?tabs=appsdk)」と呼ぶようになったようです。


### Tray test の動作

- Win7, Win8.1, Win10, Win11
  - (3) 通知領域（タスクトレイ）にアイコンが表示される
  - (4) (3)により通知設定ができるようになったことが、MessageBox のメッセージにより説明される

### なにが混乱をもたらしたか（予想）
- UI では (2) の通知を「ポップアップ」と呼んでいる
- (4) の MessageBox がポップアップだと思われている

ということではないでしょうか。


### "Popup test" ボタンの改善案
名前を "Notify test" にしてはどうでしょうか？


### "Tray Test" ボタンの改善案
"Tray Test" ボタンの用途（https://osdn.net/projects/ttssh2/ticket/46094 の経緯）は以下のようです。

```
通知を出ない状態にしてしまうと元に戻せない
General tab に アイコンを一時的に表示する "Tray test" ボタンを追加しました。
手もとではこの機能で一時的にアイコンを表示しておいて、 出なくなったポップアップ通知を再度出る状態に戻すことができました。
```

経緯を読むと、なんのためにあるのか説明が不足しているように感じます。
Windows の動きがわかっていないと何を言っているかわかりづらいのですが、以下のような感じで[ドキュメント](https://teratermproject.github.io/manual/5/ja/menu/setup-additional.html)に書くのはどうでしょうか？

```
通知領域にアイコンを表示します
「Tera Term のすべての通知をオフにする」と、「Tera Term」が Windows の「通知」の設定に表示されなくなり、設定を変更できなくなることがあります。このボタンを押して通知領域にアイコンを表示している最中だと、Windows の「通知」の設定を変更できます。
```

**Comment by zmatsuo** [comment]
> 経緯を読むと、なんのためにあるのか説明が不足しているように感じます。

そうですね。
ドキュメントを修正します。

**Comment by zmatsuo** [comment]
I update document(manual) and messages.

@LaurV2 Please try this binary.
https://ci.appveyor.com/project/teraterm/github-main/builds/49513608/artifacts


@nmaya
作ったブランチをすぐにmainにマージしてしまいました。
失礼しました。

通知領域、タスクトレイ や バルーン通知、アプリ通知 については用語集に書いて
マニュアル中には用語集へのリンクを作るのがよいかもしれないです。

**Comment by zmatsuo** [comment]
> 通知領域、タスクトレイ や バルーン通知、アプリ通知 については用語集に書いて
> マニュアル中には用語集へのリンクを作るのがよいかもしれないです。

作ってみました。
作っていただいた画像も盛り込んでみました。
#179_modify_document ブランチです。

特に何もなければ2,3日で main にマージします。

**Comment by zmatsuo** [comment]
「通知領域」というのが最新の名称かなと書いていましたが、
Windows11は「通知センター」のようです。

[タスク バーの通知領域をカスタマイズする](https://support.microsoft.com/ja-jp/windows/%E3%82%BF%E3%82%B9%E3%82%AF-%E3%83%90%E3%83%BC%E3%81%AE%E9%80%9A%E7%9F%A5%E9%A0%98%E5%9F%9F%E3%82%92%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA%E3%81%99%E3%82%8B-e159e8d2-9ac5-b2bd-61c5-bb63c1d437c3#WindowsVersion=Windows_11)

修正してpushしました。

**Comment by zmatsuo** [comment]
mainにマージしました。
https://ci.appveyor.com/project/teraterm/github-main/builds/50291331/artifacts

クローズします。
