### ISSUE TITLE
Window setup で No frame のチェックのみを操作した時に反映されない

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#181]
## 概要
Window setup で Hide title bar のチェックが ON の時、
No Frame のチェックを操作できます。
Hide title bar のチェックを操作せずに No Frame のチェックだけを変化させた場合に、
フレームのあるなしが変化しません。

## 再現手順
1. Setup -> Window で Window setup ダイアログを出します。
1. Hide title bar のチェックを ON にして OK します。
1. 再度 Setup -> Window で Window setup ダイアログを出します。
1. No Frame のチェックだけを「元が ON なら OFFに、元が OFF なら ONに」なるように操作して、OKします。
1. Frame のあるなしが変化することが期待されますが、状態が変わりません。

## workaround
Hide title bar をいったん OFF にしておいてタイトルバーを出しておき、再度 Hide title bar を ON にする際に No Frame の ON/OFF を指定すると、出来上がりの状態にすることはできます。

**Comment by zmatsuo** [comment]
修正されているのを確認しました。
mainにマージしました。
ありがとうございました。
クローズします。
