### ISSUE TITLE
LibreSSL 3.9.1 対応

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#183]
> ttssh2\ttxssh\ttxssh.c(3093,10): warning C4013: 関数 'DSA_generate_parameters' は定義されていません。int 型の値を返す外部関数と見なします。

DSA_generate_parameters() は廃止のようです。

見ていただけないでしょうか @nmaya

libressl_3_9_0 ブランチです。
3.8.3 のlibressl_3_8_3 ブランチもpushしました。

LibreSSLのビルド時、手もとでは、32bitでは大丈夫ですが、
64bitでビルドすると次のissueと同じ状態になります。

https://github.com/libressl/portable/issues/1023

**Comment by nmaya** [comment]
DSA_generate_parameters() は deprecated で DSA_generate_parameters_ex() に置き換わったようです。
https://cvsweb.openbsd.org/src/lib/libcrypto/dsa/dsa_gen.c#rev1.31

それまでの実装はこうで、内部で DSA_generate_parameters_ex() を呼んでいる感じですね。
https://cvsweb.openbsd.org/src/lib/libcrypto/dsa/dsa_gen.c?rev=1.30&content-type=text/x-cvsweb-markup

**Comment by zmatsuo** [comment]
64bitでビルドできないのが解消されて 3.9.1 になりました。
libressl_3_9_1 ブランチを push しました。
libressl_3_9_0 ブランチを削除しました。

**Comment by zmatsuo** [comment]
それまでの DSA_generate_parameters() の実装を参考に
DSA_generate_parameters_ex() に置き換えました。
ブランチ  #183 (788193ad4a209ed82106798e4fae91c9569beb6b) です。

生成した鍵を使ってログインできるのを確かめました。

TODO のところに DSA_free(priv); を入れるほうが良いのでは?
とは思うのですが、この例外は多分発生しないのではないかと思います。

見ていただけないでしょうか @nmaya
問題なさそうでしたら main にマージしてください。

libressl_3_9_1, libressl_3_8_3 ブランチは削除しようと思います。

**Comment by zmatsuo** [comment]
LibreSSL 3.9.2 に更新して main にマージしました。

**Comment by zmatsuo** [comment]
クローズします。
