### ISSUE TITLE
Broadcast command の挙動を改善したい

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#188]
#83 と関連します。

## 現状

- IME が ON だと改行やTABやESCや Ctrl-C などが送れません
  - 4.108 だと、IME が ON でも改行や TABなどは送れるようです。日本語は送れません
  - 5.2 だと、IME が ON だと日本語は送れるのですが、改行やTABなどが送れません
- 右クリックや中クリックでペーストできません
  - Google に「teraterm ブロードキャスト」まで入れると「貼り付け できない」がサジェストされるのが不本意です
- ウィンドウが増減しないとウィンドウリストが更新されません
  - ウィンドウのタイトルを変更した場合に反映させたいです
- ウィンドウリストが更新されると選択状態がクリアされます
  - つまりウィンドウが増減すると選択状態がクリアされてしまいます
- Close ボタンの日本語表記にアクセラレータキーがありますが反応しません

## 期待の動作

- IME が ON でも各種の入力が渡っていくと良いです
- マウスによる貼り付けができると良いです
- 手動でウィンドウリストを更新できる方法があると良いです
- ウィンドウの増減やウィンドウリストの更新の際も選択状態が維持されると良いです
- ボタンの表記はユーザに誤解を与えないよう挙動に合わせられると良いです

## 回避

いくつかは、Tera Term Pro Assistant では可能です。

**Comment by zmatsuo** [comment]
HELPボタンがないことに気づきました。

追加したほうが良いと思いますが、置き場がないですかね・・。

**Comment by kattyo-abk** [comment]
#83 ご対応ありがとうございました。
Broadcast command の改善という事でコメントを残させていただきます・・・。

> 右クリックや中クリックでペーストできません 

現状での一般的な対処方法は realtime mode を解除してテキストボックスに貼り付けて submit を押す
という方法だと思います。

複数ウィンドウを起動した状態でパスワードをパスワード管理ソフトから貼り付けようとしたときに、
今ですと、以下のような操作をすることになります。
 - realtime のチェックを外す
 - History のチェックを外す（パスワードなので残したくない）
 - テキストボックスに貼り付ける
 - submit を押す
 - realtime のチェックを入れる

自然な操作としては
 - paste ボタンを設け、これを押す。ただし、
   - realtime の時はそのまま各ウィンドウに貼り付け
   - realtime 解除時はテキストボックスに貼り付け

※テキストボックスとは書いてありますが実際には Combo box です

**Comment by kattyo-abk** [comment]
> paste ボタンを設け、これを押す。ただし、 

個人的には ボタンにこだわりはありません。コンテキストメニューなどでも良いと思います。

**Comment by sempreff** [comment]
@kattyo-abk 上部の入力欄に右クリックで貼り付けできるようにしてみましたので、 [#185 のスナップショット](https://github.com/TeraTermProject/teraterm/pull/185#issuecomment-2040131948) のスナップショットを試してみてもらえると嬉しいです。

**Comment by kattyo-abk** [comment]
スナップショットを試しました。

貼り付け可能なことを確認しました。
Alt-V での貼り付けは Broadcast command ウィンドウだけですね。挙動差はドキュメントに記載したほうがいいかもしれません。
そして Shift-Insert だと選択ウィンドウに2回貼りつくようです。

右クリック: 選択されたウィンドウに貼りつけ
Alt-V: Broadcast command プロセスのウィンドウに貼り付け
Shift-Insert: 選択されたウィンドウに2回貼りつけ

**Comment by kattyo-abk** [comment]
＃スナップショットの挙動の続き

どうもホスト一覧で、ホスト名以外の部分をクリックすると、
最後に反転させたホスト名が再度反転するようです。

あと、ここまでやったのでしたら、ついでに Inverse Selection （選択を反転する）も追加するといいかも・・・？

**Comment by sempreff** [comment]
動作確認ありがとうございます。Shift-INS の二重貼り付けは修正できました。リストの挙動も確認してみます。

**Comment by kattyo-abk** [comment]
今の Broadcast command のダイアログにボタンをどんどん追加するのは微妙だけど、
リスト部でのコンテキストメニューもわかりにくいという事でしたらダイアログを拡張するのに一票です。
個人的には、右クリック即ペーストは怖い、alt-v などと挙動が違うなどの理由で明示的なコマンドボタンのほうがわかりやすいかな？と
いう思いはあります。
- 本番機器対象に作業をするときにボタンを押すという明示的な操作が伴うのがわかりやすい（特に複数人で確認しながらの作業時）
- 右クリックを押すとコンテキストメニューが出る期待感があるが今は即効ペーストが発動する
- Disable mouse R(,M) button paste をオフにすると shift-insert のみとなる（このキー操作がマイナー過ぎる）

イメージはこんな感じです。
![image](https://github.com/TeraTermProject/teraterm/assets/154403668/070c94d0-3f29-4f8f-9336-cf428833dc99)

**Comment by sempreff** [comment]
> 右クリック即ペーストは怖い
> ボタンを押すという明示的な操作が伴うのがわかりやすい

Realtime モードをオフにされると良いと思います。

**Comment by kattyo-abk** [comment]
> Realtime モードをオフにされると良いと思います。

はい、まぁそうなりますね

**Comment by nmaya** [comment]
> 選択されていないところで右クリックすると選択がなくなります。

Broadcast command では選択肢が変化しないので大丈夫ですが、html の select の multiple では変化する（Chrome/Edgeでは、一つ以上選択してから選択していないところを右クリックすると選択される）のでその感覚が私にあるのかもしれません。
https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/multiple

> イメージはこんな感じです。 ![image](https://private-user-images.githubusercontent.com/154403668/320593170-070c94d0-3f29-4f8f-9336-cf428833dc99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDY0ODIsIm5iZiI6MTcxMjc0NjE4MiwicGF0aCI6Ii8xNTQ0MDM2NjgvMzIwNTkzMTcwLTA3MGM5NGQwLTNmMjktNGY4Zi05MzM2LWNmNDI4ODMzZGM5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxMDQ5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDZiNGViOGUzMjUzN2JjMDcxMGVjYjY2ZTQ3NzhkN2ZiMWNlMjJmZTllNzgzMTViYTdkYjQ4ODU0ZDkzODFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T8wk5mWaCVnAGfupPbaXdRyzqGbNLMj-nOzBt-mGSqY)

ウィンドウでできることが全体が見渡せないのと、「私は広げて出てくる機能をよく使うので、最初から広げた状態で表示するフラグが欲しい」という要望が来そうなので、ボタンで広げられるように作るのは個人的に好きではないです。
もし作るなら常に2枚目の画像の状態になっていて「expand」「hide」がないほうがよいです。

**Comment by zmatsuo** [comment]
Realtimeモードがonの時のペーストは、
一時的にRealtimeモードが外れてコマンド入力コントロールへ貼り付けられて
送信完了(又はキャンセル?)後にRealtimeモードに戻るのはどうでしょう?

漢字変換みたいなイメージです。


ウィンドウリストの一覧性が悪くなりますが、
マウスオーバーでタイトルをtipwinで表示すれば
左右を狭くレイアウトして、ボタンを配置できそう。
いまいちか・・。

**Comment by sempreff** [comment]
私は #199 の挙動で一通り充足したと思っています。
- ダイアログを「拡張」する案は、ダイアログ面積が大きくなることによって端末ウィンドウが隠されてしまうので目指す方向が違うことと、ダイアログリサイズ時の挙動など対処すべき事項が多く、Realtime Mode をオフにすれば求める操作性が得られることから、賛成しかねます。
- 「リストを右クリックした時に選択が外れそう」については、実際には選択が外れないので、予想を裏切る挙動ではあるかもしれないですが、ユーザの不利益にはならないと思います。
- 「HELP ボタンはあったほうが良い」には賛成です。その場合「to Fore」ボタンを削除して上から Submit Close Help とするのが良いと思います。
  - #83 ではボタンが欲しいという文脈でしたが、リストとボタンを行ったり来たりさせる動作は無い方が良いものですし、選択ウィンドウに対する操作が右クリックメニューに集約されているという UI はある意味わかりやすいと思いますし、前面に持ってくる操作だけ右クリックメニューとボタンと二通りの UI を提供するのも過剰と思われますので、to Fore ボタンは無くても大丈夫と思います。

**Comment by zmatsuo** [comment]
ヘルプボタンありがとうございます。@sempreff

> 別案2は動作が変更できるボタン(split button?)でしょうか。
> ただこのボタンはWindowsの標準ボタンなのか、
> どのWindowsからつかえるのかはよくわかりません。

ここの情報によると、
https://learn.microsoft.com/ja-jp/windows/win32/controls/button-types-and-styles
split button(分割ボタン)はVistaからのようです。

XPもだめ?となると候補から外すか、という気持ちです。


色々操作できるようにする、
よく使う操作が1アクションで操作できるようにする
ウィンドウの面積を狭くする
など、盛り込みたいけど相反するので難しいですね。

すこし(1週間程度でしょうか)様子を見て
新アイディアが出てこなかったら
いったんクローズしましょうか。

**Comment by zmatsuo** [comment]
クローズします。

**Comment by sempreff** [comment]
日本語の言語ファイルだけ編集誤りがありました。申し訳ありません。
#286 を出しております。
