### ISSUE TITLE
TeraTerm 5.0: TTL Script fails at 'sendfile'

### ISSUE THREAD

**Issue by Nippey** [TeraTermProject/teraterm#19]
Hello,

[ I wrongly posted this issue to https://github.com/TeraTermProject/osdn-download/issues/33. ]

I just discovered an issue while updating from 4.107 to 5.0:

I have a script that executes:

```
FLASHWRITER_FILE = 'xxxxxxx.mot'
getdir DIR

sprintf2 FILE_NAME '%s\%s' DIR FLASHWRITER_FILE
sendfile FILE_NAME 1
```

I can see that the file is already sent to the device, but still, macro execution is stuck at line 'sendfile FILE_NAME 1'.

Can I provide any additional information to you?
Best Regards!

**Comment by nmaya** [comment]
This snapshot includes fix.
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/48460196

**Comment by Nippey** [comment]
Hello Matsuo-san,
thank you for the fix, I confirm it is working now.
敬具 (Best Regards :) )
