### ISSUE TITLE
接続エラー時のメッセージを修正

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#195]
MSG_COMM_CONNECT_ERROR と MSG_COMM_TIMEOUT_ERROR が逆になっているようです。
[bad_message](https://github.com/TeraTermProject/teraterm/tree/bad_message) ブランチに修正を入れました。

エラーと発生(テスト)方法, 発生メッセージは次の通り。

1. WSAECONNREFUSED
  - MSG_COMM_REFUSE_ERROR
  - sshやtelnetが動作していないポートに接続すると発生

2. WSAENETUNREACH
  - MSG_COMM_REACH_ERROR
  - 接続先に到達できない(途中でエラーが返ってくる)
  - 発生しない?

3. WSAETIMEDOUT
  - MSG_COMM_TIMEOUT_ERROR
  - 応答パケットが返ってこないとき発生

4. default
  - MSG_COMM_CONNECT_ERROR
  - その他

1,3 はテストできるのですが、2がテストできません。
(Windows10で)WSAENETUNREACH を
発生させることはできるでしょうか?

**Comment by nmaya** [comment]
> WSAENETUNREACH を発生させる

イーサネットアダプタを無効にして（出口がない状態で）接続しようとすると出ます。
ホスト名で接続しようとすると名前が引けずに "Invalid host" になりこのエラーのところまで来ないので、IPアドレスで接続しようとする必要があります。

**Comment by zmatsuo** [comment]
> イーサネットアダプタを無効にして（出口がない状態で）接続しようとすると出ます。

私の環境(Windows 10)だと WSAEHOSTUNREACH が発生しました。
OS(winsock?)のバージョンで違うのか
仮想PC関連のアダプタが影響しているからかもしれないですね。


WSAEHOSTUNREACH をしらべると
https://learn.microsoft.com/ja-jp/windows/win32/winsock/windows-sockets-error-codes-2
自分のPCから出ていくアダプタがない時に発生するんですかね。

Tera Term 上では WSAENETUNREACH と同じメッセージにしてよさそうに思います。

**Comment by nmaya** [comment]
> > イーサネットアダプタを無効にして（出口がない状態で）接続しようとすると出ます。

この検証をしたのは Windows 11 です。

> Tera Term 上では WSAENETUNREACH と同じメッセージにしてよさそうに思います。

同じではないですが、WSAEHOSTUNREACH の説明で「WSAENETUNREACH を参照してください」となっているので、メッセージは同じでいいかもしれませんね。
