### ISSUE TITLE
duplicated ウィンドウを切断後、New connection すると SSH Authentication でフォーカスが無い

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#198]
Auto window close をオフの設定にします。
SSH で接続した端末ウィンドウで duplicate session し、
新しく複製されたウィンドウで、exit や kill などでログアウトします。
そのままそのウィンドウで New connection で SSH 接続をすると、
SSH Authentication ウィンドウで、コントロールのフォーカスがどこかに行ってしまいます。
TABキーや、アクセスキー（Alt-R など）でもフォーカスが移動しないようで、マウス操作が必須になってしまいます。

**Comment by zmatsuo** [comment]
連絡いただきありがとうございます。

手もとで再現させることができました。

対策できていると思うので試していただけますか
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49608523/artifacts

**Comment by kattyo-abk** [comment]
ありがとうございます。修正されているようです。

**Comment by zmatsuo** [comment]
確認ありがとうございます。
mainにマージしました。

main(8c3cdd4)のバイナリです。お試しください。
https://ci.appveyor.com/project/teraterm/github-main/builds/49644052/artifacts
クローズします。
