### ISSUE TITLE
teratermproject.github.io が自動更新されない

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#20]
action の[ログ](https://github.com/TeraTermProject/update_website/actions/runs/6749297760/job/18349358571)を見たところ、なにかエラーが出ているようでした。

```
github_io/manual/4/en/macro/howtoassoc.html iso-8859-1
github_io/manual/4/en/macro/howtorun.html iso-8859-1
~/work/update_website/update_website/github_io ~/work/update_website/update_website
fatal: No pathspec was given. Which files should I remove?
[master 5e7dc52] update
 Committer: zmatsuo <runner@fv-az842-289.yhlsagsewx4upp3hyc34bwbk4e.cx.internal.cloudapp.net>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 25 files changed, 310 insertions(+), 382 deletions(-)
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/TeraTermProject/TeraTermProject.github.io.git/'
~/work/update_website/update_website
```

> fatal: No pathspec was given. Which files should I remove?

ここと

> remote: Invalid username or password.

ここが気になります。

-----
push 時に action が走ったみたいなのですが、github.io のコンテンツが最新にならないようです。

_Originally posted by @nmaya in https://github.com/TeraTermProject/teraterm/issues/2#issuecomment-1790784979_

**Comment by zmatsuo** [comment]
tokenが失効していました。更新しました。

**Comment by nmaya** [comment]
ありがとうございます。
ということは、定期的にtokenの更新（re-generate した token をどこかにセットする？こと）が必要ということでしょうか？

**Comment by zmatsuo** [comment]
Personal access tokens (classic) で token を作って
https://github.com/settings/tokens

Actions secrets and variables で
https://github.com/TeraTermProject/update_website/settings/secrets/actions
GIT_REPOSITORY に
https://zmatsuo:ghp_1234567890abcdefghijklmnopqrstuvwxyz@github.com/TeraTermProject/TeraTermProject.github.io.git (例です ghp_12～の部分が生成したtokenです)
とセットしています。
パスワード込みのURLですね。

時々使わないと忘れそうなので、1ヵ月で失効するtokenを使っています。

**Comment by nmaya** [comment]
解説ありがとうございます。
