### ISSUE TITLE
Trojan detected from multiple AV Vendors in Version 5.0 and onward

### ISSUE THREAD

**Issue by Elmeche** [TeraTermProject/teraterm#206]
Dear TeraTermProject Team,

I've run the EXE binaries from the release section against VirusTotal and noticed, that in version 5.0 2 Antivirus Vendors and in version 5.1 & 5.2 3 Antivirus Vendors flag the executable as malicious, while the version 4.107 & 4.108 are benign from all AV vendors. It looks like the AI model of those Vendors apparently are detecting patterns of Trojans and Viruses. This might be most likely false positives from their AI models. But this will still prevent multiple system admins (and Users) from using version 5.0 (including my company).

My recommendation would be to contact these AV vendors and report the files as false positive. Also best would be if you include the check with VirusTotal and the later reporting of false positives in your release cycle,

**Comment by zmatsuo** [comment]
Report sent.
Let's wait and see.

**Comment by graham30rad** [comment]
Virus total is still showing 3 hits..

**Comment by zmatsuo** [comment]
When I enter 5.2 exe URL ( https://github.com/TeraTermProject/teraterm/releases/download/v5.2/teraterm-5.2.exe ) on https://www.virustotal.com/gui/home/url , all clean.

**Comment by zmatsuo** [comment]
I had received E-mail from VirusTotal.

Here's part of the E-mail.

> We understand your concern about new files being flagged as
> potentially harmful. While VirusTotal aggregates data from various
> antivirus engines, we don't make our own judgments about files.

It seems that there is nothing TeraTerm Project Team can do about false positive.
