### ISSUE TITLE
マクロ「setttile」で設定したウィンドウタイトルが、ウィンドウサイズ変更後に username@hostname で上書き変更される

### ISSUE THREAD

**Issue by sawaken2021** [TeraTermProject/teraterm#214]
ttlファイルにてSSH接続ターミナルを起動後、ログイン処理を実施。ログイン完了後に settitle コマンドでウィンドウタイトルを変更しています。

> connect '192.168.0.1:22 /ssh /auth=password /user=username /passwd=xxx'
> settitle 'UniqueWindowTitleName'

このときウィンドウタイトルは以下のように設定されます。
> 192.168.0.1 - UniqueWindowTitleName VT

しかしこの後、**ウィンドウサイズを変更**すると、ウィンドウタイトルが
> 192.168.0.1 - username@hostname: - VT
で上書き設定されてしまいます。

期待する動作は、ウィンドウサイズ変更後もsettitleで設定したウィンドウタイトルが維持されることなのですが、いかがでしょうか？

【動作環境】
TeraTerm：5.2 ※4.92でも確認しましたが再現
OS：Windows 11 ※Windows 10でも確認しましたが再現
マクロファイル：UTF-8

**Comment by zmatsuo** [comment]
リサイズしたときshellが動いていて、
プロンプトでタイトルを設定しているのではないでしょうか。

こんな風にするとどうなりますか?
```
$ echo $SHELL
/bin/bash
$ export PS1="$ "
```

**Comment by sawaken2021** [comment]
@nmaya 
BINGOでした。サーバからタイトル要求が来ており、teratermi.iniの設定を下記のように変更したところ、タイトル変更されずにsettitleマクロで設定したタイトルが維持されることを確認しました。
> AcceptTitleChangeRequest=off

仕様通りの動作でありバグではありませんでした。
@zmatsuo さん含めて迅速なコメントありがとうございました。
