### ISSUE TITLE
5.2 インストーラー インストール完了できない件

### ISSUE THREAD

**Issue by ymn0** [TeraTermProject/teraterm#216]
お世話になっております。

target [teraterm-5.2.exe](https://github.com/TeraTermProject/teraterm/releases/download/v5.2/teraterm-5.2.exe)
OS Windows 10
一般ユーザーでUAC権限昇格（普通にダブルクリックインストール、管理者権限を右クリックなどで指定なし）

事象
このメッセージ以後インストール出来ません
![image](https://github.com/TeraTermProject/teraterm/assets/44623949/6f86b4b3-ba0d-4818-a2c1-d6d22146fe68)

インストーラーの権限と推察されます。

以上の件、よろしくお願いします。

**Comment by zmatsuo** [comment]
"C:/Program Files (x86)/teraterm5" は作成されていますか?

**Comment by ymn0** [comment]
"C:/Program Files (x86)/teraterm5" は作成されていません。

また、4.108でも同一現象起きているようです。こちらは"C:/Program Files (x86)/teraterm" は既に作成されています。(上書きインストール)

**Comment by zmatsuo** [comment]
手もとではうまくインストールできています。
何かの条件で発生するんだと思いますがわからないです。

同様の現象が発生している方がいらっしゃるのかな?
コメントを待ってみましょう。

**Comment by shimarisu** [comment]
再現させる環境はないのですが
Administrator権限なしでは
C:\Program Files(x86)
にディレクトリを作ることはできないのではないでしょうか？

別のソフトウェアの話になりますが、
WinMergeの場合はAdministrator権限のないユーザ用に
ユーザー単位インストーラーというものが別途存在しています。
ユーザー単位インストーラーを用いると
Program Filesではなく%APPDATA%の下にインストールされる模様です。
(Visual Studio CodeにもSystem InstallerとUser Installerがありますね)

以下の情報はTera Termでも役に立つでしょうか？
https://winmergejp.bitbucket.io/#history

> ウィルス誤検知の対応状況
> 64bit版のインストーラは、InnoSetup6.0.xで作成していましたが、71のエンジンのうち、SecureAge APEX, McAfee-GW-Edition の２つで常に警告が発生してしまうため、一時的にInnoSetup5でインストーラを作成するようにします。
> これにより、1つのインストーラでユーザ毎か全ユーザ対象かの選択インストールができなくなったため、
> 別途ユーザ毎インストーラを作成しています。

Tera Termの場合そんなにいくつもインストーラを作っていられない気もします。
(64bit版とか,Arm版とか分けていたらきりがないですし)

ところで、Tera TermのReleaseのところにある。
teraterm-5.2_pdb.zip
とは何でしょうか？

**Comment by zmatsuo** [comment]
> Administrator権限なしでは
> C:\Program Files(x86)
> にディレクトリを作ることはできないのではないでしょうか？

作れないはずです。

> 一般ユーザーでUAC権限昇格（普通にダブルクリックインストール、管理者権限を右クリックなどで指定なし）

とのことなのでインストーラーからフォルダが作れる状態かなと思います。

インストールできないというレポートは他にはないので
何らかの環境によるものだとは思うのですが…。


ウィルス誤検知はインストーラー部分を誤検知している可能性があるんですね。🤔
一時的にアンチウィルスソフトをdisableしてインストールを試していただけないでしょうか? @ymn0 

> ところで、Tera TermのReleaseのところにある。
> teraterm-5.2_pdb.zip
> とは何でしょうか？
ダンプファイルと合わせてデバグに使うものでです。普段はなくて大丈夫です。
https://teratermproject.github.io/manual/5/ja/reference/develop-memo.html#dump

**Comment by shimarisu** [comment]
@zmatsuo 
回答ありがとうございました。

> teraterm-5.2_pdb.zip

はそういうものだったんですね。納得しました。

**Comment by zmatsuo** [comment]
インストーラーのバージョンを調べたところ、
新しいものが使用できそうです。

現時点(2d75b11)のソースをAppVeyorでビルドしたバイナリです。
https://ci.appveyor.com/project/teraterm/github-main/builds/49987685/artifacts

インストーラーのバージョンは[InnoSetup 6.1.2](https://www.appveyor.com/docs/windows-images-software/)です。
もしかすると新しいものに入れ替わっているかもしれないです。


インストーラーのバージョンを最新[InnoSetup 6.3.0](https://jrsoftware.org/isdl.php#stable)にして
手もとでビルドしたものです。dropboxに置きました。
https://www.dropbox.com/scl/fi/8bg08vkxs1eqer5iprgis/teraterm-5.3-dev-20240610_214344-2d75b11bf-snapshot.exe?rlkey=0ciuh3sgxk8k0br56nyjoqnve&st=xwiuing4&dl=0
ソースはAppVeyorのバイナリと同じです。

インストーラー6.3.0を使った後者で
インストールできるか試していただけないでしょうか

**Comment by ymn0** [comment]
@zmatsuo 
回答遅くなり申し訳ございません。
さきほど
https://github.com/TeraTermProject/teraterm/issues/216#issuecomment-2158408280
でご提示いただきましたexeファイルでのインストールを行ったところ成功しました。
(UAC権限昇格もききます)
前者(1つ目)のexeファイル、後者(2つ目)のexeファイルとも同じくの結果でした。

本件お騒がせしました。こちらにて解決、クローズと思われます。

**Comment by zmatsuo** [comment]
連絡ありがとうございます。
InnoSetupのバージョンによらずインストールできるみたいですね。

クローズします。
