### ISSUE TITLE
5.2 basenameマクロで日本語を含むパスを指定した場合に正しく動作しない場合がある

### ISSUE THREAD

**Issue by UmezawaFN** [TeraTermProject/teraterm#217]
4.108で動作していたマクロが5.2で動作しないケースがあったので調べていたところ、
basename コマンドで日本語の後に半角が続くようなパスを入力した場合に、マクロが停止するようでした。

例) test.ttl
---
filenamebox "test" 0
basename resultstr inputstr
messagebox resultstr "result"
---

上記マクロを動作させ、 C:\テスト\1\test.txt を指定すると、messageboxが開かれることなく落ちるようです。
C:\テスト\test.txt や、C:\test\test.txt を指定した場合は動作するようです。

Windows11/Windows10(x64)環境でテストしました。
よろしくお願いいたします。

**Comment by zmatsuo** [comment]
レポートありがとうございます。
手もとで再現しました。
修正します。

**Comment by zmatsuo** [comment]
修正しました。

試してみて下さい。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49865645/artifacts

**Comment by UmezawaFN** [comment]
早速の修正ありがとうございました。
試したところ問題なく動作しました。ありがとうございました。

**Comment by zmatsuo** [comment]
確認ありがとうございます。

mainにマージしました。
次回のリリースに反映されます。

クローズします。
