### ISSUE TITLE
ターミナル上は1つしか表示されていないが、ログで二重に出力されている(コマンドをペースト時)

### ISSUE THREAD

**Issue by itaku0141** [TeraTermProject/teraterm#220]
Linuxに対してTeraterm5でSSH接続し、コマンドを実行していました。
ターミナルの画面ではコマンドは常に１つしか見えず、問題ないように見えたのですがログを確認すると同じコマンドが一行に2つ表示されていました。
設定のローカルエコーはチェックしていません。
ログの設定はタイムスタンプとプレーンテキストを有効にしていました。
Teratermのバージョンは5.00です

**Comment by zmatsuo** [comment]
Tera Term 5.00 で再現しました。

手もとの最近のビルドでは発生しませんでした。
https://ci.appveyor.com/project/teraterm/github-main/builds/49865624/artifacts
試してみてください。

**Comment by itaku0141** [comment]
ありがとうございます。
bugfixなどで5.00より新しいバージョンで改善されている旨の記載がなかったためアップデートしていませんでした。

アップデートしたいと思います。

**Comment by zmatsuo** [comment]
[改版履歴](https://teratermproject.github.io/manual/5/ja/about/history.html) の変更の「ブラケットペーストの動作を[BracketedSupport](https://teratermproject.github.io/manual/5/ja/setup/teraterm-misc.html#BracketedSupport) と [BracketedControlOnly](https://teratermproject.github.io/manual/5/ja/setup/teraterm-misc.html#BracketedControlOnly) で調整できるようにした。」
というのが修正です。

8c3cdd47522e0c70b28ecee51a5e80c6fd445059 です。

履歴に「この修正でペーストしたときの文字が二重にログに出力されなくなった」と
追加しておくと今後もわかりやすいですね。

修正については #82 の説明が詳しいです。

マニュアルの「vim からの制御シーケンスの使用例」の[クリップボードからの貼り付け時に自動インデントを無効にする](https://teratermproject.github.io/manual/5/ja/usage/tips/vim.html#Bracketed)
のところにブラケットペーストの説明があります。

用語集にブラケットペーストの説明を置いて、
設定、vim からの..、[対応制御シーケンス](https://teratermproject.github.io/manual/5/ja/about/ctrlseq.html)からリンクを張るのがよさそうですね。

**Comment by zmatsuo** [comment]
修正しました。
改版履歴に追記しました。
https://ci.appveyor.com/project/teraterm/github-main/builds/49921236/artifacts
クローズします。
