### ISSUE TITLE
セッション複製時にログが自動で開始されない

### ISSUE THREAD

**Issue by shoya-ihara** [TeraTermProject/teraterm#221]
# 実行環境
OS：Windows 11
Teraterm バージョン： v5.2 (Git 176aed267)

# 発生事象
「自動的にログ採取を開始する」がon、
ログファイル名を `&h_%Y%m%d_%H%M%S.log` で設定している状態で
「セッションの複製」を行った際に、
複製されたウィンドウのログが開始されないです。

# 再現手順
1. 「設定」－「その他の設定」－「ログ」で「標準ログファイル名」を`&h_%Y%m%d_%H%M%S.log`に、「自動的にログ採取 を開始する」をonに設定し、設定の保存を行う。
1. 適当なホストに接続する。
1. Alt+dを押し、セッションを複製する
1. 新たに開かれたTera Termではログが開始されていない。

# 補足事項
以下のURLの発生事象と似ていました。  
同じ原因かどうかはわかっていないです。
https://osdn.net/projects/ttssh2/ticket/44707

追加で必要な情報などありましたらご質問ください。  
どうぞよろしくお願いします。

**Comment by zmatsuo** [comment]
ありがとうございます。

#157 ログ出力開始に失敗した場合ダイアログが表示される修正が入っています。

最近のスナップショットを試していただけますか
https://ci.appveyor.com/project/teraterm/github-main/builds/49865624/artifacts

**Comment by shoya-ihara** [comment]
@zmatsuo 
返信有り難うございます。
提供いただいたスナップショットで起動したところ、
以下のようなエラーのダイアログが表示されたことで、
私の端末の「設定」－「その他の設定」－「ログ」で「標準のログ保存先フォルダ」の設定が
誤っている（存在しないディレクトリを設定している）ことに気づきました。  
![image](https://github.com/TeraTermProject/teraterm/assets/38233581/b2bf563e-251a-4396-bac6-159996634073)

設定を変更したら期待していた挙動となったので、  
こちらのIssueはcloseとさせていただきます。  

対応ありがとうございました。
