### ISSUE TITLE
Ver5 で、 入力していない配列番号を参照すると落ちる

### ISSUE THREAD

**Issue by edamamebutasann** [TeraTermProject/teraterm#223]
;!*** CASE 1 ****************************************************
＞strdim shresult_detail 100
＞shresult_detail[50] = 'dummy'
＞messagebox shresult_detail[50] 50
設定しているのでOK

;!*** CASE 2 ****************************************************
＞strdim shresult_detail 100
＞messagebox shresult_detail[60] 60
入力していないと　エラーにならず　落ちる

Ver4では　そのまま空白を表示したまま続行した。
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
配列宣言をし、値を入力していないものを参照すると落ちる

（一部説明不足を追記）

;!--- test.ttl ----------------------------------------------------------------------------------
getver ttlver
sprintf 'TeraTermVersion = %s' ttlver
strdim shresult_detail 100
shresult_detail[50] = 'dummy'
messagebox inputstr shresult_detail[50]        ;!*** OK ***
messagebox inputstr shresult_detail[60]        ;!*** 何も表示せず落ちる。
;!--- test.ttl ----------------------------------------------------------------------------------

**Comment by zmatsuo** [comment]
報告ありがとうございます。

文字列配列型の変数は[strdim](https://teratermproject.github.io/manual/5/ja/macro/command/strdim.html) で
宣言しておかないと使えないはずです。

```
;strdim shresult_detail 51
shresult_detail[50] = 'dummy'
messagebox shresult_detail[50] 50
```

strdim で指定した範囲外の要素も使えません。

```
strdim shresult_detail 51
shresult_detail[60] = 'dummy'
messagebox shresult_detail[60] 60
```

確認いただけないでしょうか

**Comment by edamamebutasann** [comment]
表記が説明不足だったので追記しました。

宣言は十分な範囲で設定済みです（例では０～１００）
配列の [50] に値を入力して、messagebox　を表示すれば、普通に表示される。
しかし、値を入力していない、例えば 配列の [60] を　messagebox で表示すると、　落ちる。
という事です。
説明が下手で申し訳ありません。

**Comment by nmaya** [comment]
現象を確認しました。

```
strdim ar_str 10
ar_str[0] = '0'

messagebox ar_str[0] 'set ar_str[0]'
messagebox ar_str[1] 'unset ar_str[1]'
```

**Comment by edamamebutasann** [comment]
ご確認、ありがとうございます。よろしくお願いいたします。

**Comment by zmatsuo** [comment]
解説ありがとうございます。
修正しました。(ee68453beb7062794bc38e1dce08ecda4ed27a6e)

次のURLにバイナリができる予定です。試してみてください。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49943962/artifacts

[strdim](https://teratermproject.github.io/manual/5/ja/macro/command/strdim.html) で作成した文字列配列型変数の未設定の要素を読みだそうとすると
ttpmacro.exe が異常終了していました。

文字列配列変数の全要素の初期値は "" になっていないといけなくて、
一度も文字列を代入していない(=未設定)ときに参照すると、"" が返ってくるのが正しい動作ですね。

**Comment by edamamebutasann** [comment]
解決しました。ありがとうございました。

**Comment by zmatsuo** [comment]
main にマージしました。この修正は次のリリースに反映されます。

バイナリは次のURLに生成される予定です。
https://ci.appveyor.com/project/teraterm/github-main/builds/49952250/artifacts

ありがとうございました。

**Comment by zmatsuo** [comment]
クローズします。
