### ISSUE TITLE
Does Tera Term work on ARM-based Windows?

### ISSUE THREAD

**Issue by shimarisu** [TeraTermProject/teraterm#227]
Micfosoft の serfaceシリーズのように、 CPU に snapdragon(ARM-base)を搭載したマシンが増えてきています。
これらのマシンで Tera Term(x86 32bit)は実際に動作可能でしょうか？

**Comment by nmaya** [comment]
Apple Silicon の Mac 上の Paralles 上の Arm 版 Windows 10 で起動したことがあります。
https://x.com/maya_shack/status/1381239166176923648

**Comment by shimarisu** [comment]
有益な情報ありがとうございます。ARM版のPCを買ってみたい気持ちが高まりました。

**Comment by zmatsuo** [comment]
ARM64ビルドを試してみました。
調整すれば Native な実行ファイルをビルドできそうな印象でした。

**Comment by shimarisu** [comment]
ARM６４ベース(Snapdragon X Elite)の
PC (Lenovo Yoga Slim 7x Gen 9)
を買ってしまいました。
Tera Term 5.2 普通に動いてます。
