### ISSUE TITLE
リリース間隔について

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#23]
Tera Term 4 では「3か月に1回」というリリース頻度が決まっていました。
> 定期リリースは 3 ヶ月に一回、2月/5月/8月/11月の末に出ます。

Tera Term 5 ではリリース頻度が決まっていません。
「半年に１回」（2月/8月）でどうでしょうか。

### TODO
- [x] [wiki:決定事項](https://github.com/TeraTermProject/teraterm/wiki/Decision)を更新
- [x] about/qanda.html を更新

**Comment by zmatsuo** [comment]
よいと思います。
なんだか忙しいので減らしましょう。
大きい不具合が見つかったら随時リリースで。

**Comment by nmaya** [comment]
ありがとうございます。ドキュメント類を更新したら close します。
