### ISSUE TITLE
CreateProcess() に実行ファイルのフルパスを渡す

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#232]
次のページを参考にしました。
- https://jvn.jp/jp/JVN13113728/
- https://win2k.org/blog/2024/03/26/post-15280/
 
CreateProcess() にはフルパスを渡さないと危険とのこと。

ログを見るのに notepad.exe の起動等に使っていたと思います。

ShellExecute() も使い方をチェックしたほうがよさそうです。

**Comment by zmatsuo** [comment]
引き数指定の設定を追加しようと思います。
こんな感じです。
- ログ表示用エディタ
  - 実行ファイル
  - 引き数

利用するのは、例えば
`emacsclient -n`
`C:\Program Files (x86)\sakura\sakura.exe -CODE=4`
などの場合です

オプション(起動引数)のセパレータがスペースなことと、
実行ファイルのフルパスにスペースが含まれている場合があることが
2つの指定が必要になってしまう理由です。

[CreateProcess](https://learn.microsoft.com/ja-jp/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa)の説明に出てくる
`c:\program.exe` -> `c:\program files\sub.exe` を見ていると
フルパスで指定するようにしたのに残念な動作になってしまいます。

実行ファイル名をダブルクオーテーションで囲むと
引き数を付けたときにうまく起動できなくなりそうです。

Visual Studio の ツール - 外部ツール が
コマンドと引き数の2つ指定できるようになっているのは
こんな理由があるのかなと思います。

Tera Term もブラウザの起動はブラウザの[ファイル名と引き数の2つを指定できます](https://teratermproject.github.io/manual/5/ja/setup/teraterm-misc.html#ClickableUrlBrowser)。
  (ブラウザは通常未指定で、URLに関連付けられたプログラムが自動で起動します。)

ご意見を頂けないでしょうか。

特になにもなければ引き数を指定できるようにします。

**Comment by nmaya** [comment]
[CWE-427](https://cwe.mitre.org/data/definitions/427.html)は、「プログラムが相対パス名で EXE/DLL を呼び出す場合、想定より優先順の高いディレクトリに同名の実行ファイルを置くことでそのファイルを実行させる」というものです。DLL hijacking とか DLL preloading で検索すると、特に新しい問題ではないことが分かります。

> 6c4113a

この修正は、相対パスなら FOLDERID_Windows を使ってフルパスにしています。Windowsフォルダにしてしまうということは、「デフォルトの notepad.exe 以外は相対パスで指定されることはない」という前提に見えますが、そういう意図ですか？

たとえば、teartermと同じ（や近い）ディレクトリに適当なエディタを放り込んで相対パスで指定することができなくなります。（例: ..\gp108u\GreenPad.exe など）
また 6c4113a の考え方では Windows 以外の PATH が通ったところにあるプログラム（たとえば ClickableUrlBrowser の起動部分を修正しようとしても、[クリッカブル URL で起動するブラウザ](https://teratermproject.github.io/manual/5/ja/setup/teraterm-misc.html#ClickableUrlBrowser)の例にある `firefox` のように指定されたプログラム）を起動できません。

Tera Term の場合、そして実行ファイルの場合、なにを防いだら安全になるのでしょうか。

どこまで対応するかだと思いますが、「デフォルトの値に対してはこちらで対応する」「自分で指定した場合は自己責任」という考えでしたら、今の修正で理屈が通るかもしれません。
良いかどうかわかりませんが、たとえばViewlogEditorの変換を「"notepad.exe" の時だけ」（INI のデフォルト値は "notepad.exe" なので、ここまでは対応の範囲内とする）とすれば、上記の理屈内で少しだけ柔軟になるかもしれません。

ところで、少し話がそれますが（別のissueにすべきかもしれません）、私の環境では「インストール先のTERATERM.INI」のViewlogEditorのnotepad.exeはインストーラによってフルパス「C:\Windows\notepad.exe」になっているのですが、「Roaming\teraterm5のTERATERM.INI」のViewlogEditorは「notepad.exe」になっています。うちだけでしょうか？

> 引き数指定の設定を追加しようと思います。

これはよいのではないかと思います。

**Comment by zmatsuo** [comment]
[JVN#13113728](https://jvn.jp/jp/JVN13113728/) を見て
とにかくフルパスにする方針がよい、相対パスよくないと理解していました。
(今は相対パスでもよくて、$PATH検索もokではという考えです)

> 「デフォルトの notepad.exe 以外は相対パスで指定されることはない」という前提に見えますが、そういう意図ですか？

相対パスのときは、付けることでパスの指定が誤ることになっても
"c:\windows\"を付けておこうとしていました。

相対のままでで注意が必要そうなのはこんなところでしょうか。

- exeと同一フォルダ、$PATH上の実行ファイルが参照される。どれが起動するかはユーザーが管理する。
- $PATHが書き換えられて、想定外のプログラムが動作することになる

拡張子に割り振られたプログラムを起動する(ShellExecute()を使う)ようにするのもよいのかな思います。

今まで通りでパス("c:\windows\")の追加を行わない、
気になるときはユーザーがフルパスで書く、
分かっているユーザーは相対でok、で良いように思います。
マニュアルに「フルパスでないときは、exeのあるフォルダ、$pathのフォルダの実行ファイルが使用される…」とあればよさそうです。

ViewlogEditorが未設定(空白)のとき ShellExecute() を使用
設定してあると CreateProcess() がよさそう。

ViewlogEditor のデフォルト値が notepad.exe なのが
ユーザーが意図せず相対パスになってしまっているところですね。
もし相対パスの時は「ほんとに起動してよいか」ダイアログを出すのはどうでしょう

解凍レンジがどういう対策を取れば『「解凍レンジ」 Ver 1.41の使用中止を検討してください』
という状態にならなかったのだろう?と考えてしまいます。

> 私の環境では「インストール先のTERATERM.INI」のViewlogEditorのnotepad.exeはインストーラによってフルパス「C:\Windows\notepad.exe」になっているのですが、「Roaming\teraterm5のTERATERM.INI」のViewlogEditorは「notepad.exe」になっています。うちだけでしょうか？

調べますね。

**Comment by zmatsuo** [comment]
> 私の環境では「インストール先のTERATERM.INI」のViewlogEditorのnotepad.exeはインストーラによってフルパス「C:\Windows\notepad.exe」になっているのですが、「Roaming\teraterm5のTERATERM.INI」のViewlogEditorは「notepad.exe」になっています。うちだけでしょうか？

インストーラを使ってインストールしたTera Termでは「C:\Windows\notepad.exe」になっていました。

初めての起動がポータブル版で、「notepad.exe」となったのかも?

**Comment by zmatsuo** [comment]
修正しました。

これ以外は入れ込みました。

> iniファイル読み込み時 ViewlogEditor が "notepad.exe" のとき "c:\windows\notepad.exe" とする


> 初めての起動がポータブル版で、「notepad.exe」となったのかも?

初めてではなくて、
ポータブル版をテストしてい portable.ini を消して実行して
notepad.exe になったというほうがありそうです。

https://ci.appveyor.com/project/teraterm/github-main/builds/50073269/artifacts

**Comment by nmaya** [comment]
> ポータブル版をテストしてい portable.ini を消して実行して
notepad.exe になったというほうがありそうです。

いったんアンインストールして確認しました。そのようでした。失礼しました。

**Comment by nmaya** [comment]
> ViewlogEditorの指定がなければ
ShellExecute("open", [logファイル])

昔はなかった気がしますが、最近の Windows だと log 拡張子のファイルに対する関連付けがあるでしょうか。

**Comment by zmatsuo** [comment]
ファイルの拡張子にlogとして、
logのデフォルトアプリがないときは
「このファイルを開く方法を選んでください」
ダイアログが出てプログラムを選択、
「常にこのアプリで開く」にチェックを入れておくと
次回からは自動で選択したプログラムが開くという動作になります。

エクスプローラーでファイルをダブルクリックしたときの
動作と同じだと思います。

テストしたのはWindows10です。
OSのバージョンによって異なるかもしれませんが
概ねこのような動作になると思います。

**Comment by zmatsuo** [comment]
CreateProcess() は大丈夫そうです。[ShellExecute()](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew) も見ています。

teraterm/setupdirdlg.cpp の中で
```
ShellExecuteW(NULL, L"open", L"explorer.exe", dir, NULL, SW_NORMAL);
```
"explorer.exe" を実行するという指定方法で ShellExecuteW() を使用しています。
実行ファイルは相対パスです。

ShellExecuteW()の説明には相対パスのとき
$PATHが検索に使われるとか、フォルダ `c:\windows\` を探すとか書いていません。
どこの実行ファイルが使用されるのかよくわかりません。

とりあえずフルパスにして "C:\windows\explorer.exe" とするのが安全でしょうか?
意見いただけないでしょうか

**Comment by nmaya** [comment]
> ShellExecuteW(NULL, L"open", L"explorer.exe", dir, NULL, SW_NORMAL);

ttermpro.exe と同じディレクトリにある explorer.exe が起動されました。
これは 6c4113a82d0c5cc89401b228d0d46dac8e4b1b50 のように FOLDERID_Windows を使ったほうがいいかもしれませんね。

**Comment by zmatsuo** [comment]
ShellExecute() + "explorer.exe" の箇所を修正しました。
#232 ブランチ(15ac0369e2adf320878050b8bdae3cf1f9870587)です。

よさそうです。

**Comment by zmatsuo** [comment]
もしかすると、ShellExecuteW() の "explore" + フォルダ は最近のWindowsしか使えないかも?
とも考えたのですが、CreateProcess() (WinExec()?)と変わらなくなってしまうし
問題が見つかったら "open" + "explorer.exe" + フォルダ に戻そうと思います。

mainにマージしました。クローズします。
