### ISSUE TITLE
TeraTermウインドウを基準とした位置にポップアップを出力する方法はありませんか？

### ISSUE THREAD

**Issue by edamamebutasann** [TeraTermProject/teraterm#234]
画面に整列した、複数のTeraTermのウインドウで、個々のマクロがポップアップを出しても
どれがどのポップアップなのか全然わからないので、

ポップアップ（messagebox 等）を出力する方法に画面基準ではなく、
自分のウインドウ基準でポップアップを出力する方法はありませんか？(setdlgpos)

getdlgpos みたいにして現在のウインドウの位置を得るコマンドもあるといいですね。

**Comment by hkanou** [comment]
>getdlgpos みたいにして現在のウインドウの位置を得るコマンドもあるといいですね。

Tera Termウィンドウの位置の取得は修正箇所が小さく実装し易そうですので、getdlgposのようなコマンドの追加を試みてみます。

**Comment by hkanou** [comment]
> getdlgpos みたいにして現在のウインドウの位置を得るコマンドもあるといいですね。

VT window のテキスト領域の位置やサイズを取得する getttpos コマンド追加のPRを出させて頂きました。https://github.com/TeraTermProject/teraterm/pull/269
~~~
getttpos <x> <y> <width> <height> <minimized>

  Tera TermのVT windowの下記の値を取得します。(単位:ピクセル)

  <x>         テキスト領域左上隅の X 座標
  <y>         テキスト領域左上隅の Y 座標
  <width>     テキスト領域の幅
  <height>    テキスト領域の高さ
  <minimized> VT windowの最小化状態(0:通常状態、1:最小化状態)

  ※ VT windowが最小化されている場合は、<x> <y> <width> <height>には誤った値が設定されます。
~~~

>画面に整列した、複数のTeraTermのウインドウで、個々のマクロがポップアップを出しても
どれがどのポップアップなのか全然わからないので、
ポップアップ（messagebox 等）を出力する方法に画面基準ではなく、
自分のウインドウ基準でポップアップを出力する方法はありませんか？(setdlgpos)

getttposで取得したx,yをsetdlgposのx,yで指定するとテキスト領域左上隅にダイアログが表示されます。
~~~
  testlink
  if result > 1 then
  :start
    getttpos x y width height minimized
    if minimized = 1 then
      showtt 1
      goto start
    endif
    setdlgpos x y
    sprintf2 str 'x=%d, y=%d, width=%d, height=%d' x y width height
    messagebox str 'x,y = top-left of the text area'
  endif
~~~

**Comment by edamamebutasann** [comment]
ありがとうございます。実際にキッティングなどを複数ウインドウで実行している場合にとても役立ちます。

**Comment by hkanou** [comment]
>ありがとうございます。実際にキッティングなどを複数ウインドウで実行している場合にとても役立ちます。

返信ありがとうございます。
評価用のexeファイルを[こちら](https://github.com/hkanou/ttpmacro/tree/main/ttpmacro4/Release)に配置しました。
動作環境は[Tera Term 5.2 dev 609f1b96](https://ci.appveyor.com/project/teraterm/github-main/builds/50251240/artifacts)以降になります。

<ご参考>
実装時に考えたことは以下になります。
きちんとした対応は未のため、今回のPRは見送りや仕様変更の可能性があります。
(ちゃんとした対応は大変そうで腰が引けてます ;-)

### getttpos
- コマンド名(1)
  Tera TermのVT window以外のウィンドウやダイアログ(TEK window等)を取得する場合に困らないか？  
  → 取得情報が増えた場合は、getttposの引数を増やすことで対応する。
- コマンド名(2)
  VT windowの位置以外の情報(サイズ、最小化状態)を取得しているのにget positionなのか？  
  → setdlgposと対で使う想定、連想しやすいようコマンド名はsetdlgposと揃えておく。
- コマンドの対称性
  setdlgpos、getttpos はあるが getdlgpos、setttpos がない。  
  → ニーズがあれば検討する。
- 取得するX,Y座標
  VT windowの左上隅の座標と、VT windowのテキスト領域の左上隅の座標のどちらを取得するか？  
  → VT windowの左上隅の座標はタイトルバーを含むため、取得したX,Y座標をsetdlgposに渡すととウィンドウのタイトルが読めなくなる。  
  → 取得したX,Y座標をそのままsetdlgposに渡せるよう、テキスト領域の左上隅の座標を取得する。

### setdlgpos
>ポップアップ（messagebox 等）を出力する方法に画面基準ではなく、
自分のウインドウ基準でポップアップを出力する方法はありませんか？(setdlgpos)

- オプション追加
  - 原点の指定
    ディスプレイとTera TermのVT windowのどちらを原点にするかを指定するオプションが必要。
    マルチモニタ環境向けに、カレントディスプレイの左上隅を原点にする指定があると便利。
  - 表示位置の指定
    下記の指定ができると良い。(MACROのダイアログのサイズを計算してテキスト領域をはみ出さないよう表示)
    - 左上隅
    - 右上隅
    - 左下隅
    - 右下隅
    - 中央
  - 表示位置の調整
    指定した表示位置(左上隅や右上隅)からのオフセットを(X,Y)で指定できると良い。

### 位置指定の改善点
- 現在はTera Termが出力するダイアログの位置の制御は行っていない。
- showコマンドで表示されるMACROダイアログ、dirnamebox、filenameboxは、setdlgposで表示位置を指定出来ない。(現在の仕様)

**Comment by zmatsuo** [comment]
history.html の雰囲気を合わせるとこんな感じはどうでしょうか
それとtypoを見つけました。

[234_0806.patch](https://github.com/user-attachments/files/16512151/234_0806.patch)

htmlファイルの改行コードはCRLFです。
Windows由来のツールだかからそうなっていると思うのですが、
別の改行コードでもchmファイルできているっぽいですね。
ソースツリーのトップの .editorconfig を使えば自動的にcrlfになります。

最大化も取れるようにするのはどうでしょうか?
`IsZoomed(HVTWin)` で取得はできるはずです。
でも、最大化していることがわかって何かに便利に使えるか?が分からないです。


> 現在はTera Termが出力するダイアログの位置の制御は行っていない。

ディスプレイが広く、Tera Term が重ならずに複数表示できているとき、
メッセージウィンドウ(MessageBox()のウィンドウ)が
ディスプレイの中央に出るのはなんだかいまいちだと思っていました。

TTMessageBoxW() に入れ込めればいい感じにできそな気配はあります。
TaskDialogIndirect() がVista以降なのと、
もうそろそろコードフリーズを考えないといけないところが
悩ましいです。

こんな風にすれば実現できそうです。
- [How to Change MessageBox Position in C++](https://stackoverflow.com/questions/55150622/how-to-change-messagebox-position-in-c#55151073)
- [オーナーウィンドウの中央にメッセージボックスを表示する - C#](https://www.ipentec.com/document/csharp-show-message-box-in-center-of-owner-window)

**Comment by hkanou** [comment]
>history.html の雰囲気を合わせるとこんな感じはどうでしょうか
それとtypoを見つけました。
[234_0806.patch](https://github.com/user-attachments/files/16512151/234_0806.patch)

ありがとうございます、頂いたパッチ取り込ませて頂きます。

>htmlファイルの改行コードはCRLFです。
ソースツリーのトップの .editorconfig を使えば自動的にcrlfになります。

失礼いたしました、VScode使ってみます。

>最大化も取れるようにするのはどうでしょうか?
IsZoomed(HVTWin) で取得はできるはずです。

はい、最大化と非表示 IsWindowVisible(HVTWin) も取得するようにいたします。

>setdlgpos、getttpos はあるが getdlgpos、setttpos がない。
>→ 取得したX,Y座標をそのままsetdlgposに渡せるよう、テキスト領域の左上隅の座標を取得する。

setttposを実装する際、テキスト領域ではなくウィンドウ領域の座標を使用するため、
getttposは、ウィンドウ領域とテキスト領域の両方の情報を取得すべきでした。
→ 9個の引数を使用することになります。

>Tera TermのVT window以外のウィンドウやダイアログ(TEK window等)を取得する場合に困らないか？
→ 取得情報が増えた場合は、getttposの引数を増やすことで対応する。

かなり多くの引数を使用することになります。
引数を整数型配列にすれば数は少なくなりますが可読性は低下します。
→ 取得情報が増えた場合は、追加分を整数型配列にする方向で考えようと思います。

>>現在はTera Termが出力するダイアログの位置の制御は行っていない。

>TTMessageBoxW() に入れ込めればいい感じにできそな気配はあります。
TaskDialogIndirect() がVista以降なのと、
もうそろそろコードフリーズを考えないといけないところが
悩ましいです。

なるほど、TTMessageBoxW() に入れれば良かったのですね。
[How to Change MessageBox Position in C++](https://stackoverflow.com/questions/55150622/how-to-change-messagebox-position-in-c#55151073) の"// Using SetWinEventHook() ..."の方法だとTaskDialogIndirect() を使わなくて済みそうです。
MessageBoxを直接呼んでいる箇所もありますが、概ねカバーできる見込みです。

**Comment by zmatsuo** [comment]
> VScode使ってみます。

たいていのエディタが対応していると思います。


MessageBox、いい感じにウィンドウを中央に出ています。
よてもよさそうです。


MessageBoxを出す位置は、かなりインパクトがある修正になるので
設定でディスプレイの中央(デフォルト)/ウィンドウ(VTWin)の中央を
選べるのがよさそうに思えてきました。
いかがでしょうか?

__declspec(thread) は Vistaより前で使えないのと([wikipediaのスレッド局所記憶 / プログラミング言語固有の実装 / C/C++](https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89%E5%B1%80%E6%89%80%E8%A8%98%E6%86%B6#C/C++)のところの「Vista～～」という箇所参照)
Windows 9x, XPではもう絶対無理と思われるので、
できれば使わずに実現できれば。
(リリースバイナリは9x, XPで動きません。できればという希望です)
OSを見て動作を切り替えるか。
ちょっと考えます。

**Comment by hkanou** [comment]
>>VScode使ってみます。

>たいていのエディタが対応していると思います。


勉強します。

> MessageBox、いい感じにウィンドウの中央に出ています。

ありがとうございます、zmatsuoさんのおかげです。


>MessageBoxのメッセージの位置は、かなりインパクトがある修正になるので
設定でディスプレイの中央(デフォルト)/ウィンドウ(VTWin)の中央を
選べるのがよさそうに思えてきました。
いかがでしょうか?

はい、有効/無効を選択できるようにする案に賛成です。
修正試みてみます。

>__declspec(thread) は Vistaより前で使えないのと([wikipediaのスレッド局所記憶 / プログラミング言語固有の実装 / C/C++](https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89%E5%B1%80%E6%89%80%E8%A8%98%E6%86%B6#C/C++)のところの「Vista～～」という箇所参照)
Windows 9x, XPではもう絶対無理と思われるので、
できれば使わずに実現できれば。
(リリースバイナリは9x, XPで動きません。できればという希望です)

TlsAlloc他(TLS API)への変更を検討いたします。

**Comment by hkanou** [comment]
[MessageBoxPosParentRelativeオプションを追加、__declspec(thread)を使用しないよう修正](https://github.com/hkanou/teratermproject_teraterm/commit/1bb0738d92a2dbcfaa4b1fe59ef3f659921eb763) 
MessageBoxのメッセージの位置を指定するオプションを追加してみました。
```
[Tera Term]
MessageBoxPosParentRelative=on
```
[Tera Term]セクションの設定ですが、ttssh他にも効果がある共通設定としています。
項目名はVTPos,TEKPos,SaveVTWinPosを参考にしましたが、良い名前がありましたら変更したいと思っています。

>__declspec(thread) は Vistaより前で使えない...

SetWinEventHookのCALLBACK関数の引数からHWINEVENTHOOKを取得できましたので、スレッド固有変数は不要でした。
不要なご心配をおかけし申し訳ありませんでした。

その他：ttxcheckupdateの参照先のURLがOSDNでjson形式のため、別途見直すのが良さそうです。
(https://osdn.dl.osdn.net/storage/g/t/tt/ttssh2/snapshot/teraterm_version.json)

**Comment by hkanou** [comment]
>libressl が VS2005 でビルドできないと思われるので、
ttxssh に加えて ttpmenu, ttpmacro も
VS2005でビルドできない=Win95用staticCRTのバイナリが作れなくなりました。
TLS使っていないので ttermpro.exe はビルドできそう。
MinGWでshared CRTのバイナリなら全て作れるはずです。

MinGWの環境は未作成... 道のりは遠いです。

>tttypes.h の struct tttset の新しいメンバーは最後に追加しています。
修正案を作りました。参照ください @hkanou

ありがとうございます、修正案まで作成頂き申し訳ありません。
tttypes.h他の修正と併せて、頂いた情報を開発メモに加筆させて頂きました。

MessageBoxPosParentRelative対応で修正したドキュメントを見直しました。
・teraterm-ini.html : MessageBoxPosParentRelativeだけ説明過多だったのを修正
・teraterm-misc.html : "スクリーン"を"ディスプレイ"に変更

>遠い未来では、プラグインから struct tttset を
参照する必要がなくなればいいなと思っています。

>ttxcheckupdate はバイナリの最新をチェックするためのプラグインです。
AppVeyer(GitHub)でビルドしたらプラグインで更新バイナリをチェックできる、
自動更新に近いことができようにしたいな、という野望を持っています😀

😊

**Comment by hkanou** [comment]
>MinGWでshared CRTのバイナリなら全て作れるはずです。

[build_with_cmake.mdのコードブロックが\<pre\>\<code\>に変換されるよう修正した。](https://github.com/hkanou/teratermproject_teraterm/commit/d6a0fb349658e7a5afc196dadd8561b5b3aed07a) 
ヘルプページ「cmakeを使ったビルド方法」の改行処理の修正になります。

**Comment by zmatsuo** [comment]
修正ありがとうございます。

d6a0fb3 ブロックが崩れていましたね。

`<br>`、`<br />` どちらでも良いけど `<br>` のほうが良い感じなんですね。

mainにマージしました。

クローズします。
検討することなどあれば、再オープンしてください。

**Comment by nmaya** [comment]
「setdlgpos で指定する座標を VTWindow（のある位置）からの相対にしたい」の話から、絶対座標で setdlgpos に渡すために「マクロから VTWindow の位置情報を得るためのマクロコマンド」のissue だと思っていました。

> ディスプレイが広く、Tera Term が重ならずに複数表示できているとき、
メッセージウィンドウ(MessageBox()のウィンドウ)が
ディスプレイの中央に出るのはなんだかいまいちだと思っていました。

いつのまにか Tera Term (TTSSH) が表示するメッセージボックスを VTWindow の中央？にしたい、という話になっていますか？
issue のタイトルと内容がかけ離れているので気づくのに時間がかかりました。

Win32 API の MessageBox を呼び出したら、呼び出すたびに表示位置が少しずつ右下にずれていってまた戻る（Windows がやってくれる）ので、この動作を普通の動きと感じます。
端的に言うと、通常の Windows アプリとは違う変な（今までの Tera Term ユーザを含む、Windows の動作になれている人が戸惑う）動きをしないでほしいです。
この機能に限らず、一部のユーザがだけがメリットを感じる新機能は、組み込むならオプションで選べるようにしたうえでデフォルトはoffにしてほしいです。

**Comment by nmaya** [comment]
MessageBox の位置について、"File" - "Disconnect" で実際に動作を確認しました。

4.102 は、VT ウィンドウの中央に表示されました。
4.103 は、VT ウィンドウがいるディスプレイの中央に表示されました。

> MessageBoxのメッセージの位置は、かなりインパクトがある修正になる

が、すでに行われていたことになります。

> ウィンドウの中央に出る MessageBox

は、以前の動作に戻すことになります。（よいと思います）

**Comment by hkanou** [comment]
> MessageBox の位置について、"File" - "Disconnect" で実際に動作を確認しました。

ありがとうございます。

>4.102 は、VT ウィンドウの中央に表示されました。
>4.103 は、VT ウィンドウがいるディスプレイの中央に表示されました。

大変なお手数をおかけし、申し訳ありません。
VT ウィンドウの中央に表示されるのが当初の設計の旨承知いたしました。
4.102がどのような実装だったか確認したいと思います。(5.3に間に合うと良いのですが...)

>ウィンドウの中央に出る MessageBox
は、以前の動作に戻すことになります。（よいと思います）

MessageBoxPosParentRelative オプションのデフォルト値を off ではなく on とするPRを準備いたします。
off = VT ウィンドウがいるディスプレイの中央に表示する
on  = VT ウィンドウの中央に表示する

**Comment by zmatsuo** [comment]
4.103の高DPI対応がきっかけだと思います。
直接はMFCの使用をやめたことが原因です。

MFCではダイアログ系は親ウィンドウの中央に表示されます。

裏とっていないですが、
CWnd::MessageBox() や AfxMessageBox() も
デフォルトで親ウィンドウの中央に表示されるはずです。
(ディスプレイの中央に出す方法がないかもしれないです)

現在のTera Term (4.103から)は、
MFCを使わずに(CreateDialogIndirectParamW() などのWin32API を使って)
表示しているので、設定などのダイアログは、
Tera Term のコードで中央に移動しています。

Win32API の MessageBox() はディスプレイの中央に表示されます。
引数変更などで親ウィンドウの中央に表示することはできません。

>> MessageBoxのメッセージの位置は、かなりインパクトがある修正になる
> が、すでに行われていたことになります。

行われていました。

中央に出たら便利なのにな、と思い始めたのはごく最近で、
4.103の時は気づいていませんでした。

このissueを見たとき、 MessageBox() を
ディスプレイの中央ではなく親ウィンドウの中央に出せればなと
調べたところ @hkanou さんに実装いただき感激していました。

> いつのまにか Tera Term (TTSSH) が表示するメッセージボックスを VTWindow の中央？にしたい、という話になっていますか？

してしまっていました。失礼しました。
このままこのissueで・・。

こう思い返すと MessageBox() の表示位置が変わったことは
それほど気に留められていない、インパクトない感じなのかな・・。

**Comment by nmaya** [comment]
> > いつのまにか Tera Term (TTSSH) が表示するメッセージボックスを VTWindow の中央？にしたい、という話になっていますか？

> してしまっていました。失礼しました。

今後は気を配っていただけると助かります。

> こう思い返すと MessageBox() の表示位置が変わったことは
> それほど気に留められていない、インパクトない感じなのかな・・。

そうかもしれませんが、インパクトを正確に図るのは難しいと思います。

何か変わって改悪されたと思ったときのユーザのリアクションは、「黙って使わなくなる」「不便だと思いつつ黙って使う」「SNSなどで愚痴る」「開発者に言いに来る」のパターンがあると思います。
最後ぐらいしか開発者には見えないものだと思います。

**Comment by nmaya** [comment]
> 直接はMFCの使用をやめたことが原因です。
> MFCではダイアログ系は親ウィンドウの中央に表示されます。

タイミング的にもそうだと思いました。

> MessageBoxPosParentRelative

このフラグをなくして常時onにし、変更履歴を「4.103より前の動作に戻した」（「4.103でのエンバグ」と言うにはバグっぽくないため）にするのはいかがでしょうか？

**Comment by hkanou** [comment]
>>4.102がどのような実装だったか確認したいと思います。(5.3に間に合うと良いのですが...)

>Win32API の MessageBox() はディスプレイの中央に表示されます。
引数変更などで親ウィンドウの中央に表示することはできません。

親ウィンドウの中央に表示する実装を参考にしたいという思いでしたが、本実装(#234)で良さそうな旨確認させて頂くことができました。経緯までを教えて頂き大変ありがとうございます。

>>MessageBoxPosParentRelative

>このフラグをなくして常時onにし、変更履歴を「4.103より前の動作に戻した」（「4.103でのエンバグ」と言うにはバグっぽくないため）にするのはいかがでしょうか？

おっしゃるとおり、4.103でWin32APIの標準動作に合わせた形でバグではない理解です。
設計としてはon/offの選択ができるのが良いのですが、メンテナー観点では不要な処理は追加すべきではない。だと思われます。
親ウィンドウの中央に表示するのが当初の設計であれば、フラグは無くても良いかなと思い始めました。
現状、TTMessageBox()ではなく直接MessageBox()を呼んでいる箇所は、ディスプレイの中央にダイアログが表示されます。
変更履歴は「4.103より前の動作に戻した(一部を除く)」のような記載になると思われます。

**Comment by hkanou** [comment]
3204a9e で MessageBoxPosParentRelative オプションの削除を行わせて頂きました。

**Comment by hkanou** [comment]
マージ頂き大変ありがとうございます。

**Comment by nmaya** [comment]
> [3204a9e](https://github.com/TeraTermProject/teraterm/commit/3204a9e8ecad91136b5a3f78c0ee18be55639bbc) で MessageBoxPosParentRelative オプションの削除を行わせて頂きました。

せっかく動作の切り替えを書いていただきましたが、ご対応ありがとうございます。

**Comment by zmatsuo** [comment]
クローズします。
