### ISSUE TITLE
Issue with ‘strdim’ Function in Tera Term 5.2

### ISSUE THREAD

**Issue by qstso** [TeraTermProject/teraterm#235]
Dear Tera Term Developer,

I encountered a problem when using Tera Term 5.2 and would like to seek your help and advice.

It seems that the function “strdim” will not automatically assign a default value for all strings inside the array. To be more specific, without manually assigning any value to each of the individual strings in the array, when trying to access any string by using the String operation commands, “ttpmacro.exe” will hang and crash.

For example, if I run the following simple code by using Tera Term 5.2:

*********************************
strdim tmp_array 10
messagebox tmp_array[0] tmp_array[0]
messagebox 'complete' 'complete'
*********************************

“ttpmacro.exe” will hang for a few seconds and then terminate when it tries to execute the second line of code. The third line of code (message box that shows complete) will not be executed.

If I run the same code in Tera Term 4 (e.g.: Tera Term 4.98), the code can be executed without any issue.

Could you please kindly help to check and advise? Thank you very much for your help.

**Comment by nmaya** [comment]
Thank you for your report.

This issue is duplicate with #223, it is already fixed int main and will included in next release.

Thanks,
