### ISSUE TITLE
installer/release/lang_utf8/Spanish.lng has a typo (Cofiguration -> Configuration)

### ISSUE THREAD

**Issue by EntityMike** [TeraTermProject/teraterm#239]
Hello!

I installed Teraterm 5.2, and saw "TeraTerm Menu" so I installed that and was messing with it. In the tray icon on the bottom right, when you click "List Configuration", it brings up a window that I'm assuming lets you save configurations for TeraTerm windows. The title of that window has a typo - "List Cofiguration" should be "List Configuration". When I searched the source I only found it in the file **installer/release/lang_utf8/Spanish.lng** which I thought was weird because I installed it in English. Maybe the English one was fixed but the Spanish one was not? Anyways, I was going to make a branch and put in a PR but I don't have permissions so I wanted to at least create an issue for this quick fix. :)

![TeraTerm_typo](https://github.com/TeraTermProject/teraterm/assets/45380635/c1e7f1f8-a56e-45ef-a613-96a1a4f6836a)

**Comment by hkanou** [comment]
As you pointed out, there was a typo in the "TeraTerm Menu".
The following two places need to be corrected.

- installer/release/lang_utf8/Spanish.lng : DLG_CONFIG_TITLE=List Cofiguration
- ttpmenu/ttpmenu.rc : CAPTION "List Cofiguration"

Thank you for pointing it out.

**Comment by nmaya** [comment]
Hi,

Thank you for your report.
This fix is committed to main. And it will be included in next release.

Thank you.

**Comment by EntityMike** [comment]
Hello! Awesome! I'm glad that I could help :)
