### ISSUE TITLE
'sendln'で入力した文字列がウィンドウの折り返し部分で改行扱いとなってしまう。

### ISSUE THREAD

**Issue by Grus50** [TeraTermProject/teraterm#24]
主題の件について、4.106から5.0に移行したところ事象が発生したため
仕様動作であるかご確認させてください。
以下、主な事象となります。

・'sendln'で入力した文字列のみウィンドウで折り返された際に改行扱いとなってしまう。
・出力されたログはウィンドウ折り返し部分から改行されており、マクロの後続処理についても改行扱いで処理が行われる。
・他のコマンド実行結果等は折り返し部分で改行されていない。

回避方法等ございましたらご教示頂けますと幸いです。
何卒よろしくお願いいたします。

### TODO
- [x] 修正
- [x] 変更履歴
- [x] mainへのマージ

**Comment by zmatsuo** [comment]
テストを書いてみました。
```
str = "echo 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
sendln str
```
sshdへ接続、bashが動作している状態になって、マクロを実行しました。
1行はウィンドウ幅より長かったのですが、echoは1行として扱われて実行されました。
echoの出力はウィンドウ端で折り返された部分で改行扱いになりませんでした。
選択するとクリップボードには改行なしで入りました。

再現方法を教えていただけないでしょうか

**Comment by Grus50** [comment]
お待たせしております。
以下、再現用のコードとなります。

```bash
; ウィンドウサイズ調整(80x25)
dispstr #$1b"[8;25;80t"
; ログ設定
LOG_PATH = 'C:\test.log'
logopen LOG_PATH 0 1 0 1 1
; 再現用文字列送信処理
sendln ''
wait '$'
sendln 'echo 123456789123456789123456789123456789123456789123456789123456789123456789123456789'
recvln
recvln
wait '$'
; ウィンドウ折り返し地点で改行されている事の確認
ECHO_RESULT = inputstr
messagebox ECHO_RESULT 'info'
; ログ出力終了
logclose
```

・4.106
 -> messageboxの出力はechoのコマンド結果「123〜」が表示され、ログ出力も改行されていない。

・5.0
 -> messageboxの出力はechoのコマンド結果ではなく、sendlnで投入したコマンドが折り返し部分で改行された「345〜」の出力。ログ出力も同じ箇所で改行されている。

お手数ですが、ご確認の程よろしくお願いいたします。

**Comment by zmatsuo** [comment]
ありがとうございます。
調査します。

**Comment by zmatsuo** [comment]
手を入れました。

接続先(サーバー)からの改行(0x0d(CR)+0x0a(LF))が送られてきたとき、
改行(0x0d(CR)+0x0a(LF))としてログとマクロにデータを送ります。

接続先から0x0a(LF)のみが送られてきたとき、
改行(0x0d(CR)+0x0a(LF))としてログとマクロに送っていましたが、
Tera Term 4と同じように捨てるよう修正しました。

テストで使用していた環境では
(Debian OpenSSH_9.2p1 Debian-2, OpenSSL 3.0.9 30 May 2023)
コマンドを投入(enterを押して)してから
コマンドがstdoutに出力してくるまでに
0x0dが出力されていました。

この修正で動作を見ていただけないでしょうか。
https://ci.appveyor.com/project/teraterm/github-snapshot/build/artifacts
(ビルドしています)

**Comment by zmatsuo** [comment]
発生している現象と違うなと考えていました。
もしかするとtmuxなど端末多重接続ソフトをお使いでしょうか?

**Comment by Grus50** [comment]
ご対応頂き、誠にありがとうございます。
明日、動作確認させて頂きます。

取り急ぎご回答となりますが、端末多重接続ソフトは使用せずに利用しております。

**Comment by Grus50** [comment]
本日修正版にて動作確認したところ、v4.106と同様の動作となりました事をご報告させて頂きます。
お忙しいところ、ご対応頂き感謝申し上げます。

本修正につきまして、今後のリリースにて反映される見込みはございますでしょうか、、、？
rejectの場合、マクロ側で対策検討いたしますので差し支えなければご教示頂けますと幸いです。

**Comment by nmaya** [comment]
この修正は5.1へ適用予定です。

**Comment by Grus50** [comment]
ありがとうございます。本件クローズさせて頂きます。
