### ISSUE TITLE
5.2 Left click backgrounded terminal window makes text selection 1 char sensitively

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#244]
5.2 では、バックグラウンドにある teraterm ウィンドウを左クリックで選択して前面化したときに、
カーソルの勢いがあると、容易に1キャラクタ選択されてしまいます。
同じスピードでもフォアグラウンド状態では、ほぼ選択されません。
5.1 以前ではそのように敏感ではありません。
（最近あまりにコピペミスが増えたので並べて比較しました。）

**Comment by nmaya** [comment]
判定位置（ドラッグ開始→どこを超えたら選択と判定されるか）は変更されました [#116](https://github.com/TeraTermProject/teraterm/issues/116#issuecomment-1936225053) が、バックグラウンド時の選択の判定も変化したでしょうか？>@zmatsuo

**Comment by zmatsuo** [comment]
ウィンドウをアクティブにする時の動作は変化してないと思います。

文字の選択判定は
e91f4dc 2024/02/09 で動作が変化しました。
5.1 が従来通り、
5.2 が変更後の動作になります。

左ボタンを押して選択する時の動作は、

### 5.1

- 文字の左半分にポインタあるとき
  - 前方(左)にポインタが移動すると
    - 左の文字の左半分にポインタが到達すると
      - 左ボタンを押したときの左の文字が選択される
  - 後方(右)にポインタが移動すると
    - 右の文字の右半分にポインタが到達すると
      - 左ボタンを押したときの右の文字が選択される
- 文字の右半分にポインタあるとき
  - 前方(左)にポインタが移動すると
    - この文字の右半分にポインタが到達すると
      - この文字(左ボタンを押したときの文字)が選択される
  - 後方(右)にポインタが移動すると
    - 右の文字の右半分にポインタが到達すると
      - この文字(左ボタンを押したときの右の文字)が選択される

### 5.2

- 文字の左半分にポインタあるとき
  - 前方(左)にポインタが移動すると
    - 左の文字にポインタが到達すると
      - 左ボタンを押したときの左の文字が選択される
  - 後方(右)にポインタが移動すると
    - 右の文字にポインタが到達すると
      - 左ボタンを押したときの文字が選択される
- 文字の右半分にポインタあるとき
  - 前方(左)にポインタが移動すると
    - 少しでもポインタが動くと
      - 左ボタンを押したときの文字が選択される
  - 後方(右)にポインタが移動すると
    - 少しでもポインタが動くと
      - 左ボタンを押したときの文字が選択される

↑ちょっとわかりにくいです…

変更前(5.1)の動作は全般文字の半分のところを考慮している感じです。
でも、5.2も特に違和感ないんじゃないかなと思います。
選択するまでの移動距離が5.2のほうが全般短くなったので、

> 左クリックで選択して前面化したときに、
> カーソルの勢いがあると、容易に1キャラクタ選択されてしまいます。

が発生しそうです。

次の設定がどうなっているか見てもらえないでしょうか @kattyo-abk 

- [マウスでウィンドウ選択時の文字選択を有効にする](https://teratermproject.github.io/manual/5/ja/menu/setup-additional.html#SelectOnActivate)
- [Enabling text selection when the window is activated by mouse](https://teratermproject.github.io/manual/5/en/menu/setup-additional.html#SelectOnActivate)

> マニュアルは
> Disabling text selection when the window is activated
> となっていますね。要修正かな

こんな議論を見つけました。興味深いです。
[非アクティブなウィンドウがクリックされた時のガイドライン?](https://atmarkit.itmedia.co.jp/bbs/phpBB/viewtopic.php?topic=21432&forum=7)

バックグラウンド(=非アクティブ,Zオーダーが後ろ)のウィンドウを
前面に移動(=アクティブに)する時どんなオペレーションをするか
人それぞれ、場合によっていろいろですね。
1. ALT + TAB (WindowsKey + TAB)
2. タスクバーで選択(クリック)
3. タイトルバー等をクリック
4. クライアント領域をクリック (このとき文字の誤選択しやすい)

マウスでウィンドウ選択時の文字選択を有効にする=OFFで使っていたのと、
1か2でアクティブにすることが多いので
気にならなかったようです。

**Comment by nmaya** [comment]
私はウィンドウ選択時にコントロールを触ったら「触ったもの」として扱われる（参照先で言うIEの動作）のが不服/こわいので、Windows 全般の使い方として1か3の（事故らないように安全側に振った）操作をしています。
そのため、マウスでウィンドウ選択時の文字選択を有効にする=onになっていましたが、私もこの変化に気づきませんでした。offにすれば解決しそうに見えますね。

**Comment by kattyo-abk** [comment]
Enabling text selection when the window is activated by mouse はオンでした。
しばらくオフにして生活してみます。

**Comment by kattyo-abk** [comment]
しばらく前述オプションオフで使いましたが、特に問題なかったです。
バックグラウンド・ウィンドウから直接テキスト選択をしたい時以外（今回のようにウィンドウを前面にする時）は
オプションはオフとして生活するのがよさそうです。

**Comment by zmatsuo** [comment]
設定変更で解決できてよかったです。

Windows の設定に、
ウィンドウ上にマウスポインタを移動させると
自動的にウィンドウがアクティブ(&最前面)になる設定があります。

同時に動作しているアプリケーションのウィンドウを
ほとんど重なることなく表示する使い方のとき便利そうです。
最近ディスプレイ(デスクトップ)が広い環境もありますよね。

Windowsでは、
ウィンドウがアクティブになることと
ウィンドウが最前面に来ることは
同時に起こると考えることが多いと思います。

X Windows では別なことも多いです。
(たしかtwm…ではそうできた…)

こんな情報を見つけました。
[Windows11でウィンドウフォーカスの設定を変更](https://note.com/clockwork_bird/n/n16f0cbff4b59)

マウスポインターがあるウィンドウをアクティブにするけど、
最前面に来ない(Zオーダーをそのままにする)ようにできます。
お試しください。

(CTRL押下状態でポインタを移動したときは最前面にする、とかもできればいいなぁ…)

マニュアルの修正ができたらクローズします。

**Comment by zmatsuo** [comment]
マニュアル修正しました。
クローズします。

レジストリの変更をためしてみました。
アクティブだけど最前面ではない状態で、
文字を上をクリックすると
アクティブな状態なので設定にかかわらず選択されてしまいますね。
もうひと工夫必要かもしれません。

**Comment by zmatsuo** [comment]
修正したのでクローズします。
