### ISSUE TITLE
add:ttpmenuのログインパスワードの暗号化機能追加

### ISSUE THREAD

**Issue by hkanou** [TeraTermProject/teraterm#246]
ttpmenuのログインパスワードの暗号化機能追加を提案させて頂きます。

>https://github.com/TeraTermProject/teraterm/issues/213#issuecomment-2156643481
ttpmenu内のパスワードエンコード/デコード
起動時にパスワード入れないと使えないオプションがあっても(あるほうが)よさそう。

## 概要

* ttpmenuのログインパスワードの暗号化/復号対応

## 修正理由

* 現状
  ttpmenuに入力されたパスワードはエンコードされ、レジストリ又はiniファイルに保存されます。
  保存されたパスワードをデコードすることで、第三者がパスワードを知ることができます。
* 修正後
  レジストリ又はiniファイルに保存されるパスワードをAES-256-CTR(共通鍵)で暗号化し、第三者がパスワードを知ることが出来ないようにします。
  ログインパスワードを暗号化/復号する機能をLockBoxと呼びます。

## 修正内容
* 画面イメージ
  https://github.com/hkanou/ttpmacro/tree/main?tab=readme-ov-file#ttpmenu
* 実行ファイル
  https://github.com/hkanou/ttpmacro/raw/main/ttpmenu1/Release/ttpmenu_mod.exe
* List Confiturationダイアログ
  ログインパスワードを暗号化して保存できるよう、下記のコントロールを追加します。
  * チェックボックス "use LockBox"
    OFFの場合は、ログインパスワードはエンコードされて保存されます。(現状どおり)
    ONの場合は、ログインパスワードはLockBoxで設定したパスワードを用いて暗号化されます。
  * プッシュボタン "LockBox"
    LockBoxを押すとパスワード入力ダイアログが表示されます。

  リストボックスで登録済ホストを選択した場合のふるまい:
  * 登録済ホストがLockBoxを使用する設定でLockBoxのパスワードが未入力又は誤りがある場合は、パスワード入力ダイアログが表示されます。
    LockBoxのパスワードでログインパスワードを復号できなかった場合は、パスワードは""(空文字)で表示されます。

* 自動ログイン(ポップアップメニュー内の「Execute」)
  ログイン対象ホストがLockBoxを使用する設定で、LockBoxのパスワードでログインパスワードを復号できなかった場合は、パスワード入力ダイアログが表示されます。
  パスワード入力ダイアログでCancelボタンが押された場合は、対象ホストに接続後Tera Termでパスワード入力待ちになります。

* その他
  * ttpmenu/registry.cpp : RegSetBinary()
    レジストリ又はiniファイルにホスト情報を書き込むと、Password=XXXの末尾のスペースが、保存される度に1文字づつ増えていく不具合を修正します。
  * ttpmenu/ttpmenu.cpp : ManageWMCommand_Config()
    詳細設定(Details)ダイアログで実行ファイル名に"ttermpro.exe"か含まれていると"use SSH"のチェックボックスがONになる処理を廃止します。(telnet使用時、想定外の挙動となるため)
  * installer/makelang.bat
    マウイ語の変換が漏れていたので下記を追加します
    perl utf8_to.pl cp65001 release/lang_utf8/Tamil.lng release/lang/Tamil.lng

## 修正時に迷ったこと
  * 機能名を何にするか？
    ログインパスワードやSSHのKeyfileとの混同が無く、利用者にわかりやすい名称としてLockBoxにしています。
  * List ConfiturationダイアログへのLockBoxの追加
    LockBoxはログイン対象ホスト毎に設定するものではないため、"Password"の下に"use LockBox"、"LockBox"があるのはおかしい？
    → ユーザやグループ単位にLockBoxのパスワードを付与するケースも考えられるため、ログインパスワードの下に追加しています。
  * LockBoxのパスワード入力ダイアログのタイトル
    Tera Term lauch toolとTeraTerm Menuのどちらの名称を使用すべきか？
    → どちらの名称でもわかるよう併記しています。
  * langファイル
    機械翻訳ですが、各言語向けに翻訳しています。

**Comment by nmaya** [comment]
> LockBoxはログイン対象ホスト毎に設定するものではない

INIファイルでもホストごとに「LockBoxFlag=1」と保存されていますし、接続時にも設定したホストではパスワードを聞かれ、そうでないホストではパスワードを聞かれません。
Configuration=ログイン対象ホストごとに設定する機能に見えますが、違うのですか？

> 機能名

アプリケーション起動のときに1つのパスワードを入力するものであれば、「マスターパスワード」と言われる機能だと思います。
ログイン対象ホスト毎に設定していて、「ログインパスワードをパスワードで保護」ということになりますよね？
短くていい名前が思いつきません。

> 機械翻訳

使っている機械翻訳は、出力のライセンスがどうなると言っていますか？
ライセンスが明示されていない場合、私はそれをライセンスがない（利用の許可がない）ものとみなします。
- https://github.com/TeraTermProject/teraterm/wiki/Document-rule
- https://qiita.com/Tatamo/items/ae7bf4878abcf0584291
- https://togetter.com/li/1084225

> Tera Term lauch tool

これは About ダイアログにある文字列ですか？
"TeraTerm Menu" としか読んだことがないのでこちらでよいと思います。
また"Tera Term lauch tool" は名前の一部ではなく説明（「日本語ワープロソフト 一太郎」の「日本語ワープロソフト」の部分）のように思います。

**Comment by hkanou** [comment]
>>LockBoxはログイン対象ホスト毎に設定するものではない
>
>INIファイルでもホストごとに「LockBoxFlag=1」と保存されていますし、接続時にも設定したホストではパスワードを聞かれ、そうでないホストではパスワードを聞かれません。
Configuration=ログイン対象ホストごとに設定する機能に見えますが、違うのですか？

「マスターパスワード」のイメージが強く混乱してしまいました。
おっしゃるとおり、ログイン対象ホストごとに設定する機能ですので"Password"と同じ扱いで良かったですね。

>>機能名
>
>アプリケーション起動のときに1つのパスワードを入力するものであれば、「マスターパスワード」と言われる機能だと思います。
ログイン対象ホスト毎に設定する「ログインパスワードを保存するときに保護（暗号化）するパスワード」ということになりますよね？
短くていい名前が思いつきません。

はい、「ログインパスワードを保存するときに保護（暗号化）するパスワード」になります。
名称は悩みましたが、tipsで説明すれば伝わるのではということでLockBoxにしています。

>>機械翻訳
>
>使っている機械翻訳は、出力のライセンスがどうなると言っていますか？
ライセンスが明示されていない場合、私はそれをライセンスがない（利用の許可がない）ものとみなします。

ご指摘いただきありがとうございます。
権利関係の考慮が漏れておりました、見直しいたします。

>>Tera Term lauch tool
>
>これは About ダイアログにある文字列ですか？
"TeraTerm Menu" としか読んだことがないのでこちらでよいと思います。
また"Tera Term lauch tool" は名前の一部ではなく説明（「日本語ワープロソフト 一太郎」の「日本語ワープロソフト」の部分）のように思います。

Tera Term lauch toolは、About ダイアログとreadme.txtにあった文字列です。
lauch toolは説明部分である旨腹落ちしました。"Tera Term Menu"に修正いたします。

**Comment by hkanou** [comment]
もう一つ確認頂きたい箇所がありました。
https://github.com/TeraTermProject/teraterm/issues/128#issuecomment-1962384908 の"パスワードなどが漏れる可能性があることをマニュアルに追記"対応で下記を加筆しています。
この記載で良いか見ていただけないでしょうか...

doc/ja/html/usage/TTMenu/TTMenu.html
>1. Tera Term Menuとは

NOTE: 管理者権限を持つユーザはProcess Explorerなどのツールを用いてTeraTerm Menuから起動されたTera Termのユーザ名、パスワードなどの引数を表示させることが可能です。
情報漏洩のリスクがある環境では、TeraTerm Menuの利用をお控えください。
>2. レジストリ

レジストリ、iniファイルにはユーザ名、パスワードなどが保存されていますので取り扱いには注意してください。

**Comment by nmaya** [comment]
> パスワードなどが漏れる可能性があることをマニュアルに追記

ありがとうございます。よいと思います。

**Comment by hkanou** [comment]
[fix document](https://github.com/TeraTermProject/teraterm/commit/5e3ff689684584dae87b72373458f9c09417b5de) https://github.com/TeraTermProject/teraterm/issues/246
衍字並びに修正漏れを直して頂きありがとうございます。

[メッセージの見直し](https://github.com/hkanou/teratermproject_teraterm/commit/413e2d2ad30d352140d822a95ac61e0775f20c37) https://github.com/TeraTermProject/teraterm/issues/246
> 機械翻訳
使っている機械翻訳は、出力のライセンスがどうなると言っていますか？
ライセンスが明示されていない場合、私はそれをライセンスがない（利用の許可がない）ものとみなします。

langファイル他、メッセージを見直しました。

> "TeraTerm Menu" としか読んだことがないのでこちらでよいと思います。

ダイアログのタイトルを"TeraTerm Menu"に修正致しました。

**Comment by hkanou** [comment]
富士通の対話型生成AI(Fujitsu Research Portal)につきまして、問い合わせの回答を頂きましたので共有させて頂きます。

1. 富士通の対話型生成AI

   トップページ  https://portal.research.global.fujitsu.com/
   対話型生成AI  https://documents.research.global.fujitsu.com/chat-gen-ai/
   利用規約      https://portal.research.global.fujitsu.com/tou-list
                 -> https://portal.research.global.fujitsu.com/content/terms-of-use-2024060701.pdf
                 -> https://fjresearchportal.blob.core.windows.net/azureadb2c/static/cga/tou.html

2. 問い合わせ結果

   問い合わせ先: FJ-AI-Innovation-PF <fj-AI-Innovation-PF@dl.jp.fujitsu.com>
   (問い合わせ先内容によっては、別MLへの再問合せが必要になるとのことです)
   前提: APIは使用せずチャットインターフェース(Web)により翻訳を行う
   問い合わせ結果：

   Q1. 翻訳結果のテキストが誰に帰属するか教えて下さい。
   A.  利用者（入力者）に帰属します。
       詳細は各生成AIエンジンの利用規約をご参照ください。

   Q2. 翻訳結果の複製、改変、再頒布が許可されているか教えて下さい。
   Q3. 翻訳結果の利用上の指定等がありましたら教えて下さい。(例 powered by XXX の表示が必要)
   A . 翻訳結果は利用者帰属なので、Q2,3に関する制約などはありません。

   Q4. 翻訳結果を自由に使用して良いでしょうか？
   A.  各利用規約の禁止事項で定められている用途（悪用、権利侵害など）でなければ、自由に使用できます。
       https://portal.research.global.fujitsu.com/content/terms-of-use-2024060701.pdf
       https://fjresearchportal.blob.core.windows.net/azureadb2c/static/cga/tou.html

   Q5. 対話型生成AIの出力結果に関して、ライセンス関係の情報をFAQまたは利用規約に加筆頂けないでしょうか？
   A.  ご指摘ありがとうございます。内部で検討してまいります。

   Q5. 本問い合わせのご回答を公開しても良いでしょうか？
   A.  OSSコミュニティへの公開とのことなので、問題ありません。

以下、私の主観/印象になります。

   1. 対話型生成AI
      https://documents.research.global.fujitsu.com/chat-gen-ai/
      - 幻覚（ハルシネーション）検出機能
        もっともらしい誤りの誤りらしさを数値で出してくれます。
        回答の理由自体は自分で判断しなければいけないのですが、根拠がわかるのが秀逸です。
      - 応答
        知らないことは知らないと言う素直なAI。
        話を逸らしたりしないので、調べものに良いです。
   2. 富士通サポート
      - 問い合わせ後、3営業日で回答を頂けました。
        権利関係は時間がかかると思っていましたが、想定以上に回答が早かったです。
      - OSSに対して好意的にご対応頂きました。
        今回、Tera Termの翻訳で利用したい旨お伝えしましたので、問い合わせ時はその旨連絡頂くと話が速いかもしれません。
   3. その他
      - 対話型生成AI以外もいろいろな機能があり面白そうです。
        https://portal.research.global.fujitsu.com/tou-lis

**Comment by zmatsuo** [comment]
> fix document #246
> 衍字並びに修正漏れを直して頂きありがとうございます。

手もとでマージをテストして、内容を見たりしていました。
途中で眠くなって自分のリポジトリにpushするつもりが
github.com/TeraTermProject/teraterm にpushしていました。
失礼しました。

修正提案をpushして見てもらうのも便利ですね。

不要なコードを見つけました。見てもらえないでしょうか。 @hkanou 
#246_ttpmenu_merge ブランチです。

**Comment by hkanou** [comment]
>手もとでマージをテストして、内容を見たりしていました。
修正提案をpushして見てもらうのも便利ですね。

ありがとうございます。

>不要なコードを見つけました。見てもらえないでしょうか。 @hkanou
#246_ttpmenu_merge ブランチです。

不要なコードでした、ご指摘頂きありがとうございます。
DlgCallBack_LockBox()も同様、不要部分を削除正致しました。
また、LockBoxのパスワード入力ダイアログのメッセージが右に寄っていたので、中央に表示されるよう修正致しました。

**Comment by hkanou** [comment]
マージ頂きまして、大変ありがとうございます。
お陰様で魔改造と呼ばれなくて済みそうです。
いつもありがとうございます。

**Comment by zmatsuo** [comment]
マージしたソースをビルドしています。
https://ci.appveyor.com/project/teraterm/github-main/builds/50251164/artifacts

多分問題なくビルドできると思います。

プロジェクトは(実は私がです) GitHub を使うこと、
PRを受け入れるということに慣れていないので
改善などアドバイスいただければ嬉しいです #178

> お陰様で魔改造と呼ばれなくて済みそうです。

😃

**Comment by hkanou** [comment]
>マージしたあと少し直しました。
https://github.com/TeraTermProject/teraterm/commit/609f1b962d2f643d5ca8f0c6e40e49615897af42 をビルドしました。

ありがとうございます。
ローカル環境の設定のままでした、お手数をおかけいたしました。

>プロジェクトは(実は私がです) GitHub を使うこと、
PRを受け入れるということに慣れていないので
改善などアドバイスいただければ嬉しいです https://github.com/TeraTermProject/teraterm/issues/178

こちらこそGitHubに不慣れでご迷惑をおかけしていないか心配です。
私は素人ですが、何か気づきがありましたらお伝えさせて頂きます。

> https://ci.appveyor.com/project/teraterm/github-main/builds/50251240/artifacts

改めて確認いたしました。
優先度は低そうですが、一旦共有させて頂きます(備忘)

1. ttpmenuの名称
スペース有無の表記ゆれ"Tera Term Menu"、"TeraTerm Menu"がありました。
[使用方法の記載](https://teratermproject.github.io/manual/5/ja/usage/TTMenu/TTMenu.html)は"Tera Term Menu"、[ソースや更新履歴等](https://teratermproject.github.io/manual/5/ja/about/copyright.html#license_ttmenu)は"TeraTerm Menu"です。
(私見)"Tera Term"本体ではないことを伝えるため、"TeraTerm Menu"に寄せているかもと思いました。https://github.com/TeraTermProject/teraterm/blob/609f1b962d2f643d5ca8f0c6e40e49615897af42/doc/en/html/reference/sourcecode.html#L242

2. installer/release/ttmenu_readme-j.txt
[ttmenu_readme-j.txt](https://github.com/TeraTermProject/teraterm/blob/609f1b962d2f643d5ca8f0c6e40e49615897af42/installer/release/ttmenu_readme-j.txt) はv0.94r2用でした(最新版に更新しても良いかもしれません)

3. English.lng
\lang\English.lngは有りませんが、\lang_utf16le\English.lngは有ります。
installer/makearchive.bat
https://github.com/TeraTermProject/teraterm/blob/609f1b962d2f643d5ca8f0c6e40e49615897af42/installer/makearchive.bat#L87
del /f %dst%\lang_utf16le\English.lng を追加すると揃いそうです。

4. installer/teraterm.iss
https://github.com/TeraTermProject/teraterm/blob/609f1b962d2f643d5ca8f0c6e40e49615897af42/installer/teraterm.iss#L102
101行目の後ろに下記を追加しても良いように思われました。
Source: release\lang\Tamil.lng; DestDir: {app}\lang; Components: TeraTerm; Attribs: readonly; Flags: uninsremovereadonly overwritereadonly

5. テーマファイル
https://github.com/TeraTermProject/teraterm/tree/main/installer/release/theme
新しい書式([BG Theme]他)に更新しても良いように思われました。

**Comment by zmatsuo** [comment]
ありがとうございます。
すぐに答えられそうなところから

1. ttpmenu

名前は TeraTerm Menu が正式でok…と決めましょうか。


2. installer/release/ttmenu_readme-j.txt

ttpmenu/readme.txt が正で、
installer/release/ttmenu_readme-j.txt がコピーだと(だった)思います。
ttmenu_readme-j.txt は保守されていないですね。

ソースツリーから削除して、
リリースを作るときに、正からコピーするようにしたほうがよさそうです。


3. English.lng

English.lng は、デフォルトと同じになるから削除されているのかな?
あってもよさそうに思います。


4. installer/teraterm.iss

lang\ の lngファイルは Windows(9x) 向けで、
Unicode ini ファイル読み込みができないため別に分けています。
[参考](https://teratermproject.github.io/manual/5/ja/reference/dev/win32api.html)

Tera Termは、9xをサポートするコンパイラでビルドすれば、
9xで動作するつもりではあります。
(環境を準備するのはMinGWが一番簡単です。最近テストしていません。)

リリースのTera Termは、9xで動作しないexeとなるので、
lang\ フォルダは不要といは不要ですね。

タミル(Unicode)をサポートした9xがあるのか、
あるならテストできるのか分からないです。


5. テーマファイル

テーマは後回しになっています。

--

issueにするのかな?という内容とか
雑多な話題などを扱うのにMLを使えるようにしたい、
と準備しようとしたのですが挫折中です。
- https://github.com/TeraTermProject/osdn-download/issues/14

あまり使われてないですがチャットもあります。
- https://github.com/TeraTermProject/teraterm/wiki/Discord

**Comment by zmatsuo** [comment]
> 名前は TeraTerm Menu が正式でok…と決めましょうか。

ここも調整が必要ですね。
https://teratermproject.github.io/manual/5/ja/usage/TTMenu/TTMenu.html

> 雑多な話題などを扱うのにMLを使えるようにしたい、

ML準備中です。

**Comment by hkanou** [comment]
>名前は TeraTerm Menu が正式でok…と決めましょうか。


承知いたしました。

>ここも調整が必要ですね。
https://teratermproject.github.io/manual/5/ja/usage/TTMenu/TTMenu.html

>https://github.com/TeraTermProject/teraterm/issues/261 を作りました。

ありがとうございます、
#261でPRを出せるよう準備いたします。

> 雑多な話題などを扱うのにMLを使えるようにしたい、

Discordも使わせて頂きます。

**Comment by zmatsuo** [comment]
> > #261 を作りました。
>
> ありがとうございます、
> #261でPRを出せるよう準備いたします。

#261 修正中です。
もうすぐpushできると思います。 @hkanou 

自分に assign しておきますね。

**Comment by hkanou** [comment]
クローズさせて頂きます。
ありがとうございました。
