### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by DelWoodcock** [TeraTermProject/teraterm#25]
When starting it always goes into COM mode, is there a way to start it with the New connection dialog box opening up for TCP/IP connections? I looked at all the settings but could not find anything on this.

**Comment by nmaya** [comment]
If `Port=serial` in TERATERM.INI, Tera Term behaves so.
Save TERATERM.INI while connecting serial port, Tera Term saves `Port=serial`.
