### ISSUE TITLE
QR codes not shown in a usable fashion

### ISSUE THREAD

**Issue by Donner-Party** [TeraTermProject/teraterm#251]
When using Teraterm to set up PiVPN, it does not display QR codes properly, no matter what font I have tried.

It does display properly in Windows 11 ssh client.

Can this be fixed or is there a specific font I should be using?

Example of PiVPN QR code: https://it.giffen.cloud/2020/04/05/setup-pivpn-endpoint-device/

**Comment by zmatsuo** [comment]
Hi

[same issue?](https://www.reddit.com/r/pivpn/comments/glo4dc/qr_code_not_showing_properly/?rdt=53367)

Check the character encoding.

```
$ qrencode -t ansiutf8 https://teratermproject.github.io/

█████████████████████████████████████
█████████████████████████████████████
████ ▄▄▄▄▄ █▀█ █▄   ▀██▄ █ ▄▄▄▄▄ ████
████ █   █ █▀▀▀█ ▄▀ █▀ ▄██ █   █ ████
████ █▄▄▄█ █▀ █▀▀██▄▄ ▄▄ █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀ ▀▄█ █ █ █ █▄▄▄▄▄▄▄████
████▄  ▄ █▄▄ ▄▀▄▀▀▀▀█▄▀▀▀▄▀ ▀▄█▄▀████
████▀▀ ▄▄█▄▄▀█▄█▀ ▄▄ ▄█▀█▀█▄ ▀█▀█████
████ █ ▄▀█▄█▀ ▄█▄█▄██ ▀ ▀▀▀▀▀▄▄█▀████
████  ▀▄▀ ▄██ █ ▄█▀▄ █▄▀ ███▀▄▄▀█████
████▀ ▄▀█▀▄█▀ ▀▄▀▀▀█▀▄█ ▀█▀ ▀▄ █▀████
████ █▄▀▄█▄ ▀▀██▀ ▄ ▄█▀▀█ ▀  █▄▀█████
████▄█▄█▄█▄█▀ ▀█▄█▄█▀ ▀▀ ▄▄▄ ▀   ████
████ ▄▄▄▄▄ █▄█▀ ▄█▀▄▀█   █▄█ ▄▄▀▀████
████ █   █ █  █▄▀▀▀██▄██▄▄▄▄▄▀  ▀████
████ █▄▄▄█ █ ▀██▀ ▄▄███▀▀▄ ▄  ▄ █████
████▄▄▄▄▄▄▄█▄███▄█▄▄█▄█▄███▄▄▄▄██████
█████████████████████████████████████
█████████████████████████████████████
```
For correct display, please set character encoding to UTF-8.
see setup - additional settings - coding tab and set UTF-8.

from man page
```
       -t    {PNG,PNG32,EPS,SVG,XPM,ANSI,ANSI256,ASCII,ASCIIi,UTF8,UTF8i,ANSI‐
       UTF8,ANSIUTF8i,ANSI256UTF8}
```

ASCII can usually be displayed correctly. (But it is difficult to read with a qr code reader.)
```
$ qrencode -t ASCII https://teratermproject.github.io/



        ##############      ##  ########      ####  ##############
        ##          ##  ##  ##    ########      ##  ##          ##
        ##  ######  ##          ####  ##    ####    ##  ######  ##
        ##  ######  ##  ######  ##  ####  ####      ##  ######  ##
        ##  ######  ##    ##          ############  ##  ######  ##
        ##          ##  ####  ####        ##    ##  ##          ##
        ##############  ##  ##  ##  ##  ##  ##  ##  ##############
                          ######    ##  ##  ##  ##
        ##########  ########  ##          ##      ##  ##  ##  ##
          ####  ##      ##  ##  ########    ######  ######      ##
            ######  ####    ##    ##########          ####
        ######          ##      ####    ##    ##  ##    ####  ##
        ##  ####    ##    ####  ##  ##    ##  ##          ####
        ##  ##  ##      ####              ################      ##
        ####  ##  ####    ##  ####    ####  ##  ##        ####
        ######  ####      ##  ##    ##  ##    ####      ##    ##
          ####      ##    ##  ##          ##  ##      ##  ####
        ####  ##  ##    ######  ######  ##    ####  ######  ##  ##
        ##  ##  ##  ####          ########        ##  ####  ##
        ##    ##      ######    ####  ##    ####  ########    ##
        ##  ##  ##  ##    ##    ##  ##    ##    ##########  ######
                        ######          ##########      ##########
        ##############  ##    ####    ##    ######  ##  ######
        ##          ##      ####    ##  ##  ######      ##    ####
        ##  ######  ##  ####  ##          ##    ##########  ####
        ##  ######  ##  ####    ######                    ########
        ##  ######  ##  ##        ######          ##############
        ##          ##  ####    ####          ####  ##  ####  ##
        ##############  ##      ##  ####  ##  ##      ########
```

**Comment by Donner-Party** [comment]
With the -t option, it still does not display correctly in Teraterm. I should have mentioned it does display correctly if I use Windows command line SSH.
![image](https://github.com/TeraTermProject/teraterm/assets/44014054/5b7fc8c8-9582-484e-a26a-aff558ae056a)

However, I did find this at the pivpn website and it works:
![image](https://github.com/TeraTermProject/teraterm/assets/44014054/e0b98954-3a89-4d85-83c4-5ab1bf0222e2)

![image](https://github.com/TeraTermProject/teraterm/assets/44014054/fb0337b6-bdef-4e0b-9687-4743b5dab64e)

Teraterm is set for UTF-8:
![image](https://github.com/TeraTermProject/teraterm/assets/44014054/5a5b9731-d5a2-454b-ba1a-69194e046490)

**Comment by zmatsuo** [comment]
Please use Tera Term 5.2.

Set as follows.

![image](https://github.com/user-attachments/assets/caf004f6-242d-470c-8d5f-099ded1abfb8)

Displayed

![image](https://github.com/user-attachments/assets/cb96afa1-1a8a-4250-ba8c-d19338db83ec)


When Ambiguous Characters width=2cell or Tera Term 4.x

Displayed

![image](https://github.com/user-attachments/assets/fc35e78e-d696-4c01-ad53-dbf75ec536ec)

**Comment by Donner-Party** [comment]
Thanks! That helped, it is working now.

I also had to change the font to Consolas. I had been using Lucida Sans Typewriter.
