### ISSUE TITLE
Executing tar from a macro.

### ISSUE THREAD

**Issue by Tonesh60** [TeraTermProject/teraterm#254]
Team,

I'm trying to execute the following within a macro, although "result" is reporting success the output file does not appear to be created.

	setdir TarballConfigFolder
 	execommand = "tar -czf ConfigTarball.tar.gz phase1 phase2 version"
	exec execommand

An empty file does appear in C:\Users\Tony\AppData\Roaming\teraterm5\ConfigTarball.tar.gz

Executing "tar -czf ConfigTarball.tar.gz phase1 phase2 version" from CMD or powershell works fine.

I'm running Version 5.2 (Git 176aed267) in Windows 11 and have experienced the same issues on Version 106 on Windows 10.

I've tried running this as both a standard user and admistrator with the same result.

Any thoughts?

**Comment by nmaya** [comment]
Hi,

Your macro code does not store result of `exec` command to `result` variable.
Please read [help of exec command](https://teratermproject.github.io/manual/5/en/macro/command/exec.html).

> If integer value &lt;wait&gt; is not 1 (default is 0):
> `0` means that succeeded to execute the application.

**Only executed** successfuly, **not a result** of executed command.


Other point:
Is `TarballConfigFolder` equals `C:\Users\Tony\AppData\Roaming\teraterm5` ?
Files `phase1` `phase2` `version` are exist in `C:\Users\Tony\AppData\Roaming\teraterm5` ?

Thanks,

**Comment by Tonesh60** [comment]
nmaya,
Firstly, thanks for your help and interest.

TarballConfigFolder is an arbitrary folder, for reference it’s set to “C:\Kenton\ProvisioningPortal\OrderProcessing\Test”

The folders “phase1”,  ”phase2” and “version” reside in the TarballConfigFolder.

C:\Users\Tony\AppData\Roaming\teraterm5 is a folder created by a teraterm5 install. My suspicion is that TeraTerm creates a temporary ConfigTarball.tar.gz file in this folder as when I attempt to execute the script as its time/date stamp changes each time I execute it. The only way to confirm my suspicions would be to track the functionality within the source code.
Result is being returned as 0.
I would expect the output file to appear in TarballConfigFolder. Though I’ve been asking myself whether teraterm subject to any file write permissions. Could this be the problem?
Thanks.

**Comment by Tonesh60** [comment]
nmaya,

Got there eventually. The solution was to specify the folder on the execution line like so:-

setdir TarballConfigFolder	
execommand = 'tar -czf ConfigTarball.tar.gz phase1 phase2 version'
exec execommand 'show' 1 TarballConfigFolder

Thanks again.
