### ISSUE TITLE
Tera Term 5.2 doesn't remember the COM port it used

### ISSUE THREAD

**Issue by MfromE** [TeraTermProject/teraterm#256]
In Tera Term 4.79 when I closed a port with Alt-I and reopened it with Alt-N, the dialog still showed the same COM port number as I used before.
In Tera Term 5.2 the Alt-N shows always the first COM port in the list. This is very annoying as I have many COM ports and are using them in parallel. I would appreciate if the old behavior would be back.

Thank you for this great program!

**Comment by zmatsuo** [comment]
I fixed.
Please download from following URL and try it.
https://ci.appveyor.com/project/teraterm/github-main/builds/50250819/artifacts

**Comment by MfromE** [comment]
The fix is working as expected. Thank you.
