### ISSUE TITLE
Closure of the original Tera Term home page (December 20, 2024)

### ISSUE THREAD

**Issue by shimarisu** [TeraTermProject/teraterm#259]
ベクターホールディングスより以下のような内容のメールを受信しました。

> 【Vector】ホームページサービス（hp.vector）終了のお知らせ
> 
> 株)ベクターホールディングスです。
> 弊社サービスをご利用いただき、ありがとうございます。
> 
> 誠に恐縮ではございますが、2024年12月20日をもちまして
> 弊社ホームページサービス（hp.vector）を終了とさせていただきます。
> 
これにより、1996年から続いてきた、オリジナルのTera Termのホームページ
https://hp.vector.co.jp/authors/VA002416/
が2024年12月20日をもって終了することになると思われます。

**Comment by zmatsuo** [comment]
ドキュメント内の vector.co.jp へのリンク切れが発生することになりますね。
#274
5.3リリースは修正なしでよさそうです。
次のリリースには修正が必要ですね。
修正してからクローズしましょう。
再度オープンします。

**Comment by nmaya** [comment]
Vectorホームページが終了したことを確認しました。
