### ISSUE TITLE
鍵ファイルの保存パスに日本語が含まれる場合に「セッションの複製」に失敗する

### ISSUE THREAD

**Issue by lf-uraku-yuki** [TeraTermProject/teraterm#26]
SSH鍵ファイルを日本語を含むパスに保存している状態で「セッションの複製」を行うと、
複製の際にパスの文字化けが発生しセッションの複製に失敗します。

利用バージョン: 5.0 (SVN# 11000)
環境: Windows 11 Pro 23H2

**Comment by nmaya** [comment]
報告ありがとうございます。

[すでに報告済み](https://github.com/TeraTermProject/osdn-download/issues/31)で解消していると思います。
[mainの最新ビルド](https://ci.appveyor.com/project/teraterm/github-main/builds/48462926/artifacts)で問題なくなっていると思いますが、念のためご確認いただけるでしょうか。

**Comment by wakatono** [comment]
問題なく動作します。
closeしてますが、報告ということで。

**Comment by lf-uraku-yuki** [comment]
ご確認いただきありがとうございます。
修正済みの旨、承知いたしました。
