### ISSUE TITLE
TeraTerm Menu ドキュメント修正

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#261]
- 表記ゆれがあるので統一する
  - "TeraTerm Menu" (正)
  - "Tera Term Menu" (誤)
- 必要ならソースも修正する
- installer/release/ttmenu_readme-j.txt
  - このファイルは削除
  - ttpmenu/readme.txt を元にする
  - インストーラー
  - zip

https://github.com/TeraTermProject/teraterm/issues/246#issuecomment-2241613409

**Comment by hkanou** [comment]
TeraTerm Menu ドキュメント修正のPRを出させて頂きました。
cmakeとinstaller\release.batで動作確認を行いました(Win32版)
(AppVeyor、ARM/64bit版の動作確認はできておりません)

**Comment by hkanou** [comment]
マージ頂きまして大変ありがとうございます。
修正作業が重複してしまい、申し訳ありませんでした。

**Comment by zmatsuo** [comment]
> 修正作業が重複してしまい

いえいえ。
Assignees をうまく使えればいいんですけどね。

最初出なかったのですが、
今Assigneesをつついてみると hkanou さんが出てきます。
コメントすると追加できるのかもしれません。

**Comment by hkanou** [comment]
>今Assigneesをつついてみると hkanou さんが出てきます。
コメントすると追加できるのかもしれません。

ありがとうございます、コメントするようにいたします。

**Comment by zmatsuo** [comment]
これ修正します
とコメントして、assigneの設定をすればokですね。
やっていることが重複するともったいないので
アサインに気をつけますね。

修正完了したのでクローズします。

**Comment by hkanou** [comment]
>これ修正します
とコメントして、assigneの設定をすればokですね。
やっていることが重複するともったいないので
アサインに気をつけますね。

こちらこそ気を付けさせて頂きます。
>修正完了したのでクローズします。

ありがとうございます。
