### ISSUE TITLE
TTXKanjiMenu does not work with "Hide title bar"

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#265]
## 概要
メニューの KanjiCode から文字コードを変更あるいは再設定すると
文字入力ができなくなります。

## 再現方法
* スナップショットの[最新 1.0.38](https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50291521/artifacts)のポータブル版 zipを取得し、展開します。
* portable.ini を配置します。
* ttermpro.exe をエクスプローラでダブルクリックして起動し、普段使っているホストに ssh で接続してログインします。
* Setup - Window で Hide title bar のチェックを入れます。
* Control-左クリックでメニューを出し、KanjiCode から Recv/Send: UTF-8 を選択します。（どれを選択しても事象は同じです）
* 文字入力ができなくなります。
  * 再度 Control-左クリックでメニューを出し、KanjiCode を辿ると、選択が消失しています。

## 運用回避
* Control-左クリックでメニューを出し、Setup - Terminal を出して OK すると回復します。

## 関連していると思われる事象
* 上記 Hide title bar で TTXKanjiMenu の選択が消失している状態まで操作します。
* Additional Settings の Coding タブを出して OK します。
* メニューから KanjiCode が消失することがあります。

**Comment by sempreff** [comment]
- タイトルバーを残して Hide menu bar しても事象は発生します。
- commit 9babd50 を戻すと、事象は発生しなくなります。

**Comment by sempreff** [comment]
GetMenuItemInfoW が期待どおりに動作しないことがあるようです。
#266 は、小手先の回避案です。もちろんもっと良いやり方があると思いますが、まずは「文字入力ができない」という致命的な事象を逃れたい思いです。

**Comment by zmatsuo** [comment]
レポート、PR ありがとうございます。

根本対策を行いました。
PRのtypo修正も取り込みました。
試してみていただけないでしょうか


ちょっと余談、
近い未来 ts->Language をなくそうと考えています。
この変数がなくなれば制限がなくなるのになと思う部分があります。

そのときkanjimenu は
```
 [日本語▼]
 |韓国語  |
```
みたいなドロップボックスがある
設定ダイアログを持つことになるかなと考えています。

**Comment by sempreff** [comment]
ご対応ありがとうございます。
ローカルで確認してみたところ、動作良好なようです。

余談についてですが、TTX KanjiMenu をダイアログに作り替えるということでしょうか？
https://naoh16.seesaa.net/article/35220277.html
で言及されているように「メニューからワンタッチで指定できること」のために生まれたものなので、
ダイアログにしてしまうのはちょっと違うかな、と感じました。

**Comment by zmatsuo** [comment]
動作良好とのことで、よかったです。
クローズします。

切り替える言語(表示するメニュー)を選択できるようにしたいなと考えています。
```
✔ 日本語
   韓国語
```
みたいなサブメニューでも良いかなと 考えています。

もうビルドされていると思いますが appveyor でもビルドしました。
https://ci.appveyor.com/project/teraterm/github-main/builds/50328707/artifacts
