### ISSUE TITLE
Changing debug mode via the keyboard not working in V5

### ISSUE THREAD

**Issue by togrady** [TeraTermProject/teraterm#273]
Tera Term 5.2
Windows 11 Pro

The debug mode does not change for me when using the keyboard (shift + escape). Can anyone confirm if it works for them? If I run a macro to set debug mode it works as expected. I have made the changes in teraterm.ini to support this. This worked for me when using Tera Term V4.xxx.
The relevant section of my teraterm.ini looks like so:

```
; Display all characters (debug mode)
Debug=on
; Debug mode type which can be selected by user.
;   on|all   = All types
;   off|none = Disabled debug mode
;   normal   = usual teraterm debug mode
;   hex      = hex output
;   noout    = disable output completely
DebugModes=all
```

As a workaround I made the following macro to set the required debug mode:

```
app_name = "Debug Mode Selector"

strdim options 4
options[0] = "Off (normal)"
options[1] = "How non-printable characters"
options[2] = "All bytes as hex"
options[3] = "Disable output completely"

listbox "Select Debug Mode" app_name options
debug_mode = result

setdebug debug_mode
```

**Comment by zmatsuo** [comment]
Hi,

Select Setup / Setup directy... .
And check "Tera Term Cofignuration File" in "Setup directy dialog"

Tera Term 4 and 5 have different folders for ini files

**Comment by togrady** [comment]
Thank you! This worked. I did not know that the ini file location had changed.

**Comment by efa** [comment]
> As a workaround I made the following macro to set the required debug mode:

I'm using 5.6.0 portable. The Setup / Setup directy, config file point to:
D:\ProgramFiles\teraterm-5.6.0-x64\TERATERM.INI
debug mode does not work, I cannot see the hex bytes
