### ISSUE TITLE
getttpos コマンドで取得位置がずれることがある

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#275]
TERATERM.INI で DpiAware=off を指定し、
ディスプレイの拡大/縮小率を100%(96dpi)以外にしている場合に、
取得した VT window のX,Y座標とサイズがずれている

getttpos コマンドは #234 で追加

https://github.com/TeraTermProject/teraterm/issues/274#issuecomment-2294882070 より

**Comment by zmatsuo** [comment]
> https://github.com/hkanou/teratermproject_teraterm/commit/8ffcb3e55a329bf418bcf2305e7e0d986616ad1e

ttpmacro側で倍率を計算するのではなくttermpro側で行ってはどうでしょうか?

DPIに関連するものをttermpro内に閉じ込めることができるのがよさそうに思います。
ハンドルを他のプロセスに渡さなくても良いですし。

最近のWindowsではプロセスをまたいでハンドルを使用できないと思っていました。
できるなら他のウィンドウの内容を変更、内容取得できてしまいますよね。
それは危険な感じです。
APIによってはokかもしれませんが、
しなくて済むなら避けたほうが今後のためにもよさそうです。

**Comment by hkanou** [comment]
>ttpmacro側で倍率を計算するのではなくttermpro側で行ってはどうでしょうか?

ご確認頂きありがとうございます。

>最近のWindowsではプロセスをまたいでハンドルを使用できないと思っていました。
できるなら他のウィンドウの内容を変更、内容取得できてしまいますよね。
それは危険な感じです。
APIによってはokかもしれませんが、
しなくて済むなら避けたほうが今後のためにもよさそうです。

安易な実装でした。
ttermpro側で倍率を計算してハンドルを渡さない実装に見直しいたします。

**Comment by hkanou** [comment]
> ttermpro側で倍率を計算してハンドルを渡さない実装に見直しいたします。

dcda75f ttermpro側で座標からDPIを取得するよう修正いたしました。
(DPI取得部分は GetDpiForRect() として共通ライブラリに追加した方が良かったかもしれません)

**Comment by hkanou** [comment]
[eb79f5f](https://github.com/hkanou/teratermproject_teraterm/commit/eb79f5f66679118e4b4889286585bfdb6f1f06f5) でTERATERM.INI の DPIAware=off が ttpmacro に反映されるよう修正いたしました。

DPIAware の設定が下記の2か所で行われていましたが、https://github.com/TeraTermProject/teraterm/blob/9f7d478a0c5764ef4f6387df95449b8ceb3db18f/teraterm/ttpmacro/ttmacro.cpp#L143 は TERATERM.INI を参照せず、https://github.com/TeraTermProject/teraterm/blob/9f7d478a0c5764ef4f6387df95449b8ceb3db18f/teraterm/ttpmacro/ttmacro.cpp#L88 には DPIAware=off の処理がないため、常に高DPI対応が有効になっていました。

TERATERM.INI で DPIAware=off を指定した場合、下記のようにDPI設定が揃っていない状態となり...
- VT ウインドウ = DPIAware=off
- MACRO ダイアログ = DPIAware=on

一部の構成で、取得位置にずれが発生していました。

```
A = プライマリディスプレイの拡大率(%)
B = セカンダリディスプレイの拡大率(%)
C = メッセージダイアログの表示位置がプライマリディスプレイの場合の位置ずれ 〇:無, ×:有
D = メッセージダイアログの表示位置がセカンダリディスプレイの場合の位置ずれ 〇:無, ×:有
----------------------------------------------------------------------------------------
A    B    C   D
100  100  〇  〇
100  125  〇  ×
100  150  〇  ×
100  175  〇  ×
125  100  〇  〇
125  125  〇  〇
125  150  〇  ×
125  175  〇  ×
150  100  〇  〇
150  125  〇  〇
150  150  〇  〇
150  175  〇  ×
175  100  〇  〇
175  125  〇  〇
175  150  〇  〇
175  175  〇  〇
```

[eb79f5f](https://github.com/hkanou/teratermproject_teraterm/commit/eb79f5f66679118e4b4889286585bfdb6f1f06f5) は、上記の不具合を解消するためのものです。

**Comment by hkanou** [comment]
https://github.com/hkanou/teratermproject_teraterm/commit/dcda75f895c93a30f77ac91becb33dbbad4e36bf
で下記のメッセージが表示されることに気づきました。(常に表示されるわけではないようです)
[8ffcb3e](https://github.com/hkanou/teratermproject_teraterm/commit/8ffcb3e55a329bf418bcf2305e7e0d986616ad1e)の commit メッセージの issues 番号修正時、フォースプッシュしたのが原因と思われますが、現状修正できておりません。
申し訳ございませんが、まずは事象の報告をさせて頂きます。

"This commit does not belong to any branch on this repository, and may belong to a fork outside of this repository."

<img width="752" alt="image" src="https://github.com/user-attachments/assets/6732481d-388f-4681-a7a7-2a12fd599cff">

**Comment by zmatsuo** [comment]
> 下記のメッセージが表示されることに気づきました

ブランチが名無しになっていて、参照できない状態になっているのではないでしょうか。
(名前がなくなってもハッシュなら参照できる)
名前(ブランチ名)を付ければ参照できるようになって警告が出なくなると思います。

**Comment by hkanou** [comment]
>> DPIAware=off の処理がないため、常に高DPI対応が有効になっていました。

>ぜひ修正をマージしたいです。

作業加速いたします。

>>下記のメッセージが表示されることに気づきました

>ブランチが名無しになっていて、参照できない状態になっているのではないでしょうか。
名前(ブランチ名)を付ければ参照できるようになって警告が出なくなると思います。

お陰様でハッシュ有り/名前無しでしたが、名前有り？(git logで表示されるよう)にすることができました。
まだ、GitHUBで警告メッセージが表示されますが、他への影響は無さそうです。
ご教授頂きありがとうございます。

**Comment by hkanou** [comment]
>まだ、GitHUBで警告メッセージが表示されますが、他への影響は無さそうです。

警告メッセージを消すことは叶いませんでしたが、ビルドしたexeファイルの動作確認は問題ありませんでしたのでPRを出させて頂きます。

**Comment by hkanou** [comment]
こちらもマージ頂き大変ありがとうございます。

**Comment by zmatsuo** [comment]
クローズします。
