### ISSUE TITLE
MACRO : マルチディスプレイ環境でディスプレイ間の拡大率に差異がある状態で、ttpmacroの表示ダイアログを別ディスプレイに移動するとダイアログの表示がくずれる

### ISSUE THREAD

**Issue by hkanou** [TeraTermProject/teraterm#277]
- 発生事象
マルチディスプレイ環境でディスプレイ間の拡大率に差異がある状態で、ttpmacroの表示ダイアログを別ディスプレイに移動するとダイアログの表示がくずれる。
- 原因
ダイアログのサイズ変更が出来るようサイズ変更時にボタン類の座標を計算しているが、WM_DPICHANGED受信時に座標の再計算をしていないため。
- 対処
WM_DPICHANGED受信時に座標の再計算を行う処理を追加する。
- 対応状況
WM_DPICHANGED受信時の処理を追加中。(Tera Term 5.3 のリリースには間に合わない見込み)

**Comment by hkanou** [comment]
PRを出させて頂きました。[e072c31](https://github.com/TeraTermProject/teraterm/pull/311/commits/e072c312637403a3fd85425ca1838752910c612d)

- 制限事項：明示的なフォントサイズの指定を行っていないため、ディスプレイ間のDPIに差異があると文字の表示数が少し変わります。
- ダイアログのサイズ変更時の動作が一部不自然だったため修正しています。

**Comment by nmaya** [comment]
> ディスプレイ間の拡大率に差異がある状態で、ttpmacroの表示ダイアログを別ディスプレイに移動するとダイアログの表示がくずれる

まず、最初の問題がどういうものか把握できていないのですが、[snapshot](https://ci.appveyor.com/project/hkanou/teratermproject-teraterm/builds/50563558/artifacts) と 5.3 の動作を比較してみました。

- main display ... 100%
- 2nd display ... 150%

``` 277.ttl
messagebox "foo bar baz\nfoo bar\nbaz" '#277 snapshot' 1
```

1. main display に表示
![1-main_display](https://github.com/user-attachments/assets/aadd9a56-0efb-4054-86ac-8b27a239885c)

2. 2nd display へ移動
![2-move_to_2nd_display](https://github.com/user-attachments/assets/192ec865-9052-4e31-beb5-b2eab1bdb31c)

3. 2nd display で表示中にダイアログを広げる
![3-expand_dialog](https://github.com/user-attachments/assets/07b9bca4-b063-4d4c-8961-88a6262fdc8b)

4. そのまま main diaplay へ移動
![4-move_to_main_display](https://github.com/user-attachments/assets/9060f908-5375-48e7-8f50-87131b694378)

-----

Q1. 最初の問題はどういものでしょうか。5.3 のほうで現れている「解像度の違うディスプレイ上でダイアログを**リサイズしたとき**に配置がおかしくなる」のことであっていますか？タイトルは「解像度の違うディスプレイに**移動したとき**に配置がおかしくなる」と読めますが、手元では確認できませんでした。

Q2. snapshot では 2nd display に移動するとテキストがちょっと欠けました。main display を 150% にして起動したときは欠けませんでした。
この差があるのが不思議なのですが、再現しますか？
![5-150%_main_display](https://github.com/user-attachments/assets/4e778c88-b901-4413-9168-342faa9a2372)

**Comment by hkanou** [comment]
>まず、最初の問題がどういうものか把握できていないのですが、[snapshot](https://ci.appveyor.com/project/hkanou/teratermproject-teraterm/builds/50563558/artifacts) と 5.3 の動作を比較してみました。

ご確認頂きありがとうございます。

>Q1. 最初の問題はどういものでしょうか。5.3 のほうで現れている「解像度の違うディスプレイ上でダイアログをリサイズしたときに配置がおかしくなる」のことであっていますか？タイトルは「解像度の違うディスプレイに移動したときに配置がおかしくなる」と読めますが、手元では確認できませんでした。

最初に気づいた問題はlistboxを「解像度の違うディスプレイに移動したときに配置がおかしくなる」というものでした。左記に該当するのはlistboxとstatusboxでmessagebox他は問題ありません。
ただ、messagebox他もリサイズすると配置がおかしくなりますので「解像度の違うディスプレイ上でダイアログをリサイズしたときに配置がおかしくなる」の方が適切ですね。

>Q2. snapshot では 2nd display に移動するとテキストがちょっと欠けました。main display を 150% にして起動したときは欠けませんでした。
この差があるのが不思議なのですが、再現しますか？

再現いたしました。
https://github.com/TeraTermProject/teraterm/blob/0c8869a6da91d0edf19e923e8abe793138cf424c/teraterm/ttpmacro/msgdlg.cpp#L90
```
TW = s.cx + s.cx/10;
TH = s.cy;
```
メッセージの幅(TW)は10%のマージンを見ているのに対し、高さ(TH)のマージンがなかったため解像度の違いを吸収できていませんでした。処理を見直します。
ご指摘頂きありがとうございます。

**Comment by hkanou** [comment]
>Q2. snapshot では 2nd display に移動するとテキストがちょっと欠けました。

0cb699e で文字欠けに対応いたしました。
動作確認用のバイナリの格納先は以下のとおりです。
https://ci.appveyor.com/project/hkanou/teratermproject-teraterm/builds/50607087/artifacts

**Comment by nmaya** [comment]
> 動作確認用のバイナリ

ありがとうございます。

> listboxを「解像度の違うディスプレイに移動したときに配置がおかしくなる」

この問題を 5.3 で確認し、修正されていることをバイナリで確認しました。

> messagebox を「解像度の違うディスプレイでリサイズしたときに配置がおかしくなる」

こちらも修正されていることをバイナリで確認しました。

**Comment by hkanou** [comment]
ご確認頂きましてありがとうございます。
お手数をおかけいたしました。

**Comment by nmaya** [comment]
PR #311 のほうでお願いした

> > 可能なら、別の修正に関する PR はまとめず別の PR にしてもらうことはできるでしょうか？

> [別の PR に分けるようにいたします。](https://github.com/TeraTermProject/teraterm/pull/311#issuecomment-2348743267)

をお待ちします。

**Comment by hkanou** [comment]
リマインド頂きありがとうございます。
別のPRに分けるようにいたします。

**Comment by nmaya** [comment]
マージしました。ありがとうございます。

**Comment by nmaya** [comment]
ビルドをかけました。
https://ci.appveyor.com/project/teraterm/github-main/builds/50685487

**Comment by hkanou** [comment]
マージ頂きましてありがとうございます。
本issueをクローズさせて頂きます。
