### ISSUE TITLE
version_str ブランチ

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#278]
キャプチャできなかったのですが「version_str ブランチが main ブランチに取って代わった」のような警告メッセージが出ました。（fork している人だけに出るものでしょうか？）
version_str ブランチは 8/16 に作成され、 9f7d478a0c5764ef4f6387df95449b8ceb3db18f は 8/16 にコミットされていて、マージコミットはないようです。

警告が出たということは、他の作業者に影響の出る操作があったのでしょうか？どのような操作をされましたか？

**Comment by zmatsuo** [comment]
誤って別のアカウントでpushしてしまい、
ブランチを削除しても
contributor のところにアカウントが残っていました。

消す方法を見つけました [GitHubでContributorを消す方法](https://eorf.hatenablog.com/entry/2022/08/12/025227)。
うまく消えれば他の方が誤ってpushしたときにも対応できると思い試してみました

操作としては次のようにしました。
- version_str ブランチをpush
- main を削除
- version_str ブランチにmainにrename

リポジトリの内容(ファイルなど)は変化していません。

一瞬ですがmainが消えているので、
その時に clone したり pull すると main がない
リポジトリとなっていると思います。
失礼しました。

この後 contributor に残っていたアカウントは消えました。
main を作成したときに contributor を作り直しているのでしょう。

**Comment by nmaya** [comment]
了解しました。
