### ISSUE TITLE
貼り付け操作時にローカルエコーが表示されない

### ISSUE THREAD

**Issue by matsujirushi** [TeraTermProject/teraterm#28]
ローカルエコーをチェックしているときに、`編集`>`貼り付け`したテキストがウィンドウに表示されない。
（`貼り付け`を使わず、キーボードからポチポチ入力したときは表示される。）

### TODO
- [x] 修正
- [x] 変更履歴
- [x] mainへのマージ

**Comment by zmatsuo** [comment]
修正しました。

修正済みバイナリを次のURLからダウンロードできます。
https://ci.appveyor.com/project/teraterm/github-snapshot/build/artifacts
(ビルド中です。もうすぐダウンロードできるようになります)

**Comment by matsujirushi** [comment]
ご対応いただきありがとうございます！
確認します。

**Comment by matsujirushi** [comment]
動作確認しました。バッチリ動作しました。
どうもありがとうございました。
