### ISSUE TITLE
Appveyor でビルドするときの Inno Setup バージョン

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#283]
「Inno Setup」は、リリースプロセスで最新バージョンを確認し通常はアップデートするものひとつである。
[開発環境・ライブラリ](https://teratermproject.github.io/manual/5/ja/reference/develop-environment.html) には、バージョンも記されている。

現在は 6.2.2 と記されていて、最新は 6.3.3 が出ている。
リリースは「AppVeyor でビルドする」ことになっているが、以下の理由でバージョンをコントールすることができない。

### ビルドに使われる Inno Setup

cf. https://github.com/TeraTermProject/teraterm/issues/274#issuecomment-2305136585

> bulidtools/ に Inno Setup をダウンロードしておけば、自動的に使われるはずです。
> **なければシステムにインストールされているものを使います。**
> ダウンロードは buildtools/install_innosetup.bat をコールすればokです。

### Appveyor の Inno Setup

https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50447248

```
Inno Setup 6 Command-Line Compiler
Copyright (C) 1997-2023 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2023 Martijn Laan. All rights reserved.
Portions Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.
https://www.innosetup.com
Compiler engine version: Inno Setup 6.2.2
Preprocessing
   Reading file: C:\Program Files (x86)\Inno Setup 6\ISPPBuiltins.iss
```

- C:\Program Files (x86)\Inno Setup 6 にインストールされている
- インストールされているものが使われている
- バージョンは 6.2.2

**Comment by nmaya** [comment]
[appveyor_vs2022_bat.yml](https://github.com/TeraTermProject/teraterm/blob/main/ci_scripts/appveyor_vs2022_bat.yml) の before_build で [install_innosetup.bat](https://github.com/TeraTermProject/teraterm/blob/main/buildtools/install_innosetup.bat) を呼ぶと、[install_innosetup.cmake](https://github.com/TeraTermProject/teraterm/blob/main/buildtools/install_innosetup.cmake) に書かれているバージョンを用いることができる。

**Comment by nmaya** [comment]
buildtools\innosetup6 の Inno Setup が使われるようになりました。

https://ci.appveyor.com/project/teraterm/github-main/builds/50462798

```
Inno Setup 6 Command-Line Compiler
Copyright (C) 1997-2024 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2024 Martijn Laan. All rights reserved.
Portions Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.
https://www.innosetup.com
Compiler engine version: Inno Setup 6.3.3
Preprocessing
   Reading file: C:\projects\github-main\buildtools\innosetup6\ISPPBuiltins.iss
Parsing [Setup] section, line 33
Parsing [Setup] section, line 34
```

**Comment by zmatsuo** [comment]
関連した修正を行いました。#284
6.3.3が使われていますね。👍

**Comment by nmaya** [comment]
appveyor_release_bat.yml の修正が漏れていたので、5.3 リリースでは 6.2.2 が使われていた。
https://ci.appveyor.com/project/teraterm/github-release/builds/50557994#L2931
