### ISSUE TITLE
ciスクリプトを整理する

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#284]
- スクリプトを統合する
  - buildtools/install_innosetup.bat
  - buildtools/install_cygwin.bat
- 代替できるファイルを削除
- 参考 #283

**Comment by zmatsuo** [comment]
環境変数 NOPAUSE を参照して、
CIから使用したときは一時停止(pause)しないようにしました。

クローズします。

**Comment by nmaya** [comment]
シンプルになりましたね、ありがとうございます。
