### ISSUE TITLE
General ダイアログのドロップダウンリストの内容が二重になる

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#288]
## 概要
ExeDir と HomeDir が同じ場合、General ダイアログのドロップダウンリストの内容が二重になります。

## 再現手順
1. portable.ini を置きます。
1. Setup -> General... で General ダイアログを出します。
1. LaunguageUI のドロップダウンリストの内容が二重になっています。

## 修正案
単純に、パスが同じなら二回見に行かないのが良いと思います。 #287 です。

**Comment by nmaya** [comment]
マージしました。

**Comment by zmatsuo** [comment]
char ではなく wchar_t 文字列なので、比較を wcscmp() に置き換えました。
