### ISSUE TITLE
ウインドウサイズを変更すると、同じ行で折り返してしまう。

### ISSUE THREAD

**Issue by DoiTakahiro** [TeraTermProject/teraterm#29]
組み込みＬｉｎｕｘのシリアルコンソールにＣＯＭ接続で接続しています。
ウインドウサイズを変更すると、80桁を超えると同じ行の先頭に戻ります。
ウインドウサイズを変更しない場合は、文字を入力して右端に行った後は、次の行の先頭に文字が入力されます。
ＳＳＨ接続の時は問題ありません。
バージョン5．0で確認しました。
どこか設定がありますか？

**Comment by zmatsuo** [comment]
telnet,sshでは処理されるSIGWINCHシグナルが
処理されないからではないでしょうか

次のページが参考になりました。
https://remoteroom.jp/diary/2021-08-20/

Tera Term 4 ではどのような動作でしょうか?

**Comment by ttdoda** [comment]
端末の高さ、および幅はLinux側ではttyが管理しています。現在の値は`stty -a`コマンドで確認できます。
```
% stty -a
speed 38400 baud; rows 102; columns 120; line = 0;
intr = ^C; quit = ^\; erase = ^H; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = <undef>; start = ^Q; stop = ^S;
susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe -echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```
上記の例では、端末のサイズは幅120桁、高さ102行となっています。

bashではこの設定を利用して、コマンドラインの表示の制御を行っています。

Tera Term側でウィンドウサイズを変更した場合、新しいウィンドウサイズをttyに反映しなければ表示が正しく行われなくなります。

TELNET接続やSSH接続ではウィンドウサイズの変更を通知する方法(TELNETはNAWSオプション、SSHはwindow-change channel request)が有ります。
Tera Termはウィンドウサイズ変更時にこれらを使って新しいウィンドウサイズを通知する為、ttyの設定が自動で更新されます。

しかしシリアル接続時にはこのようなウィンドウサイズを通知する手段が無い為、Tera Termのウィンドウサイズを変更した後に手動で`stty`コマンドを実行して設定を更新する必要が有ります。
例えば、ウィンドウサイズを幅132桁、高さ40行に変更した場合は `stty cols 132 rows 40` を実行してください。

## resize コマンド

xtermの付属コマンドに`resize`というコマンドが有ります。

`stty`コマンドで端末の幅や高さを設定する場合、新しい幅や高さを調べてその値をコマンドに指定する必要があります。
これに対して`resize`コマンドはウィンドウの幅や高さをコマンドが自分で調べて、ttyに設定してくれます。
組み込みLinuxという事ですが、もし`resize`コマンドが入っていたならばこちらを使う方が楽でしょう。

また、`resize`コマンドのウィンドウサイズを調べてttyに反映する部分の機能をbashスクリプトで作成してみました。
スクリプトは以下のURLから入手できます。

https://gist.github.com/ttdoda/0420f1f88d633e925c86a9a900605d24

もし`resize`コマンドが無かった場合は、このスクリプトを適当な場所に保存しておき、ウィンドウサイズを変更した時にスクリプトを実行するとttyの設定が更新されます。

**Comment by DoiTakahiro** [comment]
皆様、ご回答ありがとうございました。
TeraTerm4でも同様な動きでした。
組み込みLinux（PetaLinux)にresizeコマンドが入っていましたので、ウインドウサイズ変更後、resizeコマンドを実行すれば、stty -aの値も更新され、問題なく改行されることを確認しました。また、resizeスクリプトの動作も確認しました。
解決しましたので、本件クローズとさせていただきます。
ご協力、ありがとうございました。
