### ISSUE TITLE
TTXKanjiMenuのACCESS_VIOLATION

### ISSUE THREAD

**Issue by hkanou** [TeraTermProject/teraterm#301]
TTXKanjiMenuプラグインが下記の状態の場合ACCESS_VIOLATIONが発生するように思われます。
- ttxkanjimenu.dll が有効な状態
- TERATERM.INI で Language=Japanese か Korean 以外を指定 (例 Language=English)
- Tera Term のメニューバーをクリック

Language=Japanese か Korean 以外の場合、メニューが無いためteraterm/TTXKanjiMenu/ttxkanjimenu.c の 177行の end = p->id; で info_ptr[-1] を参照して例外が発生します。

修正案 ttxkanjimenu.c (自身のメニューの場合のみ処理するよう修正)

   426  static void PASCAL TTXModifyPopupMenu(HMENU menu) {
   427      // メニューが呼び出されたら、最新の設定に更新する。(2007.5.25 yutaka)
  追加      if (menu == pvar->hmEncode) {
   429          (void)menu;
   430          UpdateRecvMenu(pvar->ts->KanjiCode);
   431          if (!pvar->UseOneSetting) {
   432              UpdateSendMenu(pvar->ts->KanjiCodeSend);
   433          }
   434          CheckMenuItem(pvar->hmEncode, ID_MI_USEONESETTING, MF_BYCOMMAND | (pvar->UseOneSetting)?MF_CHECKED:0);
  追加      }

**Comment by zmatsuo** [comment]
ありがとうございます。

マージしました。
