### ISSUE TITLE
Scoop compatibility issue / persisting of INI files 

### ISSUE THREAD

**Issue by cheyrich** [TeraTermProject/teraterm#303]
Scoop uses Windows hard links to persist application configuration across version updates.

TeraTerm does not work correctly in that environment. I guess this is due to the Auto Backup feature (which seems to be configurable in the upcoming version: https://teratermproject.github.io/manual/5/en/setup/teraterm-misc.html#IniAutoBackup) 

It seems like Tera Term renames the existing INI file with a timestamp prefix, and creates a new file to be used as the new valid INI file. That way the hard link would stick to the renamed file and causing the issue. I guess the process should be changed so that the backup file is the newly created file. 

This is the result of a freshly extracted TeraTerm 5.2:
```
fsutil file queryfileid TERATERM.INI
File ID is 0x000000000000000000020000000953b0
```
Then ttermpro.exe is started for the first time and closed again.
```
fsutil file queryfileid TERATERM.INI
File ID is 0x00000000000000000005000000095403

fsutil file queryfileid 20240903T163749+0200_TERATERM.INI
File ID is 0x000000000000000000020000000953b0
```

Same applies to KEYBOARD.CNF as well on the first start. And probably other cfg files later on certain conditions

Please refer issue description here as well:
https://github.com/ScoopInstaller/Scoop/issues/6128

Thanks

**Comment by nmaya** [comment]
[current code](https://github.com/TeraTermProject/teraterm/blob/176aed2671bda031f2d0c0b09af463feba8e428c/teraterm/common/ttlib_static_cpp.cpp#L1423)

@zmatsuo 現在のコードは

- 現ファイルをバックアップファイル名へ移動
- バックアップファイルを現ファイル名へコピー

このようになっています。

ファイルを移動するとハードリンクがバックアップファイルを向くそうです。（シンボリックリンクを使えば問題は起きないように思いますが…）
「現ファイルをバックアップファイル名にコピー」という処理にせず、今の処理にした経緯などあるでしょうか？

**Comment by zmatsuo** [comment]
> 「現ファイルをバックアップファイル名にコピー」という処理にせず、今の処理にした経緯などあるでしょうか？

何かあったわけではなく、(なんとなく効率が良いかなと)このようにしました。
へんこうしても大丈夫だと思います。

**Comment by nmaya** [comment]
わかりました。説明ありがとうございます。

**Comment by zmatsuo** [comment]
> 何かあったわけではなく、(なんとなく効率が良いかなと)このようにしました。

コピーするようにしました。
こちらのほうが効率が良さそうです。

バックアップフィアルを作っても、
TERATERM.INI のファイル ID はそのままなのを確認しました。

変更履歴は
「TERATERM.INI のバックアップファイルの作成方法を変更した」でどうかなと思っています。

**Comment by nmaya** [comment]
@cheyrich Here is a snapshot that includes change 638fc9d311d0ff77b21bfed989ad559803a42421, stop moving current INI file when backup.
Is it meet your needs?
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50603208

**Comment by nmaya** [comment]
> コピーするようにしました。
> 「TERATERM.INI のバックアップファイルの作成方法を変更した」でどうかなと思っています。
ありがとうございます。よいと思います。

**Comment by zmatsuo** [comment]
改版履歴に追記して main にマージしました。
