### ISSUE TITLE
extended ASCII character set does not display in Tera Term 5

### ISSUE THREAD

**Issue by gingle** [TeraTermProject/teraterm#304]
I  am not able to display the extended ASCII character set in Tera Term 5. I am able to display them in Tera Term 4. I am setting the terminal to VT100. Are there other settings for TT 5?

**Comment by nmaya** [comment]
I can display `¼` (0xbc) in my env.
plz try some setting values in `Coding`, `Font` and `Characters width` etc.


- Windows 8.1 (Japanese)
- Tera Term 5.2

![ascii_ext](https://github.com/user-attachments/assets/c31e778d-2478-4945-b06a-c562d0717588)
![setting1](https://github.com/user-attachments/assets/6983a492-1c78-4d55-acf1-35165c1082eb)
![setting2](https://github.com/user-attachments/assets/b7bace0f-234c-4317-9fc6-29b0108cc076)

**Comment by gingle** [comment]
I do not find HackGen Console or Meiryo UI in my VTWindow Font Selections. This is the default font...
 ![image](https://github.com/user-attachments/assets/7bbd0ae9-5068-43cd-a97c-35e7c8f7dbee)

**Comment by gingle** [comment]
I was able to replicate TT4 ASCII by setting Font to Terminal/Regular/9 and unselecting "Drawing resized font to fit cell width" in Additional settings. Thanks.
