### ISSUE TITLE
TCP/IPでパケット送信できない

### ISSUE THREAD

**Issue by sakumoto1028** [TeraTermProject/teraterm#305]
`send $01$02` のようにコマンドを実行してもパケットが送信されません。
改行コードを送信すると初めて送られるのですが、仕様でしょうか？
改行コードを付けなくても送れる方法はありますか？

**Comment by nmaya** [comment]
TELNET なら [LINEMODE](https://teratermproject.github.io/manual/5/ja/setup/teraterm-com.html#linemode) が有効になっているのではないでしょうか？

**Comment by sakumoto1028** [comment]
@nmaya 
回答ありがとうございます🙇
[LINEMODE](https://teratermproject.github.io/manual/5/ja/setup/teraterm-com.html#linemode) をOffにすることで `send` コマンド実行時にパケットを送信することが出来ました！
