### ISSUE TITLE
Unicode 16.0

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#322]
https://www.unicode.org/versions/Unicode16.0.0/

https://forest.watch.impress.co.jp/docs/news/1622857.html
https://pc.watch.impress.co.jp/docs/news/1623252.html

**Comment by zmatsuo** [comment]
doc/ja/html/index.html に 「Unicode 16.0 準拠」と入れました。

対応文字コードを全部書くと大変なので
「UTF-8をはじめ多くの文字コードを使用可能」として
「日本語/英語/ロシア語/韓国語/UTF-8 モード」を削除しました。

**Comment by nmaya** [comment]
試せていませんが、更新ありがとうございます。
差し替えるたびに、変更履歴 （その他のところ）に差し替えたUnicodeのバージョンを書いてもいいかもしれませんね。

**Comment by zmatsuo** [comment]
tests/unicodebuf-unicode_15.1-.pl に追加された文字のテストを入れています。
手もとに対応しているフォントがないので
文字幅が正しいようだぐらいしかテストできていません。

> 変更履歴 （その他のところ）に差し替えたUnicodeのバージョンを書いてもいいかもしれませんね。

履歴に追記しました。
次回からは更新したTera Term のバージョンのところに追記しましょう。
