### ISSUE TITLE
LogAutoStart=on で切断後に新規接続するとエラーが表示される

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#323]
切断後もログ取得は継続されていますのでエラーを表示しないだけでOKかと思われます

**Comment by nmaya** [comment]
取り急ぎ、#157 による動作です。

**Comment by sempreff** [comment]
二重にログファイルを open しないようにする案で対策できたと思います。

**Comment by kattyo-abk** [comment]
修正すべきかどうかまではわからないのですが、動作確認中にあった事象を一応記載しておきます。

1. ログ自動取得開始
2. ログ取得を終了
3. 標準ログファイル名(default log file name)の設定を変更
4. 切断
5. 新規接続

とすると２度目以降の接続時に使用されるログファイル名が設定変更前の物になります。
（2, 3, 4 の順序関係はおそらくなし）

**Comment by kattyo-abk** [comment]
個人的な要望ですが、エラーダイアログが表示されるのがかなり厳しいので、
この部分だけでも修正版でリリースいただけると嬉しいです。

**Comment by sempreff** [comment]
stable ブランチがあると、こういう時に影響を小さくできて良いですね。

**Comment by kattyo-abk** [comment]
snapshot で確認させていただきます。

>  この部分だけでも修正版でリリースいただけると嬉しいです。

以前のリリースサイクルなら2か月くらいで新版が出たかなぁと思うと6か月間隔固定が微妙に長い…。

**Comment by sempreff** [comment]
以前は「[定期リリースは 3 ヶ月に一回](https://teratermproject.github.io/manual/4/ja/about/qanda.html)」でしたね。
今は「[半年に1回](https://github.com/TeraTermProject/teraterm/issues/23#issuecomment-1803944516)」ですが、
目下は大きな改造をしている状況なので、リリース間隔が長いことにはそれなりに意味/意義があると思います。

一方で、リリースに対する修正は 不安定な要素をできるだけ取り込まずに行えると良いので、繰り返しになってしまいますが、stable ブランチがあると良いですね。

**Comment by kattyo-abk** [comment]
正式版としてバイナリが公開されるなら stable branch でも main でもどちらでも嬉しいです（エラーが出るのは業務上では他人に勧めにくい→v5系だと最大で1年前近く前のバージョンを使い続ける事に）

**Comment by kattyo-abk** [comment]
Snapshot 確認したところ切断→新規接続時にログ取得エラー表示は無くなりました。
