### ISSUE TITLE
Need an option in TeraTerm not to autoexit after I manually disconnect from a remote SSH server.

### ISSUE THREAD

**Issue by antdude** [TeraTermProject/teraterm#327]
I couldn't find the option for it.

Thank you for reading and hopefully answering soon. :)

**Comment by nmaya** [comment]
#### How do you manually disconnect from a remote SSH server?
- Type 'exit' and return on remote shell?
- File-Disconnect from Tera Term menu?

#### What do you mean autoexit?
Does that mean close Tera Term Window?

**Comment by antdude** [comment]
Yeah, typing exit in SSH2 session. It closes my Tera Term window. :(

**Comment by nmaya** [comment]
Please use [Auto window close](https://teratermproject.github.io/manual/5/en/menu/setup-additional-tcpip.html#AutoWinClose) option.

**Comment by antdude** [comment]
Perfect and thanks. Strange place to put that option though. No wonder I couldn't find it.

**Comment by nmaya** [comment]
This is correct behavior.

When serial connection, VT Window is not close when disconnect.
When TCP/IP connection, user can select close or not close VT Window when disconnect.
