### ISSUE TITLE
Need English mailing lists.

### ISSUE THREAD

**Issue by antdude** [TeraTermProject/teraterm#328]
https://lists.osdn.me/mailman/listinfo/ttssh2-users and https://lists.osdn.me/mailman/listinfo/ttssh2-dev are in Japanese. It would be nice to have English language for English users like me. ;)

**Comment by nmaya** [comment]
OSDN is not managed by an administrator.
It is in an unstable state and we do not know when the service will stop.

We don't have a plan to make a English list.
In my opinion, currently GitHub Issues is optimal place.

**Comment by antdude** [comment]
That's disappointing.
