### ISSUE TITLE
SelectOnActivate デフォルト値の変更（あるいは修正）

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#332]
#244 は、
バックグラウンドにある teraterm ウィンドウを左クリックで選択して前面化したときに sensitively  に1キャラクタ選択されてしまう
という事象について、
SelectOnActivate を off にすることをワークアラウンドとしてクローズされています。
（自分も SelectOnActivate を off にして #155 を加えたことで妥協していました。）

しかし SelectOnActivate のデフォルトは on です。

SelectOnActivate を off にすることが多数の幸福であるなら、
デフォルトを off にするのは、いかがでしょうか。

あるいは別の選択肢として、 https://github.com/TeraTermProject/teraterm/commit/e91f4dcd53a31e8e94ca2f015b64f2db7d72c8bc で加えられた変更のうち一部を戻すことで、症状が改善して sensitiveに選択されることがなくなることが手元で確認できています。これを適用すると従来相当と動作になりますので、デフォルト値は変えなくてよいと思います。
できれば、こちらの適用をご検討いただけませんでしょうか。 #331 です。

**Comment by nmaya** [comment]
> SelectOnActivate を off にすることが多数の幸福である

いちユーザの私は VTWindow の client 部分をクリックしてウィンドウを選択することがないのでどちらでもよいのですが、どちらが幸福度が高いかがどのように測れますか？
SelectOnActivate は 2.3 からデフォルトが on のようなので、伝統的に「こういうもの」という認識の人もいると思います。

> https://github.com/TeraTermProject/teraterm/commit/e91f4dcd53a31e8e94ca2f015b64f2db7d72c8bc で加えられた変更のうち一部を戻す

こちらのほうがデフォルトを変えずに済むのでよいと思います。
コードを追えていませんし試せていませんが、#331で「sensitiveに選択されることがなくなる」らしいという話はわかりました。
ですが、当該コードはどんな理由があって入っている変更で、コードを戻すことで何がなくなるでしょうか？

**Comment by sempreff** [comment]
> 当該コードはどんな理由があって入っている変更

あいにく、わかりかねます。

> コードを戻すことで何がなくなる

バックグラウンドにある VTWindow の client 部分をクリックしてアクティブにする際に、センシティブに文字が選択される事象が発生しなくなる以外に、何かを失うということは無いように思います。

**Comment by nmaya** [comment]
> > 当該コードはどんな理由があって入っている変更

> あいにく、わかりかねます。

書いた人がいるので尋ねてみましょう。
@zmatsuo PR #331 をマージしてもいいでしょうか？
マージすると https://github.com/TeraTermProject/teraterm/commit/e91f4dcd53a31e8e94ca2f015b64f2db7d72c8bc で加えられた変更のうち一部が消えるそうです。
この消える部分はなにをしているでしょうか。消えることによる影響はあるでしょうか。

**Comment by zmatsuo** [comment]
LeftHalfOfDBCS()という関数名がいまいちですが、
複数セルの文字の先頭を返します。

従来(Tera Term 4)は 1or2Cell でした。

Tera Term 5 では、文字によっては2より大きい3Cellなどもあり
対応する必要があります。

例えば、Emacs Hello の Bengaliの1文字目等です
```
wget https://raw.githubusercontent.com/emacs-mirror/emacs/refs/heads/master/etc/HELLO -O -
```
```
Bengali (বাংলা) নমস্কার
```

AttrKanji がある部分が2Cellに関連した部分になります。
これを徐々になくしていきたいという方針で修正しています。

[VTWinに表示している文字の情報の表示](https://github.com/TeraTermProject/teraterm/wiki/Experimental-Debug-implementation#vtwin%E3%81%AB%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E6%96%87%E5%AD%97%E3%81%AE%E6%83%85%E5%A0%B1%E3%81%AE%E8%A1%A8%E7%A4%BA)で、
表示している文字のUnicodeやEmoji,Ambigous,cell数等を見ることができます。
かなり雑多に表示していてデバグ感が高い状態です。
ドキュメントは現在ないので、該当ソースを参照ください
BuffGetCharInfo()@buffer.c

Padding=TRUEのとき、複数cellの文字の先頭ではない部分のセル(漢字2cellの左1cellなどです)を示します。

できればAttrKanjiを使わない実装で調子よくしたいです。
ぱっと見、修正前後でそんなに変わらなさそうですが、
どうして修正後調子よくなるのでしょうねぇ。

**Comment by sempreff** [comment]
以下の修正案を試してみて、手元では良好に動作しています。

現象
  BuffChangeSelect を BuffStartSelect に揃えて AttrKanji を使う方式に戻すと安定する。

仮説
  BuffChangeSelect だけ LeftHalfOfDBCS を使うように修正されていて、
  BuffStartSelect が従来の AttrKanji を使う方式のまま残されているため
  開始と終了で x の計算方法が異なることになり、sensitive に選択されてしまうことになった。

対策
 BuffChangeSelect と同様に [BuffStartSelect も x の計算に LeftHalfOfDBCS を使うように修正](https://github.com/TeraTermProject/teraterm/pull/331/files)する。

疑問
  なぜ BuffChangeSelect だけ LeftHalfOfDBCS を使うように修正して、BuffStartSelect をそのままにしたのか？

**Comment by zmatsuo** [comment]
> 疑問
> なぜ BuffChangeSelect だけ LeftHalfOfDBCS を使うように修正して、BuffStartSelect をそのままにしたのか？

全てを一気に直せなかったからですね。

LeftHalfOfDBCS() を使うようにするといい感じになりますか?

**Comment by sempreff** [comment]
> LeftHalfOfDBCS() を使うようにするといい感じになりますか?

「手元では良好に動作しています」は、「いい感じ」と解釈していただいて大丈夫です。

従来の AttrKanji 方式であろうと 新しいLeftHalfOfDBCS方式であろうと、
BuffChangeSelect と BuffStartSelect とをどちらかに揃えてあげることがポイントだと思います。

**Comment by zmatsuo** [comment]
> 「手元では良好に動作しています」は、「いい感じ」と解釈していただいて大丈夫です。

了解です。
mainにマージしました。

小さい修正ですが、気になる方にはとても大きな修正になるかもしれません。
履歴にも入れといたほうがいいでしょうか?

**Comment by zmatsuo** [comment]
マージしました。
ありがとうございます。

**Comment by nmaya** [comment]
> マージ済の PR の更新ではなく別 PR になりました。

一度マージしてしまったらそうなると思います。
