### ISSUE TITLE
Time span of invert display when Visual Bell

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#333]
要望です。

悲しい事に、年のせいか短時間での visual bell のフラッシュがツラく感じるようになってしまいました。
（特に面積が大きい全画面表示時にそう感じる。）
可能であれば点灯時間を延ばす等の設定方法を追加いただけると助かります(puttyのような感じ)。
設定UIで設定できなくても良いです（INIファイル書き換えで済ませる）。

例
・点滅時の点灯時間を延ばす（周波数を減らす）
・カーソルの周りだけ、あるいは画面枠付近だけ点滅させるなど（点滅面積を減らす）

**Comment by nmaya** [comment]
ハードコーディングされている秒数をINIから読めるようにできたらよいと思ったのですが、blink には種類があって秒数が決まっているようです。

https://www.ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf

> slowly blinking (less then 150 per minute)
> rapidly blinking (150 per minute or more)

端末エミュレータは規格に沿って実装していて「エミュレーション」していると言えますので、それから外れる実装はしたくありません。

**Comment by kattyo-abk** [comment]
周波数や点滅などと書いたのでわかりにくかったかもしれません。
上記の SGR 5, 6 はおそらくキャラクタ属性についての仕様かと思います。
私の要望は ^G によるビープ音のかわりに Beep=visual に設定したときに画面が一瞬反転表示される描画方法のカスタマイズについての要望となります。

**Comment by nmaya** [comment]
10ms が指定されていました。

https://github.com/TeraTermProject/teraterm/blob/5b83fb6f727400f27a88ff189e64389fc6fea8c7/teraterm/teraterm/vtterm.c#L5689

どうやら、この Visual Bell というのは screen が元のようです。

https://github.com/TeraTermProject/teraterm/blob/5b83fb6f727400f27a88ff189e64389fc6fea8c7/teraterm/teraterm/vtterm.c#L1505

screen ではどれくらいの長さか見てみたら [1 sec](https://git.savannah.gnu.org/cgit/screen.git/tree/src/screen.h?h=v.5.0.0#n167) のようです。ずいぶん違いますね。

**Comment by kattyo-abk** [comment]
個人的には 1s 程ではなくても putty レベル(何秒だろ)にできると助かります。

このような感じでしょうか(msec指定)
BeepVisualFlashTime=500

**Comment by nmaya** [comment]
snapshotを作成しました。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50651166

**Comment by nmaya** [comment]
マージしました。

ビルドをかけました。
https://ci.appveyor.com/project/teraterm/github-main/builds/50685487

**Comment by kattyo-abk** [comment]
snapshot で動作確認できました（500はさすがに長かった模様）。
ありがとうございました。
