### ISSUE TITLE
Log Dialog cannot close (by X button)

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#334]
v4 ではログダイアログの×ボタンを押すとログ取得を停止したうえでログダイアログが閉じられました。
v5.3 ではログダイアログの×ボタンを押しても反応がありません。ログダイアログもクローズできません。
（×ボタンを押したらアイコンが消えるので、Windowメッセージの処理は入っているのかもしれません。）
323 で紹介された v5.4 snapshot でも同様です。

- ログ取得を停止したうえでログダイアログを閉じる（v4と同じ挙動）
- ログダイアログを隠す（＝ダイアログを閉じるだけでログ取得は継続）
- ×ボタンを表示しない
- （その他）

上記いずれかの挙動に変更したほうが良いと思いました。

**Comment by nmaya** [comment]
@zmatsuo 

> ログ取得を停止したうえでログダイアログを閉じる（v4と同じ挙動）

になっているのは意図的でしょうか？

**Comment by kattyo-abk** [comment]
ログダイアログを閉じるとログ取得が止まるのは v2.3 でも同様の挙動のようです。

**Comment by sempreff** [comment]
挙動が変わったのは、[ディスプレイ解像度に応じて適切なアイコンを使用するようにした](https://github.com/TeraTermProject/teraterm/commit/e5e2b60e0b9cae0cb0a985e2adda30385e1faf3a#diff-9cd0e523f5cafc2dd48f7b1d716674a11e635ca179744ecd17338f6106e28817R271) の副作用のようです。

**Comment by sempreff** [comment]
#341 のようにすると 4.x 相当の動きになりました。このような修正でよければ history.html も追記します。

hitstory.html 上では、このダイアログは何と呼ぶのが適当でしょうか？
- ログ出力状況ダイアログの×ボタンが動作しない問題を修正した。
- get the x button back to work on log status dialog.

…というような表現で良いでしょうか。

なお、自分はこのダイアログはいつも ESCキー打鍵で閉じていた（×ボタンを押すことがなかった）ので気づいていませんでした。

（File→Log で出るダイアログの「OK」「Cancel」「Help」のボタンの並び順が気になってきてしまいましたが、手を付けていません。やるなら別 issue ですよね）

**Comment by nmaya** [comment]
> https://github.com/TeraTermProject/teraterm/pull/341 のようにすると 4.x 相当の動きになりました。

ありがとうございます。

> このダイアログは何と呼ぶのが適当でしょうか？

このダイアログ名の件、確かに呼び分けが難しいですね。
「File」-「Show Log dialog」となっていますのでこれが「ログダイアログ」で、File→Log で出るダイアログは「ログファイル名指定ダイアログ」かなと思います。
[ヘルプ](https://teratermproject.github.io/manual/5/ja/menu/file-log.html)では「"Log" ダイアログボックス(ファイル名指定)」「"Log" ダイアログボックス(ファイルへ書き込み中)」と呼び分けていますね。

**Comment by nmaya** [comment]
[c74bc0d](https://github.com/TeraTermProject/teraterm/pull/341/commits/c74bc0ddf655c5f1bef32e2407392c407ec39a22) において、×ボタンでダイアログが閉じることを確認しました。
ありがとうございます。

**Comment by nmaya** [comment]
> （File→Log で出るダイアログの「OK」「Cancel」「Help」のボタンの並び順が気になってきてしまいましたが、手を付けていません。やるなら別 issue ですよね）

そのようにお願いいたします。
