### ISSUE TITLE
Webサイトの更新元を変更する

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#34]
teraterm/main/doc/web から web/main に変更する

### TODO
- [x] コンテンツの移動
- [x] TeraTermProject/TeraTermProject.github.io リポジトリへ反映するスクリプトの修正
- [x] [wiki:プロジェクトページの更新手順](https://github.com/TeraTermProject/teraterm/wiki/Update-Project-page) を更新

**Comment by zmatsuo** [comment]
teraterm リポジトリから分けて、webサイト用のリポジトリを試しに作ってみました。
https://github.com/zmatsuo/web
このようなイメージでよさそうでしょうか?
teraterm/web リポジトリを作ってみようと思います。


リポジトリの作成手順です。

1. あらかじめ web リポジトリを作っておく
  git@github.com:zmatsuo/web.git

2. TeraTermProject/teraterm リポジトリから doc/web/ を取り出してpush

```
git clone git@github.com:TeraTermProject/teraterm.git
cd teraterm
git filter-branch -f --subdirectory-filter doc/web/ -- --all
git remote add github git@github.com:zmatsuo/web.git
git push github
```

**Comment by nmaya** [comment]
ありがとうございます。
https://github.com/TeraTermProject/web は作成してあります。

**Comment by zmatsuo** [comment]
TeraTermProject/web リポジトリにソースを入れました。
Webサイトの更新元もこのリポジトリに変更しました。

**Comment by zmatsuo** [comment]
サイトに1か所誤りを見つけたので修正して更新しました。
うまく更新できているようです。

**Comment by nmaya** [comment]
ありがとうございます。

**Comment by zmatsuo** [comment]
teraterm リポジトリの doc/web は、
web リポジトリに移動したので削除してしまってokだと思います。
いかがでしょう?

**Comment by nmaya** [comment]
そうですね、削除してよいと思います。

**Comment by zmatsuo** [comment]
削除しました。
クローズします。
