### ISSUE TITLE
MACRO: CCtrlWindow::OnDpiChanged()の引数の脱字の修正

### ISSUE THREAD

**Issue by hkanou** [TeraTermProject/teraterm#346]
teraterm/ttpmacro/ttmmain.cpp CCtrlWindow::OnDpiChanged()の第2引数の脱字の修正になります。
https://github.com/TeraTermProject/teraterm/blob/8b2aa515d9b8d34e52f1189ca20b721cd8009fab/teraterm/ttpmacro/ttmmain.cpp#L703

修正前：LRESULT CCtrlWindow::OnDpiChanged(WPARAM wp, LPARAM)
修正後：LRESULT CCtrlWindow::OnDpiChanged(WPARAM wp, LPARAM lp)

**Comment by nmaya** [comment]
- 修正する
- lpは使っていないので実害はない
- 変更履歴は書かない

**Comment by hkanou** [comment]
> - 修正する
> - lpは使っていないので実害はない
> - 変更履歴は書かない

認識に齟齬はありません。
PR #311 に含まれていた cab18aa の修正です。

**Comment by nmaya** [comment]
マージしました。ありがとうございます。
