### ISSUE TITLE
MACRO: エラーダイアログのクローズボタン押下時の動作を Continue から マクロ終了確認ダイアログの表示 に変更

### ISSUE THREAD

**Issue by hkanou** [TeraTermProject/teraterm#347]
MACROのエラーダイアログのクローズボタン(Xボタン)押下時の動作を下記のように変更する修正になります。
変更前：Continue (処理続行)
変更後：マクロ終了確認ダイアログを表示する

**Comment by nmaya** [comment]
- 変更前・変更後というのは、このissueの提案ですか？
- 変更後の動作が妥当なのは、過去の Tera Term の動作がそうだからですか？
- だとしたら、いつからおかしくなっていましたか？

**Comment by nmaya** [comment]
4.108 で動作を確認しました。「×ボタン押下」も「ESCキー押下」も動作は「処理続行」でした。

> "x"ボタン押下の動作は処理続行より処理停止が適切と思われました

確かに停止が適切な気がしますが、今までずっと「処理続行」の動作をしています。
そのつもりで業務に使っているような人もいると思いますが、アップデートしたら突然「今までと同じ操作をしたのに今までと違う動作をする」ことになります。
変更履歴に書くとはいえ、安全上の理由ではなく「そのほうがよさそうに思える」という理由で変えていいものか、考えてしまいます。

**Comment by hkanou** [comment]
>4.108 で動作を確認しました。「×ボタン押下」も「ESCキー押下」も動作は「処理続行」でした。

確認頂きましてありがとうございます。
4.63(2009/7/5版)も「×ボタン押下」と「ESCキー押下」の動作は「処理続行」でした。

下記のどちらが良いか決めづらいです。
1. 修正した場合
   「処理続行」に慣れていらっしゃる方にとっては、今までと動作が変わって困惑
2. 修正しない場合
   新しく使い始めた方にとっては、想定と異なる動作で困惑

私自身はエラーダイアログが表示されて「xボタン押下」するケースは少なく、#277 の動作確認で初めてに気づきました。せっかくなので修正したいなと思いましたが、2009年からの動作でissueも無ければ無理に修正しなくても良いかもしれませんね。

**Comment by nmaya** [comment]
4.108 の動作を確認したのは、5 になったときに動作が変わったのかもしれない、と思ったからです。
4から5で変化はありませんでした。

2.3 で確認しましたが、同じ動作でした。
1.4 で確認しましたが、これも同じ動作でした。
16bit のときから一貫してこの動作のようです。

**Comment by nmaya** [comment]
ありがとうございました。
