### ISSUE TITLE
Webサイトのオンラインマニュアルにライブラリのライセンスファイルをコピーする

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#35]
### TODO
- [ ]  TeraTermProject/TeraTermProject.github.io リポジトリへ反映するスクリプトの修正

**Comment by zmatsuo** [comment]
自動的にファイルを追加するようにしました。

**Comment by nmaya** [comment]
[wiki:ライブラリバージョンアップ時の変更箇所](https://github.com/TeraTermProject/teraterm/wiki/Update-library) に手順を書き加えました
