### ISSUE TITLE
Additional Settings: Terminal と Window のタブ名

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#352]
（内容的には #84 の関連ですが、軽微なトピックなので別立てにしておきます）

デフォルトのタブ名が English.lng と不一致で、不当に長いです。
おそらく「従来のダイアログのタイトルを持ってきてそのまま」なのだろうと推測します。

[term_pp.cpp の L"Tera Term: Terminal setup"](https://github.com/TeraTermProject/teraterm/blame/89a46bd13b89cd0eb846845540539ff439c6e3c7/teraterm/teraterm/term_pp.cpp#L291) を単に `Terminal` にして
[win_pp.cpp の L"Tera Term: Terminal win..."](https://github.com/TeraTermProject/teraterm/blame/89a46bd13b89cd0eb846845540539ff439c6e3c7/teraterm/teraterm/win_pp.cpp#L563) を単に `Window` にしていただけると良いでしょう。

**Comment by zmatsuo** [comment]
修正しました。
