### ISSUE TITLE
YmodemLog のドキュメント

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#357]
この内容で「ソースコード解説」を見なければならない、というのは難しすぎるでしょう。

TODO

- YmodemLog について追記
  - setup/teraterm.html
  - setup/teraterm-trans.html

----
Please refer to the following URL
https://teratermproject.github.io/manual/5/en/reference/sourcecode.html#xyzmodem

TERATERM.INI
```
YmodemLog=on
```

_Originally posted by @zmatsuo in https://github.com/TeraTermProject/teraterm/issues/351#issuecomment-2379725442_

**Comment by hkanou** [comment]
6b84850 「Tera Term 設定ファイルの全項目一覧」に YmodemLog の説明へのリンクを追加する PR をお送りさせて頂きました。

**Comment by nmaya** [comment]
> YmodemLog の説明へのリンクを追加する PR

ありがとうございます。マージしました。

PR は #357-ymodem_doc の変更に対する追加修正でした。ソース的な依存関係はありませんでしたが、内容的な依存関係がありました。
hkanou/hkanou_#357 ブランチは main からのブランチだったようですが、このようなときは #357-ymodem_doc からのブランチのほうがいいかもしれません。

**Comment by hkanou** [comment]
> PR は https://github.com/TeraTermProject/teraterm/issues/357-ymodem_doc の変更に対する追加修正でした。ソース的な依存関係はありませんでしたが、内容的な依存関係がありました。
hkanou/hkanou_#357 ブランチは main からのブランチだったようですが、このようなときは https://github.com/TeraTermProject/teraterm/issues/357-ymodem_doc からのブランチのほうがいいかもしれません。

おっしゃるとおりでした。
https://github.com/TeraTermProject/teraterm/issues/357-ymodem_doc からのブランチが良かったです、気をつけます。
