### ISSUE TITLE
日本語ファイル名のZMODEMでアプリケーションエラー

### ISSUE THREAD

**Issue by ttdoda** [TeraTermProject/teraterm#36]
## 概要
ファイル名に日本語を含むファイルをZMODEMで受信すると、Tera Termがアプリケーションエラーで落ちる。

## 再現手順
接続先ホストにあらかじめlrzszをインストールしておく
```
echo aaa > ほげ.txt
sz ほげ.txt
```
`ZmodemAuto`が`off`の場合(デフォルト)はメニューから以下を選ぶ
[ファイル]-[転送]-[ZMODEM]-[受信]

## バージョン
5.0で発生。
4.107では落ちないが受信したファイルの名前が文字化けする。

**Comment by zmatsuo** [comment]
マージしました。クローズします。
