### ISSUE TITLE
XMODEM と ZMODEM のマニュアル修正(英語版に日本語版の記載を反映)

### ISSUE THREAD

**Issue by hkanou** [TeraTermProject/teraterm#360]
XMODEM と ZMODEM の英語版マニュアルに、ログ取得のヒントへのリンクの記載が漏れています。
(issue起票後、英語版マニュアルに日本語版の記載を反映する PR をお送りさせて頂きます)

例 XMODEMの場合
「どうしても正常に転送できない場合は、ホスト側の XMODEM コマンドを正しく設定および使用していることを確認した上で、XMODEM のログを取り、作者に送ってください。
参考: 中間ホストを経由してホストに接続した場合のファイル転送」

情報ありがとうございます > @ttdoda さん

**Comment by nmaya** [comment]
ありがとうございます。マージしました。
