### ISSUE TITLE
com0com のポートを認識しない

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#365]
これは workaround で、別に対策が必要？
https://x.com/ttdoda/status/1843684376284147743

**Comment by zmatsuo** [comment]
調べます。

解決できれば #209 も解決するのではないかと思います。

**Comment by zmatsuo** [comment]
解決できそうです。

com0com独自のシリアルポート?(Ports classではないポート)のとき、
"COM4" のような伝統的なシリアルポートデバイス名以外、
例えば"TERATERM"などにも設定できます。

Tera Term内部では "COM%d" に決め打ちしている箇所があるかもしれないので、
まずは、Ports classではないポート伝統的なシリアルポートデバイス名に
対応することを目指してみます。

**Comment by zmatsuo** [comment]
com0com の Ports classではない
"COM%d"のデバイス名のシリアルポートを
選択できるようになりました。

検出部分(comportinfo.cpp)内では
"COM%d"以外も検出できています。
現在はリストせずに捨てています。
Tera Term のシリアル選択が対応できれば
com0comの全てのデバイス名がオープンできるようになる見込みです。

com0comのデバイスクラス(デバイスの分類)が
普通のシリアル(Port class)とは異なっていて
修正前は検出することができていませんでした。

#209 の egg timer も特別なデバイスなのかもしれません。
手もとにARDUINOがあったので試してみたところ
普通のシリアルで Tera Term から使えているようでした。

ビルドできずバタバタ修正しました。
ビルドできていると思います。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50786506/artifacts

**Comment by nmaya** [comment]
ありがとうございます。
use Ports class が off でも認識されることを確認しました。

**Comment by nmaya** [comment]
00ffde52cc7b7ba4350ba941bd31f42c00d81dae ですが、リンクライブラリの追加はこれまでプロジェクトの「追加の依存ファイル」（vcxproj の AdditionalDependencies）に追加しています。
特に理由がなければ、一貫性を保つようにしてもらえるでしょうか。

**Comment by zmatsuo** [comment]
compat_win.cpp に _SetupDiGetDevicePropertyW() を追加したのですが、
 (Windows-7 以前でも動作する SetupDiGetDevicePropertyW() です)
この関数,オブジェクトファイルを含む common_static.lib を
リンクしている他のプロジェクトでも
setupapi.lib をリンクが必要となってしまいました。

_SetupDiGetDevicePropertyW() を使用していないプロジェクトなら
リンク時 setupapi.lib なくてもいいのではと思うのですが
必要となります。

プラグインなど全てに
追加の依存ファイル setupapi.lib を追加する必要があります。
ちょっと大変なのでオブジェクトに埋め込みました。

setupapi.lib が必要なライブラリを例えば common_setupapi.lib に
分ける方法もあると思います。

**Comment by nmaya** [comment]
> SetupDiGetDevicePropertyW()
> プラグインなど

ありがとうございます。
理由がわかりましたので、ソースのコメントを追加しておきました。

**Comment by zmatsuo** [comment]
手もとにモデムデバイスがないので確認はできていませんが
Windows Vistaから7以前の時、
モデムデバイスが検出できなくなる不具合があったので修正しました。 a1739221fc10f30ff346620b6cc23404883f9f4d
