### ISSUE TITLE
TTXChangeFontSize が動作しなくなった

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#366]
## 概要

main ブランチの commit fbf9a38fea6861f311197e4cd6e0adbcc8035134 以降、TTXChangeFontSize が動作しません。

## 再現方法

[TTXChangeFontSize](https://osdn.net/users/doda/pf/TTXChangeFontSize/wiki/FrontPage) を[用意](https://osdn.net/projects/ttssh2/ticket/45005#comment:1412:45005:1657206632)しておきます。

dcda4abad12f9a1912eac016ee44e9d246a39ea9 を checkout してビルドし、TTXChangeFontSize.dll を配置して起動します。
TTXChangeFontSize は設定したとおりに動作します。

fbf9a38fea6861f311197e4cd6e0adbcc8035134 を checkout してビルドし、TTXChangeFontSize.dll を配置して起動します。
TTXChangeFontSize は動作しません。

## 期待の動作

副作用により後方互換性が失われた状態と推察します。
従来通り動作することを期待します。

**Comment by zmatsuo** [comment]
レポートありがとうございます。

動作しないことを確認しました。
修正を検討します。

**Comment by zmatsuo** [comment]
対策しました。
バイナリを作成しました。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50828166/artifacts

試してみてください。

**Comment by hkanou** [comment]
> 対策しました。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50828166/artifacts

TTXChangeFontSize.dll が従来と同じように動作することを確認いたしました。
TTXResizeMenu.dll、TTXResizeWin.dll の動作も問題ありませんでした。
対応頂きありがとうございます。

**Comment by zmatsuo** [comment]
ありがとうございます。
mainにマージしました。

**Comment by zmatsuo** [comment]
クローズします。
