### ISSUE TITLE
Cannot write log file when connection is re-connected

### ISSUE THREAD

**Issue by fatsmurf** [TeraTermProject/teraterm#370]
OS: WIndows 11
TeraTerm version: 5.3 x86 (Git 5b83fb6f7)
Steps to re-produce:
. configure TeraTerm to start with Auto start logging enabled, or just enable logging.
. start TeraTerm
. connect to a host or serial port
. disconnect from the host or serial port
. connect to a host or serial port again.
---> pop-up appears with the message: "Cannot write log file. xxxxx"
However the log file seems to continue to be updated.

There are other cases when logging is stopped and restarted with another file name., the pop-up message appears with old log file name.

**Comment by nmaya** [comment]
It seems that this issue same as #323.
Does this issue occur with #323's snapshot?

**Comment by fatsmurf** [comment]
Yes, it looks the same. Sorry!
i have not test with #323 snapshot.
Thanks.
