### ISSUE TITLE
SSHv2 Cisco and MAC algorithm 

### ISSUE THREAD

**Issue by shinji7800** [TeraTermProject/teraterm#373]
Hello there, 

since I updated Cisco switch, only hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com are available 

before upgrade : hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com, hmac-sha2-256,hmac-sha2-512,hmac-sha1 was compatible. 

there Is a way to add missing algo in teraterm ? 

thanks for your responses 

best regards

**Comment by nmaya** [comment]
Hi,

SSH client cannot use MAC algorithms which is not supported by remote server.
Tera Term (TTSSH) supports hmac-sha2-256-etm@openssh.com and hmac-sha2-512-etm@openssh.com.
Server (Cisco) seems to decided to drop support hmac-sha2-256,hmac-sha2-512 and hmac-sha1 MAC algorithm by default.
Does Tera Term have to add the MAC algorithms? What are you asking of us?

Thanks,

**Comment by shinji7800** [comment]
Hello 

my bad my shortcuts still use teraterm 4.96. but if I force to use teraterm 5.3 it works ! 

thanks for your time and your works 

best regards
