### ISSUE TITLE
INIファイルのパス

### ISSUE THREAD

**Issue by toyo400** [TeraTermProject/teraterm#374]
TTSSH(3.0)以上を使用したいため、teraterm5を使用したいのですが、
INIファイルのパスが%APPDATA%\teraterm5となってしまったため、
共用で使用しているサーバにおいて、各ユーザでINIファイルを編集できる状態になりました。
ログ取得の強制等、制限をかけたいので、これまで通りプログラムディレクトリを指定できることを希望します。

もしくはteraterm4系でTTSHのみバージョンアップする事は可能でしょうか。

**Comment by nmaya** [comment]
> これまで通りプログラムディレクトリを指定できること

ポータブル版のためにある仕組みですが、インストールディレクトリに portable.ini ファイルを置くと `%APPDATA%\teraterm5` ではなく [`exeファイルのあるフォルダ` が使用される](https://teratermproject.github.io/manual/5/ja/setup/folder.html)ようになります。
その場合はこれまで通り UAC/VitrualStore の影響を受けるため、ログの保存先が C:\Users\\<ユーザー名>\AppData\Local\VirtualStore\Program Files (x86)\teraterm5\log のようになると思いますのでご注意ください。

> teraterm4系でTTSHのみバージョンアップする事は可能でしょうか。

Tera Term 4.x と TTSSH 3.x を組み合わせることはできません。
