### ISSUE TITLE
Skip "Send File dialog" to "Send File"

### ISSUE THREAD

**Issue by AlexanderAdelAU** [TeraTermProject/teraterm#375]
I have just loaded v5.3 and now have to go through 3 dialogs to send a file and have to navigate to the source directory each time if I click on "Send in same way as Tera Term 4".   If this has to be done can you at least allow save settings to try and avoid this un-necessary set of Dialogs?

TODO:
- [x] about number of operations, this issue
- [x] use ts.FileDir for send file, moved to #379
- [x] memorize Send File dialog options, moved to #380

**Comment by nmaya** [comment]
Hi,

> 3 dialogs

Tera Term 5 added one new dialog between "File - Send file" menu and file selection dialog to select transfer options.

![sendfileoption](https://github.com/user-attachments/assets/b449afbd-6c12-4f1c-a0a8-617401029be6)

What is **three** dialogs you said?

> have to navigate to the source directory each time

In Tera Term 4:
Source directory (default dir of the file selection dialog) is of "Send file" is seems "File dir" (internal ts.FileDir), which is able to change "File - Change direcotry" menu.
User can fix it.

In Tera Term 5:
Remembering source directory (default dir of the file selection dialog) is not depends on "same as Tera Term 4" is on or off.
It is not controlled by app. Windows remembers the directory of latest selected file, and is used in next time.
User can not fix it.

> Send in same way as Tera Term 4

It changes "[sending method](https://teratermproject.github.io/manual/5/en/menu/file-sendfile.html)", not selection dialog.

We will discuss about this issue.
Thanks.

**Comment by nmaya** [comment]
@zmatsuo
修正の前に、この問題の経緯・修正が必要か・修正点をまとめる確認をしています。
まとまるまで修正を始めなくてよいです。

1. Tera Term 4 では "Send File" に ts.FileDir ("File - Change directory" で指定できる) が指定されていますが、Tera Term 5 では lpstrInitialDir がないため、Windows にお任せになっているように見えます。現在この動作であることに間違いないですか？
2. Tera Term 5 でこのように変更された理由はありますか？
3. Tera Term 5 で lpstrInitialDir を ts.FileDir に修正すると Tera Term 4 と同じ動作になりますが、上記 2. の「変更した理由」を覆すことになります。覆すだけのメリットがありますか？
4. この issue では "Send file" について言われていますが、その他のプロトコルでのファイル転送の "送信" でも同じ動作でしょうか。同様の修正をしてもよいでしょうか。
5. Tera Term 4 では Current directory だった ts.FileDir が、[設定UI](https://teratermproject.github.io/manual/5/ja/menu/setup-additional-general.html#DownloadFolder)、[フォルダの解説](https://teratermproject.github.io/manual/5/ja/setup/folder.html)で download folder となっています。termpro.exe のインスタンスのカレントディレクトリと紛らわしいために改名したのでしたっけ？
6. ts.FileDir は[ヘルプ](https://teratermproject.github.io/manual/5/ja/menu/setup-additional-general.html#DownloadFolder)で「ファイル転送のためのディレクトリ」と説明されていますが、項目名が「download folder」となっていて、ファイルの送信について全く扱われていません。上記 2. の理由で「ダウンロードのみ」に使うことにしたのでこの命名なのでしょうか？
7. 上記 3. の修正を入れ receive / send の両方に使うのであれば、「ダウンロードフォルダかつ送信ファイル選択のデフォルトフォルダ」なので、「download folder」ではない別の名前がふさわしいと思います。

**Comment by AlexanderAdelAU** [comment]
Thankyou for your response.   I was misleading when I said 3 dialogs, I should have said "multiple actions"   In Tera Term 4 I always went straight to the download directory and because I do this very frequently it was simple.  Now with TT5 I have multiple issues, I  have to click on send as TT4 checkbox, (I can't fix or save this, if I do I have to select the default directory again - which is annoying) So, that is two clicks, now if I am lucky I am in the default directory and can send.   I suppose the issue is:
1.  The purpose of the command is to Send A File - so you should go straight to the file select, you should not go to a interim dialog
2. Whether you want to send using TT4 or TT5 should be in the settings - just like you could change the serial data rate through the settings - you should not need to select it each time. 

When you are transferring a lot of files TT5 is just about unusable for me.   I have both versions installed now and have defaulted to TT4 for the time being.

Thanks

Alex

**Comment by zmatsuo** [comment]
> 1. Tera Term 4 では "Send File" に ts.FileDir ("File - Change directory" で指定できる) が指定されていますが、Tera Term 5 では lpstrInitialDir がないため、Windows にお任せになっているように見えます。現在この動作であることに間違いないですか？
> 2. Tera Term 5 でこのように変更された理由はありますか？
> 3. Tera Term 5 で lpstrInitialDir を ts.FileDir に修正すると Tera Term 4 と同じ動作になりますが、上記 2. の「変更した理由」を覆すことになります。覆すだけのメリットがありますか？
> 4. この issue では "Send file" について言われていますが、その他のプロトコルでのファイル転送の "送信" でも同じ動作でしょうか。同様の修正をしてもよいでしょうか。
> 5. Tera Term 4 では Current directory だった ts.FileDir が、設定UI、フォルダの解説で download folder となっています。termpro.exe のインスタンスのカレントディレクトリと紛らわしいために改名したのでしたっけ？
> 6. ts.FileDir はヘルプで「ファイル転送のためのディレクトリ」と説明されていますが、項目名が「download folder」となっていて、ファイルの送信について全く扱われていません。上記 2. の理由で「ダウンロードのみ」に使うことにしたのでこの命名なのでしょうか？

CUIだと意識しますが、GUI プログラムだとカレントディレクトリは意識しないのが一般的だと思います。
Tera Term 5 では、Tera Term 4 のカレントディレクトリをなくして、
ホームや動作ログなどすべて特定のフォルダとなるよう意図しています。
ダウンロードディレクトリ=カレントディレクトリとして扱うと良いだろうと考えていました。
アップロードするファイルの置いてあるデフォルトフォルダは考えていませんでした。

> 7. 上記 3. の修正を入れ receive / send の両方に使うのであれば、「ダウンロードフォルダかつ送信ファイル選択のデフォルトフォルダ」なので、「download folder」ではない別の名前がふさわしいと思います。

そう思います。
ファイル送受信フォルダ でしょうか。(なんだかしっくりしない気がします)

**Comment by nmaya** [comment]
@AlexanderAdelAU 
Now I understand that increased number of operations to select a send file is this issue.

before:

1. "File - Send file" - open FileSelect dialog (file dir. it is able to specify in advance by user)
2. Select a file - file is sent

after:

1. "File - Send file" - open "Send file" dialog
2. push "..." button - open FileSelect dialog (some dir)
3. (change directory)
4. Select a file - back to "Send file" dialog
5. push "OK" button - file is sent

**Comment by nmaya** [comment]
@zmatsuo 

> GUI プログラムだとカレントディレクトリは意識しないのが一般的だと思います。
> アップロードするファイルの置いてあるデフォルトフォルダは考えていませんでした。

[マクロ](https://teratermproject.github.io/manual/4/ja/macro/command/changedir.html)がありますので、考慮が必要ですね。

> ホームや動作ログなどすべて特定のフォルダとなるよう意図しています。

プログラム直下ではなくなり、かつ用途ごとに分離してくださいましたね。そうした理由はよく分かっています。

> ファイル送受信フォルダ でしょうか。(なんだかしっくりしない気がします)

ts.FileDir ですので、ファイル送受信用フォルダ・ファイル転送用フォルダ あたりでしょうか？

**Comment by nmaya** [comment]
moved some topics to sub issue, #379 and #380.

**Comment by nmaya** [comment]
@zmatsuo 
この issue は「File Send ダイアログ」が追加され、操作の手数が増えたことが問題とされています。
Tera Term 4 のように「いきなり GetOpenFileName() が出てきてファイルを選択するだけ」が求められています。

「File Send ダイアログ」が追加された理由「GetOpenFileName() の "Binary" を選択するチェックボックスを維持したかったが、拡張テンプレートを使うのをやめた」「その他のオプションも選択できるようにした」というのは理解しているつもりです。
これらのオプションの指定はあらかじめしておいたものを使い、ファイルの選択だけをしたいというのが起案者の要望です。

「File Send ダイアログ」の廃止はやりすぎな気がするので、「File Send ダイアログ」をスキップするオプションを追加して希望されている操作を実現することはよいと思いますか？

**Comment by zmatsuo** [comment]
> 「File Send ダイアログ」をスキップするオプションを追加して希望されている操作を実現することはよいと思いますか？

こんな案はどうでしょうか?

- "File - Send file" で現在の動作
- Shift(or Ctrl) + "File - Send file" で「File Send ダイアログ」をスキップしてファイル選択から送信
  - ただし、初回パラメータ設定(#380)を行った後利用できるようになる

ファイルをDropして送信も合わせて考えると、
デフォルトファイル送信方法を設定できるほうがよさそうですね。

ファイルの送信は、hexやmot等を送るのに使っていて、
同じファイル名の別ファイルを何度も送信するのではないでしょうか

実は送信ファイル名のヒストリがあるとうれしくないでしょうか? #236

**Comment by nmaya** [comment]
> Shift(or Ctrl) + "File - Send file"
> パラメータ設定を行った後利用できる

見えないコマンドは隠し機能に見えるので好みません。

> 実は送信ファイル名のヒストリ

起案者の意図がわからないので、起案者にとって有用かわかりません。
また、ダイアログには実装できるものの GetOpenFileName にはヒストリを追加できないですよね。
これは別の話です。

**Comment by AlexanderAdelAU** [comment]
> > Shift(or Ctrl) + "File - Send file" 
> > Available after parameter setting
> 
> I don't like invisible commands because they seem like hidden features.
> 


Agree.  Invisible commands don't address the concern for the casual user who believe that the required functionality is not present.  Advanced features should be "added" by the user, when appropriate and indeed required.  The settings disalogue with a check box is the best way of "adding" the functionality.

**Comment by zmatsuo** [comment]
> 「File Send ダイアログ」をスキップするオプションを追加

「スキップする」チェックボックスのチェックを入れておくと、
次にメニューを選んだ時、「File Send ダイアログ」ではなく
ファイル選択がでる、いう動作ですね。

このとき、設定を変更したくなったらどうやって再度ダイアログを出せばよいでしょう?

送信ファイル名のヒストリはダイアログに
実装すれば良いと思っていました。
フォルダ名を入力した状態だとファイル選択でそのフォルダが開くと便利そうです。

What do you think of filename history?
How do you use "Send File" ? @AlexanderAdelAU

**Comment by nmaya** [comment]
> このとき、設定を変更したくなったらどうやって再度ダイアログを出せばよいでしょう?

UIで設定できずINIを直接編集する特別オプションか、Additional Setting の中のどこかのタブにチェックボックスを作るイメージです。
「スキップする」チェックボックスを「File Send ダイアログ」に出すイメージはありません。よくわからずチェックして進んでしまうと、戻し方がわからなくなるからです。

**Comment by zmatsuo** [comment]
#380 の修正の中に入れ込んでしまいました。
Ctrl + "File - Send file" も入れてみました。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/51061618/artifacts

**Comment by nmaya** [comment]
issue #380 のためのコミット 9799f7db07adca4538a9aca87d9b27c530a37e32 に、この issue の修正が含まれました。
変更履歴は書かれていません。

**Comment by nmaya** [comment]
修正ありがとうございます。

- ダイアログに UI パーツが無い skip_dialog が受け渡しされている
  - この issue で、ダイアログでの選択は不要と判断されたと思っています
- 「Ctrl + "File - Send file"」
  - この issue で、隠しコマンドのような機能は望ましくないと判断されたと思っています
    - オプションができたため「直接 GetOpenFileName() を開く唯一の方法」ではなくなったので、隠しコマンドではなくなりました
  - Ctrl キーを押したときとそうでないときで "Send file" をクリックした結果が異なると、バグのように見えるかもしれません
    - setup/teraterm-trans.html の説明 `CTRLキーを押しながら[File]-[Send file...]を選択することで、この設定のon/offを入れ替えた動作を行うことができます。` の説明を、[メニュー側](https://teratermproject.github.io/manual/5/ja/menu/file.html)にも入れていただけるでしょうか？

**Comment by zmatsuo** [comment]
修正を入れました。375-skip_sendfile_dialog ブランチ (b58a28d5c92676fb621026786c0ca12c52d43392) です。

> メニュー側にも入れていただけるでしょうか？

入れてみました。pushした内容でどうでしょうか?

**Comment by nmaya** [comment]
> doc/ja/html/menu/file.html

```
- ファイルを送信します。
+ ファイルを送信します。"Send file" ダイアログを表示します。
```

このうえで、SendfileSkipOptionDialog が off のときはいまの記述で正しいです。
SendfileSkipOptionDialog が onのときは「CTRLキーを押しながらをこのメニューを選択すると...」の部分が逆転すると思います。

**Comment by zmatsuo** [comment]
説明を修正しました。
