### ISSUE TITLE
ログファイル選択時に不要な上書き確認ダイアログが表示される

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#376]
## 概要
既存のファイルを「...」ボタンからログファイルとして選択する際、
追記したい場合であっても「上書きしますか？」のダイアログに「はい」を選択する必要があります。

「上書きしますか？」のダイアログに「はい」と応答するには
ファイルが破壊される可能性を覚悟する必要があるので、抵抗があります。

また、「上書きしますか？」のダイアログに「はい」を応答したとしても
その後に Log ダイアログで「New / Overwrite」を選択して OK しない限り上書きされないので、
メッセージと動作が食い違っていることになり、混乱します。

## 再現手順１
1. デスクトップに dummy.log ファイルを作成します。
1. Setup -> Log で Log ダイアログを出します。
1. Filename の右側の「...」ボタンで Tera Term：Log ダイアログを出します。
1. デスクトップに作成済の dummy.log ファイルを選択して「保存」します。
1. 「名前を付けて保存の確認」ダイアログが表示されます。
1. ファイルを指定後に Write mode 指定するつもりだったとしても上書きに同意しなければならず、混乱します。

## 再現手順２
1. Setup -> Log で Log ダイアログを出します。
1. 既存ファイルを指定し、Write mode で「Append」を選択します。
1. Filename の右側の「...」ボタンで Tera Term：Log ダイアログを出します。
1. 既存ファイルを選択して「保存」します。
1. 「名前を付けて保存の確認」ダイアログが表示されます。
1. Write mode 指定を Append にしてあっても上書きに同意しなければならず、混乱します。

## 期待の動作
「Tera Term: Log」ダイアログでファイルを選択する際は、
「名前を付けて保存の確認」ダイアログが表示されないことが妥当です。

**Comment by nmaya** [comment]
提案ありがとうございます。
ソースを追いかけられていないのですが、この関数は "Setup - Save setup" のような「上書き確認が必要な GetSaveFileName()」の呼び出しに使われていることはありませんか？

**Comment by sempreff** [comment]
呼び出し側で OVERWRITEPROMPT を未設定の場合のみ未設定になれば良いと考えています。
（そのようにしたつもりでしたが、誤っておりましたので修正いたしました）

**Comment by nmaya** [comment]
わかりました。確認ありがとうございます。
