### ISSUE TITLE
ts.FileDir を送信にも使う

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#379]
Tera Term 4 の「現在のディレクトリ」が、ファイルの「ダウンロード」にしか用いられておらず、送信には使われていない。
この件で対応すべき箇所を検討する。

- 送信するファイルの選択時に使用する
  - File - Kermit - Send
  - File - XMODEM - Send ... 最後に選択したのと違うフォルダで表示された。いまどうなってる？
  - File - YMODEM - Send ... 〃
  - File - ZMODEM - Send ... 〃
  - File - B-Plus - Send
  - File - Quick VAN - Send
  - File - Send file - ...
  - マクロで選択したとき ... いまどうなってる？
- UI表記
  - Setup - Additional settings - General - Download Folder -> 変更
  - Setup - Setup directory - Download -> 変更
- ドキュメント
  - menu/setup-additional-general.html#DownloadFolder
  - setup/folder.html
  - macro/command/changedir.html

origin: #375

## TODO
- [x] 送信ファイル選択の GetOpenFileName() の初期値（決定）
  - プロトコルでの送信
  - Send File
  - 変更履歴
- マクロコマンドでフルパスでなかったときの扱い（決定）
  - プロトコルでの送信
  - Send File
  - ドキュメント
  - 変更履歴
- [x] 「ダウンロードフォルダ」→「ファイル転送用フォルダ」（決定）
  - UI表記
  - ドキュメント

**Comment by nmaya** [comment]
@zmatsuo
修正の前に、この問題の経緯・修正が必要か・修正点をまとめる確認をしています。
まとまるまで修正を始めなくてよいです。

1. Tera Term 4 では "Send File" に ts.FileDir ("File - Change directory" で指定できる) が指定されていますが、Tera Term 5 では lpstrInitialDir がないため、Windows にお任せになっているように見えます。現在この動作であることに間違いないですか？
2. Tera Term 5 でこのように変更された理由はありますか？
3. Tera Term 5 で lpstrInitialDir を ts.FileDir に修正すると Tera Term 4 と同じ動作になりますが、上記 2. の「変更した理由」を覆すことになります。覆すだけのメリットがありますか？
4. この issue では "Send file" について言われていますが、その他のプロトコルでのファイル転送の "送信" でも同じ動作でしょうか。同様の修正をしてもよいでしょうか。
5. Tera Term 4 では Current directory だった ts.FileDir が、[設定UI](https://teratermproject.github.io/manual/5/ja/menu/setup-additional-general.html#DownloadFolder)、[フォルダの解説](https://teratermproject.github.io/manual/5/ja/setup/folder.html)で download folder となっています。termpro.exe のインスタンスのカレントディレクトリと紛らわしいために改名したのでしたっけ？
6. ts.FileDir は[ヘルプ](https://teratermproject.github.io/manual/5/ja/menu/setup-additional-general.html#DownloadFolder)で「ファイル転送のためのディレクトリ」と説明されていますが、項目名が「download folder」となっていて、ファイルの送信について全く扱われていません。上記 2. の理由で「ダウンロードのみ」に使うことにしたのでこの命名なのでしょうか？
7. 上記 3. の修正を入れ receive / send の両方に使うのであれば、「ダウンロードフォルダかつ送信ファイル選択のデフォルトフォルダ」なので、「download folder」ではない別の名前がふさわしいと思います。

_Originally posted by @nmaya in https://github.com/TeraTermProject/teraterm/issues/375#issuecomment-2424285139_

**Comment by nmaya** [comment]
> 1. Tera Term 4 では "Send File" に ts.FileDir ("File - Change directory" で指定できる) が指定されていますが、Tera Term 5 では lpstrInitialDir がないため、Windows にお任せになっているように見えます。現在この動作であることに間違いないですか？
> 2. Tera Term 5 でこのように変更された理由はありますか？
> 3. Tera Term 5 で lpstrInitialDir を ts.FileDir に修正すると Tera Term 4 と同じ動作になりますが、上記 2. の「変更した理由」を覆すことになります。覆すだけのメリットがありますか？
> 4. この issue では "Send file" について言われていますが、その他のプロトコルでのファイル転送の "送信" でも同じ動作でしょうか。同様の修正をしてもよいでしょうか。
> 5. Tera Term 4 では Current directory だった ts.FileDir が、設定UI、フォルダの解説で download folder となっています。termpro.exe のインスタンスのカレントディレクトリと紛らわしいために改名したのでしたっけ？
> 6. ts.FileDir はヘルプで「ファイル転送のためのディレクトリ」と説明されていますが、項目名が「download folder」となっていて、ファイルの送信について全く扱われていません。上記 2. の理由で「ダウンロードのみ」に使うことにしたのでこの命名なのでしょうか？

CUIだと意識しますが、GUI プログラムだとカレントディレクトリは意識しないのが一般的だと思います。
Tera Term 5 では、Tera Term 4 のカレントディレクトリをなくして、
ホームや動作ログなどすべて特定のフォルダとなるよう意図しています。
ダウンロードディレクトリ=カレントディレクトリとして扱うと良いだろうと考えていました。
アップロードするファイルの置いてあるデフォルトフォルダは考えていませんでした。

> 7. 上記 3. の修正を入れ receive / send の両方に使うのであれば、「ダウンロードフォルダかつ送信ファイル選択のデフォルトフォルダ」なので、「download folder」ではない別の名前がふさわしいと思います。

そう思います。
ファイル送受信フォルダ でしょうか。(なんだかしっくりしない気がします)

_Originally posted by @zmatsuo in https://github.com/TeraTermProject/teraterm/issues/375#issuecomment-2424837899_

**Comment by nmaya** [comment]
@zmatsuo 

> GUI プログラムだとカレントディレクトリは意識しないのが一般的だと思います。
> アップロードするファイルの置いてあるデフォルトフォルダは考えていませんでした。

[マクロ](https://teratermproject.github.io/manual/4/ja/macro/command/changedir.html)がありますので、考慮が必要ですね。

> ホームや動作ログなどすべて特定のフォルダとなるよう意図しています。

プログラム直下ではなくなり、かつ用途ごとに分離してくださいましたね。そうした理由はよく分かっています。

> ファイル送受信フォルダ でしょうか。(なんだかしっくりしない気がします)

ts.FileDir ですので、ファイル送受信用フォルダ・ファイル転送用フォルダ あたりでしょうか？

_Originally posted by @nmaya in https://github.com/TeraTermProject/teraterm/issues/375#issuecomment-2425245808_

**Comment by zmatsuo** [comment]
ts.FileDir を送信にも使えばよさそうです。

送信、受信フォルダを分けたい
送信フォルダはOS任せがよい、とリクエストが出てきたら
送受フォルダを分けて、送信フォルダが未設定の時はOS任せになるとか
良いかもしれません。

**Comment by nmaya** [comment]
#### 送信時の動き
|  | プロトコル |  Send File |
| -- | -- | -- |
| メニュー（初期ディレクトリ） | *1 | *2 |
| マクロ（フルパスでないファイル名を指定したとき） | *3 | *4 |

*1 今の main では GetDownloadDir() を使っていて、ts->FileDirW を展開していました。
https://github.com/TeraTermProject/teraterm/blob/bd1a824a31bcfe8097643a49bf21fdc3501581f5/teraterm/teraterm/filesys_proto.cpp#L943
https://github.com/TeraTermProject/teraterm/blob/bd1a824a31bcfe8097643a49bf21fdc3501581f5/teraterm/common/ttlib_types.cpp#L47
動作は問題なさそうに見えます。
「変数名が CurDir が紛らわしい」「関数名 DownloadDir() も名前が正しくない」ので、表示名と同じようにネーミングだけは直したいです。

*2 これは上にあるように「FileDirW を使うように変更する」でいいと思います。

*3 マクロでプロトコルで送信
Tera Term 4 の動作を確認したところ、[ドキュメント](https://teratermproject.github.io/manual/4/ja/macro/command/changedir.html)の記述と異なり、「Tera Term の現在のディレクトリ」ではなく「ttermpro.exeのあるディレクトリ」（もしかして、=ttermpro.exe のインスタンスのカレントディレクトリ）を基準にしているようでした。
Tera Term 5 の動作を確認しましたが、ts.FileDirW や exe のところにファイルを置いてファイル名だけ指定して送信しても送信されず、どこを基準にしているかよくわかりませんでした。

*4 マクロで Send File
SendMemSendFileCom() から LoadFileWW() か LoadFileBinary() に行き、_wfopen_s() に行きます。もしかして「ttermpro.exe のインスタンスのカレントディレクトリ」になっているでしょうか？

*3,*4 ドキュメントの矛盾？
その1: 4,5 とも「Tera Term の現在のディレクトリを基準にする」と「changedirコマンドの影響を受けないため、絶対パスである必要がある」があります。どちらかが誤っているのではないでしょうか？
その2: 5のほうに「現在のディレクトリ」の記述が残っています。Tera Term 5 では「Tera Term の現在のディレクトリ」を変更する手段はなくなったはずなので、ユーザは「そういわれてもどうしようもできない」です。
[4のchangedir](https://teratermproject.github.io/manual/4/ja/macro/command/changedir.html), [5のchangedir](https://teratermproject.github.io/manual/5/ja/macro/command/changedir.html)
ドキュメントで「絶対パスでないときの動きは知らん」と言い切って「不定」でいいなら、動きを追わなくてもいいかもしれません。

**Comment by nmaya** [comment]
> メニューから（各プロトコル・SendFile とも）の初期ディレクトリをts.FileDirにすればok

そう思います。

> BPlusの送信

ありがとうございます。お願いします。

> > ts.FileDirW や exe のところにファイルを置いて

> Tera Term 4 と同じになる気がしますが
> ttermpro.exe のインスタンスのカレントディレクトリになっている

場所は違いました（Roaming\teraterm5 でした）が「ttermpro.exe プロセスのカレントディレクトリ」で、同じ動作でした。失礼しました。

> 通信コマンドで指定するファイル名が相対パスの場合

これは幾つか分岐点があると思います。

- 「マクロ（ttpmacro.exe）は Tera Term を操っているだけ」と考える
  - ttermpro.exe プロセスのカレントディレクトリを基準とする
  - ttermpro.exe の ts.FileDir を基準とする
- マクロ側でフルパスに解決する考え方の発想
  - マクロ（ttpmacro.exe）のプロセスのカレントディレクトリ（setdir のディレクトリ）を基準とする
  - マクロファイルのあるディレクトリを基準とする

もともと前者の設計思想だと思うので、あまり変えたくないです。
Tera Term 5 の本体側は「カレントディレクトリをなくす」という方向にしました。
これらをあわせて「（ttermpro.exe 側で）ts.FileDir を基準とする」のが妥当と思いますが、いかがでしょうか？

**Comment by nmaya** [comment]
ビルドかけなおしました。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50980282

**Comment by zmatsuo** [comment]
BPlusの送信だけ先に直しました。

> 「マクロ（ttpmacro.exe）は Tera Term を操っている」とする設計思想で
> 「（ttermpro.exe 側で）ts.FileDir を基準とする」のが妥当

了解です。その通りだと思います。

**Comment by nmaya** [comment]
UIからの選択を修正しました。
Send file では GetFileDir() の呼び出しに必要なので、単体の FileDir ではなく 大本の pts を渡すようにしました。問題あるようならご指摘ください。

**Comment by zmatsuo** [comment]
#380 で Sendfile Dialog の動作を見直しました。
Sendfile Dialog には初期フォルダ、初期ファイルも渡せるようにしました。
#379 用ブランチを伸ばす形で修正を入れました。

マクロの修正を調査します。

> #393 は少し思い当たるところがありますので一緒に調べます。
> #392 のファイル名を記憶するのは、#236 と一緒に解決できればと考え中です。

**Comment by nmaya** [comment]
この issue のためのブランチから #380 のためのブランチが作成され、#380 のためのブランチがマージされました。
この issue の範囲「マクロの修正」は行われないまま、main へマージされています。
pick するときは注意してください。

**Comment by zmatsuo** [comment]
マクロ関連を対応しました。

次の3タイプあります。

1. Tera Term から送信、Tera Term 側がファイル名指定
2. Tera Term が受信、Tera Term 側がファイル名指定
3. Tera Term が受信、送信元がファイル名を指定

Tera Term 側がファイル名指定するものは、
ファイル名が相対パスのときは ts.FileDir を使用するようにしました。

送信元がファイル名を指定するものは
従来から ts.FileDir(GetFileDir()) を使用しているのでそのままです。

マニュアルにリンクを追加したり説明を加えたりました。

指摘などあればお願いします。
特になければ英語版マニュアル、修正履歴を進めようと思います。

**Comment by nmaya** [comment]
ありがとうございます。大丈夫だと思います。
