### ISSUE TITLE
TTPmacro (TT 5.0) - issue with strjoin command

### ISSUE THREAD

**Issue by Dom-Out** [TeraTermProject/teraterm#38]
Hi,

I tried the TeraTerm 5.0 with ttpmacro script.

I found a problem using "strjoin" command. My script was working good with TeraTerm 4.106 but not working with TeraTerm 5.0.

If i used this example 
    groupmatchstr1 = "Hello"
    groupmatchstr2 = "Everybody"
    strjoin JoinData "" 2

The JoinData must be equals to "HelloEverybody" but not happening. Joindata is empty. 
If I want ot have the result of the command I need to use groupmatchstr2.

**Comment by zmatsuo** [comment]
strjoin command has been fixed.
https://teratermproject.github.io/manual/5/en/about/history.html#teraterm_5.1

Try a recent(latest) binary.
https://ci.appveyor.com/project/teraterm/github-main/history

**Comment by nmaya** [comment]
> strjoin command has been fixed.

Sorry, I forgot it was already fixed.
