### ISSUE TITLE
コマンドリファレンス内で表現されている(バージョン4.56以降)　のバージョンはどこを見ればいいのでしょうか？

### ISSUE THREAD

**Issue by edamamebutasann** [TeraTermProject/teraterm#385]
お世話になっています。
TTL コマンドリファレンス内で表現されている
(バージョン4.56以降)　等の ”バージョン”は、どこを確認すればいいのですか？
TeraTerm のウインドウの　ヘルプ-Tera Term について　の画面では、
現在の最新で Version 4.108(Git 70c5279)　と出てきます。
この番号ではないんでしょうか？
何処かのページに説明があれば教えていただきたいと思います。
お願いいたします。

**Comment by nmaya** [comment]
> TeraTerm のウインドウの　ヘルプ-Tera Term について　の画面で
> Version 4.108

そこに出ているバージョンが、今使っているバージョンです。

> この番号ではないんでしょうか？

どうしてこの番号が今使っているバージョンではないと思ったのでしょうか？

**Comment by edamamebutasann** [comment]
コメントありがとうございます。
以前もどなたかが質問されていて、しかし残念ながら失念してしまい、ここへ来たのですが、
記述がみつからないのでしつこく聞いてしまいました。
コマンドリファレンス内で表現されている(バージョン4.56以降) の 4.56 と、
TerTermの現最新バージョン 4.108
これは、　4.56 ＝ 4.056 と解釈するのでしょうか？
そうすると納得なのですが、これでよいのでしょうか？
稚拙な質問で申し訳ありません。

**Comment by nmaya** [comment]
> TerTermの現最新バージョン 4.108

[Release](https://github.com/TeraTermProject/teraterm/releases) にあるとおり、最新バージョンは 5.3 です。

> そうすると納得なのですが

[変更履歴](https://teratermproject.github.io/manual/4/ja/about/history.html) には、リリースされた順に日付とバージョン番号が書かれていますので、これでご納得いただけますか？

**Comment by edamamebutasann** [comment]
変更履歴を見てわかりました。過去を追っていくとわかりました。
ここまで説明していただけないとわからないなんて、情けない。
どうもありがとうございました。
