### ISSUE TITLE
つちよし(𠮷,U+20BB7)が表示できない

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#386]
![image](https://github.com/user-attachments/assets/288b7ed9-4226-4b45-8b4d-70faba7098eb)

**Comment by zmatsuo** [comment]
次の表示が正しくできるようになりました。
```
$ echo -e "\U20bb7"野家
𠮷野家
```

バイナリをビルドしています。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50894761/artifacts

**Comment by nmaya** [comment]
「𠮷」の表示をこちらでも確認しました。
![yoshi](https://github.com/user-attachments/assets/ea8288f8-7a2e-42ba-8273-ff4e1e7d59f5)

**Comment by zmatsuo** [comment]
クローズします。

**Comment by zmatsuo** [comment]
表示できていないとき、4キャラクタ出力されていました。

この文字は U+FFFD で不明な文字のときに表示される文字( [replacement character (Wikipedia,jp)](https://ja.wikipedia.org/wiki/%E7%89%B9%E6%AE%8A%E7%94%A8%E9%80%94%E6%96%87%E5%AD%97_(Unicode%E3%81%AE%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF)) )です。
何が表示されるかは選択したフォントによって異なりますが、
多くはひし形の中に"?"となっているようです。
("�" ←ブラウザのフォントによって表示が異なります)

最初の添付画像のフォントは [白源](https://github.com/yuru7/HackGen) です。

bash等では
```
echo -e "\UFFFD"
```
で確認できます。
文字幅は Ambiguous で 1または2cellになります。
