### ISSUE TITLE
Line at a time mode

### ISSUE THREAD

**Issue by davidbstanley** [TeraTermProject/teraterm#387]
P have had a real problem recently trying to get Tera Term to work with a remote system via Telnet.  We had previously been using Hyperterm which works fine but is problematic with newer Windows versions.  The issue with Tera Term was caused by the default 'Line at a time mode' setting being on.  Setting it to 'EnableLineMode=off' in TERATERM.ini resolved the issue.  My suggestion would be to give access to that setting in the Setup/Additional settings menu and document it.  It would have saved me a lot of time.

**Comment by nmaya** [comment]
Hi,

Thank you for your suggestion. Aleady [documented](https://teratermproject.github.io/manual/5/en/setup/teraterm-com.html#linemode) about the line at a time mode.

Thanks,

**Comment by nmaya** [comment]
Hi,

It is expected. Line at a time mode is a mode of **[TELNET](https://manpages.ubuntu.com/manpages/xenial/man1/telnet-ssl.1.html) protocol**.
It is not affect to serial connection.

Thanks,

**Comment by zmatsuo** [comment]
Added link to document.
