### ISSUE TITLE
マクロでgetenvにより環境変数定義を取得した際に、日本語を含んでいると文字化けする

### ISSUE THREAD

**Issue by nbrains** [TeraTermProject/teraterm#388]
# 問題概要
TeraTerm v5.0～v5.3のマクロにおいて、getenv/expandenvにより環境変数定義を取得した際に、日本語を含んでいると文字化けする。
TeraTerm v4.108では発生しない。

# 再現手順
コマンドプロンプトから、ユーザー環境変数「TEST_ENV」に設定値「日本語」を設定する。
```
SetX TEST_ENV 日本語
```
下記内容で「env.ttl」を作成し、ttpmacro.exeにDrag&Dropする。
```
getenv 'TEST_ENV' m_Env
messagebox m_Env "title"

m_Env = '%TEST_ENV%'
expandenv m_Env
messagebox m_Env "title"
```

TeraTerm v5.0～v5.3で実行するとメッセージボックスに「???{??」と表示される。

# 期待動作
メッセージボックスに「日本語」と表示される。

# 確認環境
Windows 11 Pro 23H2

# 補足
環境変数の設定値からTeraTermのログの出力パスを切り替えようとした際に発生。
「C:\apps\プログラム\log」のような日本語を含むファイルパスでも発生しています。

# TODO
- マクロコマンド
  - [x] getenv
  - [x] expandenv
  - [x] setenv
- [x] 変更履歴

**Comment by zmatsuo** [comment]
連絡ありがとうございます。

マクロコマンド getenv, expandenv  が Unicode に対応していませんでした。
履歴など後回しで、取り急ぎ修正しました。

このように環境変数を設定して、
```
TEST_ENV=日本語😄👍
```
このように表示できることを確認しました。
![388-1](https://github.com/user-attachments/assets/ea4931ec-8be3-4b85-adeb-d7d3ad89877f)


バイナリを作っています。もうすぐできると思います。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/50971388/artifacts
試してみてください。

[setenv](https://teratermproject.github.io/manual/4/ja/macro/command/setenv.html)も同様ですね。
明日対応します。

**Comment by nbrains** [comment]
修正版で改善された事を確認しました。
迅速なご対応ありがとうございました。

**Comment by zmatsuo** [comment]
setenvも対応しました。

main にマージしました。
バイナリを作っています。
https://ci.appveyor.com/project/teraterm/github-main/builds/50988279/artifacts

**Comment by zmatsuo** [comment]
クローズします。
