### ISSUE TITLE
Recent ttssh releases marked as malware?

### ISSUE THREAD

**Issue by doron1** [TeraTermProject/teraterm#39]
Hello, I'm a (very) long time user of ttssh. When trying to upgrade recently, I found that both 5.0 and 4.107 releases are marked as malware by some AV tools (check VT). Release 4.105 does not get this. Is this malware?

**Comment by nmaya** [comment]
Hi,
It seems to false positive.

**Comment by doron1** [comment]
Thanks for your quick response!
It is from 5 different AV systems, including a Trojan indication, which is
what made me uneasy.
Are you absolutely sure about this?

**Comment by zmatsuo** [comment]
see #56
Close this.
