### ISSUE TITLE
"Send file" over serial line does not honor "local echo" setting

### ISSUE THREAD

**Issue by herrmanthegerman** [TeraTermProject/teraterm#393]
Hello,

in "Terminal Setup", I can enable a local echo:

![image](https://github.com/user-attachments/assets/1a33e33e-ad37-43cf-ab0b-2cbefac7c9ea)

When **sending files**, the lines sent are not displayed although "Local echo" is enabled.

I consider this a bug or is this to be expected? Thanks.

[Running Tera Term 5.3]

**Comment by zmatsuo** [comment]
Thanks for the report.
It seems to be a bug. We will investigate.

**Comment by zmatsuo** [comment]
Fixed. Please try this binary.
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/51076151/artifacts
