### ISSUE TITLE
TeraTerm v5.3 - Link macro first. Use 'connect' macro.

### ISSUE THREAD

**Issue by brucerry** [TeraTermProject/teraterm#398]
The ttpmacro.exe has been set
![teraterm-5 3_set_ttpmacro exe](https://github.com/user-attachments/assets/7c6ef849-e146-42fa-9e34-75cb602d744c)

But pressed "Run",
![teraterm-5 3_link_macro_error](https://github.com/user-attachments/assets/0b50ddbf-cf8c-42c6-bb18-45bc52fc4401)

**Comment by nmaya** [comment]
Hi,

Macro sends some data via Tera Term.
To send some data, Macro is linked to Tera Term, and Tera Term is connected to some remote.
You have to link by connect command, as the error message says.

**Comment by brucerry** [comment]
Got it. We have to add a 'connect' command at the beginning of script in order to make connection with the computer port (in my case).

Below is a *.ttl example to make it works.
```
; TTL command reference
; https://teratermproject.github.io/manual/5/en/macro/command/index.html

; https://teratermproject.github.io/manual/4/en/macro/command/connect.html
; Connect to COM5
; This would open and connect to Tera Term window at port COM5 directly, so do not need to open it before executing this script
connect '/C=5'

sendln "echo hello"

```

**Comment by brucerry** [comment]
> Hi,
> 
> Macro sends some data via Tera Term. To send some data, Macro is linked to Tera Term, and Tera Term is connected to some remote. You have to link by connect command, as the error message says.

Got it. We have to add a 'connect' command at the beginning of script in order to make connection with the computer port (in my case). Older version(s) may not have to do so.

Below is a *.ttl example to make it works.
```
; TTL command reference
; https://teratermproject.github.io/manual/5/en/macro/command/index.html

; https://teratermproject.github.io/manual/4/en/macro/command/connect.html
; Connect to COM5
; This would open and connect to Tera Term window at port COM5 directly, so do not need to open it before executing this script
connect '/C=5'

sendln "echo hello"

```
