### ISSUE TITLE
Documentation website is offline

### ISSUE THREAD

**Issue by JK3X4** [TeraTermProject/teraterm#40]
Sorry if this is not the way to communicate this kind of issue, but I 'm trying to access online documentation for ttl language, and the website looks like it is down.

Is the project deprecated or discontinued ? Could you provide offline file which contains current documentation page for teraterm language?

Thank you in advance

**Comment by nmaya** [comment]
TeraTerm Project web site was moved to https://teratermproject.github.io/.
Online manual is [here](https://teratermproject.github.io/manual/5/en/).
Offline manual is installed with program, teraterm.chm.

**Comment by JK3X4** [comment]
Thank you!!! I realized it too late.
