### ISSUE TITLE
ターミナル上は1つしか表示されていないが、画面の端で、改行した時、改行後の先頭文字、1文字がログで二重に出力されている

### ISSUE THREAD

**Issue by canal19680425** [TeraTermProject/teraterm#403]
コマンドラインにおいて、画面端まで行き、2行に跨るコマンドを入力した時のログにおいて、改行後の先頭文字が重複して、ログに記録される。
Tera-Term Ver4.78でこの事象を確認し、最新である、Ver5.3でも、同様の事象が起きた。
以下事象の例
[ターミナル画面上での表示]
[test@aaaaaaaaaaaaa tmp]# echo 0_1_2_3_4
_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19
_20_21_22_23_24_25_26_27_28_29_30_31_32_
[ログ出力]
# echo 0_1_2_3_4__5_6_7_8_9_10_11_12_13_14_15_16_17_18_19__20_21_22_23_24_25_26_27_28_29_30_31_32_

5の前の_ と 20の前_の2文字が、重複文字です。

**Comment by nmaya** [comment]
報告ありがとうございます。

ログファイルに記録されるのは、端末に表示された結果ではありません。
ログファイルはリモートが送ってきたデータを記録するものですから、ログファイルで文字が重複しているのであればリモートがその文字を重複して送ってきているのでしょう。バイナリログを取れば、エスケープシーケンスを含めて何が送られてきているのか確認することができます。

cf. [Q. ログファイルの内容が VTWindow に表示された内容と異なる。表示できない文字が出力されている。](https://teratermproject.github.io/manual/5/ja/about/qanda.html#logfile_garbled)
