### ISSUE TITLE
Send file ダイアログ、Logダイアログのボタンの並びを修正

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#407]
https://github.com/TeraTermProject/teraterm/issues/353#issuecomment-2508854943

「OK」「Cancel」「Help」の順に変更する

**Comment by nmaya** [comment]
もしかして #380 の d1d00257c6525b2d3b3f5ebcb9762711d33bb027 とぶつかりませんか？

**Comment by zmatsuo** [comment]
ボタンの並びの修正を #380 に入れてしまっていました。#380 を修正しました。
