### ISSUE TITLE
Visual Studio 2019(プラットフォーム ツールセット = 'v142')のビルドツールセットがみつかりません

### ISSUE THREAD

**Issue by shimarisu** [TeraTermProject/teraterm#48]
■現象
https://teratermproject.github.io/manual/5/ja/reference/develop.html
を参考にして、Tera Term 5.1(GitHub上にある最新の開発版) のビルドにチャレンジしています。

Visual Studio Community 2022 をインストールして、
Tera Termをビルドしようとしたところ、以下のエラーとなりました。

MSB8020 Visual Studio 2019(プラットフォーム ツールセット = 'v142')のビルドツールセットがみつかりません。...

■質問
①Tera Term 5.1dev は プラットフォーム ツールセット = 'v143'でビルドできないでしょうか？
②プラットフォーム ツールセット = 'v142'は現在入手可能でしょうか？

よろしくお願いいたします。

**Comment by nmaya** [comment]
どこかに書こうと思って忘れていました。私もその現象に当たりました。
「Visual Studio **2022** のインストーラで **MSVC v142 VS 2019 C++ x64/86 ビルドツール** を選択して入れておかないと、**v143** でビルドできない」です。
言い換えると、v143 でビルドするために v142 を（使われないけど）入れておかなければならない、ということになります。原因と回避方法はわかりません。
取り急ぎご参考まで。

**Comment by shimarisu** [comment]
「MSVC v142 VS 2019 C++ x64/86 ビルドツール 」だけを追加でインストールする方法が分からなかったため
一度 Visual Studioをアンインストールし、インストールし直すことで、Tera Termのビルドができるようになりました。
ありがとうございました。

**Comment by nmaya** [comment]
これを選択します。
![vc142-](https://github.com/TeraTermProject/teraterm/assets/5668936/c0b3a536-bf29-4592-9091-69da5fdf6a3a)

**Comment by zmatsuo** [comment]
使っているプロジェクトファイルの PlatformToolset に
誤りがあるのではと思い調べましたが見当たりませんでした。

使用していないプロジェクトファイルがあったので削除しました。

**Comment by zmatsuo** [comment]
Visual Studioのプロジェクトファイルの参照に誤りがありました。
修正しました。

試しにMicrosoftが配布している開発環境を使って検証しました。
こんな手順でビルドできます。

- 仮想マシン上で開発環境を準備する
  - https://developer.microsoft.com/ja-jp/windows/downloads/virtual-machines/
- 設定 / Time & language / Language & region / Add a alnguage
  - キーボードを切り替え, 日本語を追加 など
- Windowsキー+'R', cmd起動
- 次のコマンドを入力
```
cd \
mkdir teraterm
cd teraterm
winget install Git.Git
winget install cmake
git clone https://github.com/TeraTermProject/teraterm.git -b main
cd teraterm\buildtools
install_cygwin.bat
install_innosetup.bat
cd ..\installer
release.bat 3
```

**Comment by shimarisu** [comment]
修正いただき、ありがとうございました。

**Comment by nmaya** [comment]
MSVC v142 VS 2019 C++ x64/86 ビルドツール を削除してもビルドできることを確認しました。
ありがとうございます。
