### ISSUE TITLE
一部の設定項目がTERATERM.INIへ保存されない

### ISSUE THREAD

**Issue by linlac** [TeraTermProject/teraterm#51]
Tera Term: その他の設定
→ フォント
→ Drawing resized font to fit cell width
上記設定がデフォルト有効となっておりますが
チェックボックスを外したうえで INI を保存しても、次回起動時に有効な状態となってしまいます。

有効時、無効時で INI に差分が生じておらず、
INI を読み解きましても、そもそも当該項目にあたるパラメータが存在していないようにも見受けられます。

一部のフォントにおいて当該項目との相性が悪く、表示が乱れてしまうため
任意でオフにした状態を設定として保存できますと大変助かります。

上記事象の解決策･ワークアラウンドにつきましてアドバイス頂けますと幸いです。

Tera Term Version 5.0 (SVN# 11000)
表示に問題が生じるフォント: Inconsolata Regular

# tasklist
- [x] TERATERM.INI への読み書き（ttset.c）
- [x] setup/teraterm-ini.html
- [x] about/history.html

**Comment by zmatsuo** [comment]
ありがとうございます。

ファイルに保存していませんでした。
起動後はいつもonになっています。

こんな感じで保存できるようにしましょうか
```
[Tera Term]
DrawingResizedFont=on/off
```
2,3日お時間ください。

**Comment by linlac** [comment]
ご確認ありがとうございます。

実装頂けるとのことで非常に助かります。ありがとうございます。
(PRお送りできるだけの技術力があれば良かったのですが…)

今のところは都度オフにするなり、
その他のフォントを利用するなりで回避可能ですので
どうぞ急がれることなくご対応頂けましたら幸いにございます。

**Comment by nmaya** [comment]
UIにある項目なので、何をする設定なのか、このページへの説明追加が必要かと思います。
https://teratermproject.github.io/manual/5/ja/menu/setup-additional-visual.html

**Comment by nmaya** [comment]
UIのタブの並び順とヘルプの並び順が違うので見間違えました。
https://teratermproject.github.io/manual/5/ja/menu/setup-additional-font.html#ResizedFont にありましたね。

**Comment by zmatsuo** [comment]
タブの並び順とヘルプの並び順を合わせました。
全てのタブのヘルプの目次に追加しました。

https://ci.appveyor.com/project/teraterm/github-main/builds/48776079/artifacts

**Comment by linlac** [comment]
起案者です

TeraTerm release 5.1 で設定が保存･反映されることを確認致しました。
大変迅速なご対応を誠にありがとうございました！
