### ISSUE TITLE
Tera Term 5.1のexeファイルがマルウエアとして認識される

### ISSUE THREAD

**Issue by Phantom1104** [TeraTermProject/teraterm#56]
Chromeでダウンロードした場合や、ダウンロード後にexeファイルを実行しようとすると、teraterm-5.1.exeがマルウエアとして認識されてしまいます。

![teraterm51_malware1](https://github.com/TeraTermProject/teraterm/assets/148406001/f4cee8bc-5c76-4da7-8354-80c5ade316c4)
![teraterm51_malware2](https://github.com/TeraTermProject/teraterm/assets/148406001/1036c314-422c-41af-ac82-52eae51000c0)

**Comment by nmaya** [comment]
報告ありがとうございます。
Windows Defender で "Win32/Wacapew.C!ml" となることも確認しています。
誤検知と思われますが、こちらでできる対応はパターンの更新で直るのを待つことくらいかもしれません。

こちらでできることは切り分けはこんな感じだと思います。

- 何が検出されているのか
  - インストーラの exe ... 検出される
  - zip 版 ... 問題ない

内部の実行ファイルが検出されているわけではない？△

- ダウンロードサイト
  -  GitHub ... 検出される
  - AppVeyor  ... 検出される

ダウンロード元による違いはない。×

- 使用するインストーラのバージョン
   - リリースを作成 AppVeyor ... Inno Setup 6.2.2
   - ローカルで作成 ... Inno Setup 6.2.2

同じ。×

- インストーラを作成する環境
   - リリースを作成 ... 検出される
   - ローカルで作成 ... 検出されない

インストーラのビルド環境か？内部の実行ファイルのビルド環境も異なる。△

**Comment by shimarisu** [comment]
マイクロソフト Edge でダウンロードしようとすると

![image](https://github.com/TeraTermProject/teraterm/assets/16871312/ead8ff6e-86df-4eba-b7d1-bd134c4deeaa)

マイクロソフトへのフィードバック として
私はこの Web サイトの管理者あるいは代表者であり、この Web サイトについての誤った警告について報告します
ということができる模様です。

**Comment by nmaya** [comment]
> マイクロソフトへのフィードバック

情報ありがとうございます。すでに報告済みです。

![Clipboard03](https://github.com/TeraTermProject/teraterm/assets/5668936/427f0059-f961-487d-942a-9cc2b7645a1e)

**Comment by nmaya** [comment]
- Defender SmartScreen が、Edgeでダウンロードしたときに「一般的にダウンロードされていません」の警告を出す
- Defender が "Win32/Wacapew.C!ml" と判定してファイルを削除する
どちらも解消しているようです。

**Comment by Phantom1104** [comment]
ありがとうございます。
正常にダウンロードおよびインストールが可能になりました。

**Comment by nmaya** [comment]
### 現時点の状況
Edge の Defender SmartScreen 「一般的にダウンロードされていません」
どちらも報告済みですが、

- 4.107 ... 解消済み
- 4.108 ... まだ解消していない

**Comment by zmatsuo** [comment]
CLaunch の最新版(4.06)が現在ダウンロードできません
http://hp.vector.co.jp/authors/VA018351/claunch.html
正確にはダウンロードしてファイルシステムに置くと
Windows セキュリティーが削除してしまいます。

winget で CLaaunch をインストールすることができるようなのですが
wingetでは4.04が最新版です。
```
winget list | grep -i claunch
CLaunch                                   CLaunch                                   4.04
```
もしかするとパッケージの登録が行われると
ブロックされにくくなる/されなくなるのかもしれません。🤔

**Comment by nmaya** [comment]
5.2 インストーラが、Edge の Defender SmartScreen 「一般的にダウンロードされていません」に引っかからなくなりました。
