### ISSUE TITLE
カラー反転時の範囲選択色が反転しない

### ISSUE THREAD

**Issue by JuneChrome** [TeraTermProject/teraterm#58]
TeraTermpro
いつも便利に使わせていただいておりありがとうございます。

Ver5.0・5.1のデフォルト状態で
設定→ウィンドウ→カラー枠内の反転を選んだ後
ターミナルの画面で範囲選択を行うと
選択色が背景と同一のままになっており
範囲選択できていないように見え、真っ白になってしまします。
※真っ白になるので文字色は範囲選択時に反転が正常にかかっているようです
※範囲選択したまま再度色を反転すると範囲選択自体はできていることが確認できます

利用環境:Windows10_Pro_64bit
　　　 　Windows11_pro_64bit
インストール版・ポータブル版ともに同一の事象が確認できています。

何か対処法などありましたら教えていただきたいです。

●デフォルトウィンドウカラー
![TeraTerm_comparison01](https://github.com/TeraTermProject/teraterm/assets/154390780/81fcb597-ad27-43ba-b1d2-7753ce2e2bbd)

●ウィンドウカラー反転設定後
![TeraTerm_comparison02(Reverse)](https://github.com/TeraTermProject/teraterm/assets/154390780/f478379f-15c3-404d-ba75-b48b89f1e86b)

またカラーで他に気になるのが4.x系の時に反転前と後で
TERATERM.INIを見比べると4つのカラー系の項目で
設定値が変わっているのがわかるのですが
5.0になると反転してもカラー系の項目が1つしか変わっていないのも気になりました。
こちらも不具合でないかの確認と、対処法があれば教えていただきたいです。

●Ver4.x系カラー反転時INIファイル比較
![Ver4 x系](https://github.com/TeraTermProject/teraterm/assets/154390780/12e8c3f7-b84d-4aae-a2ba-2bee49e24c0e)

●Ver5.x系カラー反転時INIファイル比較
![Ver5 0](https://github.com/TeraTermProject/teraterm/assets/154390780/5f12c4a1-4ac1-4429-b279-57bc81acf473)

よろしくお願いいたします。

**Comment by nmaya** [comment]
(1) 選択されている範囲の背景色は、Reverse(反転) 属性の背景色が使われるようです。
Normal(標準)属性のテキスト色が(0,0,0)で背景色が(255,255,255)で、Reverse(反転)の背景色が(255,255,255)であれば、そのような動作になると思います。

(2) 「反転(Reverse)」ボタンは、いま選択されている属性のテキスト/背景色を入れ替えます。
すべての属性のテキスト/背景色を入れ替えるわけではありませんので、1つしか変わらないのは正常な動作だと思います。

**Comment by zmatsuo** [comment]
反転表示の説明を修正しました。
https://teratermproject.github.io/manual/5/ja/about/emulations.html#reverse

標準状態では
反転属性は有効で、
Normal属性(SGR 0)と反転属性(SGR 7)は
文字(前景)と背景の色関係が反対になっています。
https://teratermproject.github.io/manual/5/ja/about/ctrlseq.html#charattr

Normal属性の文字と背景の色を「反転」ボタンを押して入れ替えると、
反転属性と同じ色となります。

試しに反転属性の文字や背景の色の変更も試してみてください。

linux系のコマンドが使えるなら次のように実行すると、
```
wget https://raw.githubusercontent.com/TeraTermProject/teraterm/main/tests/color-sgr-decscnm.pl -O - | perl - aq
```
現在の設定を見ることができます。

--
ソースを眺めていると反転表示の説明はまだ不足していました。
後日説明を追記します。

**Comment by nmaya** [comment]
@zmatsuo 説明と追記ありがとうございます。

> Normal属性の文字と背景の色を「反転」ボタンを押して入れ替えると、 反転属性と同じ色となります。

これは違いませんか？

![reverse](https://github.com/TeraTermProject/teraterm/assets/5668936/9ca96982-37d2-4b0d-b4c1-a326049b4cf7)

Window ダイアログの「Reverse」ボタンは、あくまで"現在選択されていて編集中の属性"のText色とBG色を入れ替えているように見えます。
Normal属性の編集中にReverse属性の値を持ってきているようには見えませんし、反転表示時にReverse属性の色を使うかNormal属性の色を反転しているかはこのダイアログの動きには関係ないように思います。

**Comment by JuneChrome** [comment]
@nmaya  様　　@zmatsuo  様

確認とアドバイスありがとうございます。

結論から言うと問題にしている事象は**解決**しました。
ただ多少気になる点は残ったので情報提供だけさせていただきます。

まず今回私が困っていたことがうまく伝わっていないといけないので
改めて書きます。
「カラー反転時での　コピーなどをするための　**範囲選択**で文字が消えてしまう（選択できていないように見える）」
利用環境:Windows10_Pro_64bit
　　　 　Windows11_pro_64bit
利用TeraTerm：インストール後カラー設定など
　　　　　　　すべての設定を変更しない標準状態を利用。
　　　　　　　Ver4とVer5を比較利用中

nmaya様に書いていただいたようにWindowsダイアログ上の操作で
①Attribute「Normal」をReverse
②Attribute「Reverse」をReverse
の両方を操作することでカラー反転時でも**範囲選択**で
文字が消えずに見えるようになりました。（問題解決）

私が違和感があるのが、今までTeraTermのVer4系をずっと利用させていただいていて
反転操作はAttribute「Normal」でしか、していませんでしたが
**範囲選択**時に文字が消えるようなことはなかったことです。

こちらは多少違和感ありますが新旧バージョンでソフトの挙動が変わり
「Ver5系からはこういった仕様だよ」ということであれば
そのように使っていこうと思います。
（ちなみに色の反転操作は2つTeraTermを立ち上げて、別々のサーバで作業するときに
　画面で識別をはっきりさせるために日常的に利用しています）

お対応ありがとうございました。
よろしくお願いいたします。

**Comment by nmaya** [comment]
> ターミナルの画面で範囲選択を行うと
> 選択色が背景と同一のままになっており
> 範囲選択できていないように見え、真っ白になってしまします。

これについては、(1) の説明などにより解決（ご理解）いただけたものと思います。

> 4.x系の時に反転前と後で
> TERATERM.INIを見比べると4つのカラー系の項目で
> 設定値が変わっているのがわかるのですが

4.106 までは、UseNormalBGColor (常に標準の背景色を使う) が有効になっていると、**Window ダイアログを確定したとき**に Normal属性の BG 色が自動的にすべての属性の BG 色設定に反映されるようです。(動作3)

これは(2)で説明した「『反転(Reverse)』ボタン」の動作とは別の動作です。

> 5.0になると反転してもカラー系の項目が1つしか変わっていない

4.107/5.0 から (動作3) の動きがなくなったようです。内部の細かい実装まですぐにわかりませんが、UseNormalBGColor のときに各属性の背景色をNormal属性の背景色で上書きするのをやめ、そのかわり使うときにNormal属性の色を参照するようになった、のだと思います。変更された経緯は https://osdn.net/projects/ttssh2/ticket/45493, https://osdn.net/projects/ttssh2/ticket/45648 にあると思います。

この変更により、INI へ保存される内容に違いが起こりました。
また同じくこの変更により、Reverse属性の色が自動的に変更されなくなり、その結果Normal属性とReverse属性の色が全く同じになり、選択されていることが視覚的に見えなくなる現象（今回私が困っていたこと）が起きました。

私の見解は
- 不便になった（戸惑った）のはわかります
- 暗黙的に設定を書き換える動作3の動きはあまりよいと思えない
- おそらくこの現象が見えていた訳ではないが、妥当な理由があって変更した動作だと思う
なので、このままでよいと思っています。

**Comment by zmatsuo** [comment]
> これは違いませんか？
失礼しました。@nmaya

Normal属性とReverse属性のTextとBackgroundが同じ色に
設定する説明のつもりでした。

Normal属性と、Reverse属性(=選択状態)の
TextとBackgroundの両方が同じ色で設定しようとすると
警告を出すようにするのも良いかなと思いました。
(その他の属性もそうしたほうがよいですかね)


解決してよかったです。@JuneChrome

> 反転操作はAttribute「Normal」でしか、していませんでしたが
> 範囲選択時に文字が消えるようなことはなかったことです。

Tera Term 4.107 から Tera Term 5 と同じ動作になっています。

次の修正(4-stable/r10269, 3b0934b)です
> DECSCNM setで色反転時に、属性にANSIColorを設定した文字の前景色と背景色を入れ替えるようにした。
https://teratermproject.github.io/manual/4/ja/about/history.html#teraterm_4.107

動作が変化するとオヤッと思いますよね。
修正しているときは気が付きませんでした。
だた今の動作は妥当かなと思います。


ドキュメントを修正したらクローズしようと思います。

**Comment by zmatsuo** [comment]
> Window ダイアログを確定したときに Normal属性の BG 色が自動的にすべての属性の BG 色設定に反映されるようです。(動作3)

これ気づいていなかったかもしれません(ちょっと詳細は忘れてしまいました😄)

ただやはり今の動作でよいかなと思います。
良い変更方法が思いついたら取り入れていきましょう。

色かんれんの設定UIはそのうちまとめないとですね。


/THEME=[テーマファイル]
https://teratermproject.github.io/manual/5/ja/commandline/teraterm.html
/FG= や /BG=
https://github.com/TeraTermProject/teraterm/blob/main/TTXSamples/TTXCommandLineOpt/ReadMe-ja.txt
をhost:のところに入れて
https://teratermproject.github.io/manual/5/ja/usage/ssh.html
履歴に入れるのも良いかなと思います。@JuneChrome

**Comment by zmatsuo** [comment]
文字の前景色背景色について追記しました。
https://teratermproject.github.io/manual/5/ja/about/emulations.html#fg_bg_color

[↑](https://github.com/TeraTermProject/teraterm/issues/58#issuecomment-1864655478) の tests/color-sgr-decscnm.pl の出力のCyanとBright Cyanが同色に見えます。
これも調査します。

**Comment by nmaya** [comment]
> TextとBackgroundの両方が同じ色で設定しようとすると
警告を出すようにするのも良いかなと思いました。
(その他の属性もそうしたほうがよいですかね)

うーん、そこまでしなくていいと思います。

**Comment by zmatsuo** [comment]
> これも調査します。

問題なさそうです。

"16 Colors(PC style)" にチェックが入っていた時、
  SGR 46(背景Cyan(Dark Cyan)) + Blink → Bright Cyan
"16 Colors(PC style)" チェックが入っていなかった時、
  SGR 46(背景Cyan(Dark Cyan)) + Blink → Cyan

となります。

画像をキャプチャしたとき、
TEARTERM.INIがインストール直後のものを使っていたので
"16 Colors(PC style)" にチェックが入っていたはずで正しい動作です。

**Comment by zmatsuo** [comment]
UseTextColorについてもマニュアルに追記しました。

> うーん、そこまでしなくていいと思います。

おいといて、問い合わせが再度出てきたら考えましょうか。

現在の色設定を簡単にtera term上だけで確認できる方法が欲しいなと思いました。

このissueはクローズします。
