### ISSUE TITLE
TCP/IP setup dialog で最後のエントリが削除できない 

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#59]
TCP/IP setup dialog  で [Remove] ボタンでエントリを削除していくと、最後のエントリが削除できません。
最後のホスト1つを残置したまま [OK] で閉じ、再度 TCP/IP setup dialog を開くと、すべてのホストが削除されています。

対象バージョン： ver 5.0以降
ver4.108 では再現しません。

**Comment by zmatsuo** [comment]
お知らせいただきありがとうございます。
手もとで再現しました。
エントリが1つになったときの動作が何かおかしいですね。
調査、修正します。

**Comment by zmatsuo** [comment]
修正しました。

バイナリを次のURLからダウンロードして試すことができます。
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts

**Comment by kattyo-abk** [comment]
開発版で確認したところ、エントリの操作は正常になりました。
ご対応ありがとうございます。

以下、問題とは関係ないですが、開発版によるエントリの操作以外の変更点部分についてです。

v4.102 までダイアログ類は System フォントでしたが、
その時は TCP/IP setup ダイアログのリストボックスの表示行数は6行でした。

v4.103で Dialog Font のデフォルトが MS UI Gothic (9pt)になった時に４行になったようです。
v4.103では MS UI Gothic 10pt 以上にすると5行に、16pt以上またはSystemフォントに戻すと6行表示されます。
v5.1 までは v4.103 と同様のようです。

修正版 (5.2-dev-20231223_233822-622af87c2-appveyor-snapshot)では
デフォルトフォント MS UI Gothic (9pt) では横スクロールバーが増えた影響で
エントリの実質表示行数が３行になりました。
16pt にすると 5行表示となります。

可能でしたらデフォルト設定の状態で4行以上は表示された方が良いのでは？と思います。
（個人的には可能なら5行以上を希望。）

なお、確認した環境はスケーリング100%(dot by dot)です。

**Comment by kattyo-abk** [comment]
修正版ですと MS UI Gothic 11pt以上にしないと縦スクロールバーにスクロール ボックスが表示されません。
（11pt でだいたい 4.8行くらい表示されます。）

**Comment by zmatsuo** [comment]
> エントリの操作は正常になりました。

よかったです。

横スクロールバーですが、
設定されている文字列がリストボックスの横幅より長いと表示されます。

> エントリの実質表示行数が３行になりました。

横も縦(行数)も標準ではちょっと狭いですね。
ダイアログのレイアウトは見直したほうがよさそうです。

ダイアログをリサイズできるようにしてみました。
https://ci.appveyor.com/project/teraterm/github-snapshot/build/artifacts
リサイズする手間はありますが、
どんなフォント、環境で表示しても対応できると思います。
お試しください。

ダイアログはリサイズできますが、
手もとのWindows10では(11も?)
UI上リサイズできるかパッと見わかりません。

右下のグラフィック(SizeBox?添付画像のようなアイコンです)が
ないのが原因の一つなのですが
![sizebox](https://github.com/TeraTermProject/teraterm/assets/6488847/d06dbdd8-d33a-4762-be95-f7578a468ff7)
とりあえずこのままでいいかなと思います。

リサイズできるけど右下のグラフィックのないアプリは
Explorer, Cygwinのsetup.exe, Chrome, Firefox など存在していて、
(わかりにくいけど)それほど違和感ないのではと思います。

この右下グラフィックを違和感なく簡単に出すことができるなら
出すほうがいいとは思うのですが、
今のところ出し方がわからずにいます。

あと、ダイアログのサイズを自動で保存したくなりますね。
またべつのissueで。

レイアウト調整ができればこのissueは閉じようかなと思います。

**Comment by kattyo-abk** [comment]
修正ありがとうございました。
ダイアログウィンドウのサイズ変更ができるようになっているのも、とても良いです。
私はクローズで構いません。

> この右下グラフィックを違和感なく簡単に出すことができるなら
> 出すほうがいいとは思うのですが、
> 今のところ出し方がわからずにいます。

たぶん以下のページにある SBS_SIZEGRIP だとは思いますがやったことは無いので私もわかりません。
http://www.kumei.ne.jp/c_lang/sdk/sdk_58.htm


以下、もし気になるようでしたら気が向いたときにでも修正ください。
（不都合があるレベルではないのでそのままでもOKかなと。）
・いくつかのフォントでは History の後半が収まらない
・いくつかのフォントでは History のラベルの影響でGROUPBOXの線が消えることがある
フォント選択例： Termianl や MS ゴシック 、MS UI Gothic の 10pt など

**Comment by zmatsuo** [comment]
ウィンドウ(ダイアログ)の下部の中央に[OK]などを置くレイアウトは
Windows 3.1の頃に多いデザインでしょうか。
Windows 95の頃になると右下や右上が多い印象です。

コントロールの位置を全般変更しようかなとも思ったのですが、
従来デザインを踏襲してサイズと位置だけを調整する方針で修正しました。

[OK]ボタンはリサイズ時も中央付近になるよう修正しました。

> フォント選択例： Termianl や MS ゴシック 、MS UI Gothic の 10pt など

MS UI Gothic, Meiryo UI, Yu Gothic UI では大丈夫な程度に調整しました。

お試しください。
https://ci.appveyor.com/project/teraterm/github-main/builds/48844685/artifacts

変更履歴を入れてませんでした。
入れたらクローズします。

**Comment by kattyo-abk** [comment]
いくらか試しましたが問題なさそうです。
ありがとうございました。

**Comment by zmatsuo** [comment]
確認ありがとうございます。

改版履歴に追記完了しました。
クローズします。
