### ISSUE TITLE
settitle に日本語を渡すと落ちる

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#6]
from https://osdn.net/projects/ttssh2/ticket/48873, https://github.com/TeraTermProject/osdn-download/issues/30

cf. https://github.com/TeraTermProject/osdn-download/issues/30#issuecomment-1779536805

**Comment by zmatsuo** [comment]
修正しました。

次のURLからダウンロードできます
調整できていませんが (#11, #12)
動作確認はできます
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts

**Comment by nmaya** [comment]
これらのスクリプトで確認しました。

- Shift_JIS
- UTF-8 (BOMあり)

[48873_ttL.zip](https://github.com/TeraTermProject/teraterm/files/13225609/48873_ttL.zip)
