### ISSUE TITLE
Additional settings で Font タブを表示すると、Visualタブでの Font Quality の変更が反映されない

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#62]
Additional settings の Visual タブで Font Quality を変更したあと、
他のタブに移動せずに [OK] でクローズすると、設定が正常に変更されます。

Additional settings の Visual タブで Font Quality を変更したあと、
ダイアログを閉じずに Font タブを表示すると、
Font Quality に変更前の設定が表示されます。
この状態で [OK] でクローズすると、設定が変更されません。

一方、 Font タブで Font Quality を変更したあとに、
Visualタブを表示すると、変更前の設定が表示されていますが、
この状態で  [OK] でクローズすると、Font タブの設定が反映されます。

つまりFontタブを表示したら、Fontタブ側の Font Quality 設定が反映されるようです。

Font Quality の設定をどちらかのタブに寄せるか、
片方での変更をもう一方のタブにも反映するか、どちらかにしたほうが良いかと思われます。

**Comment by zmatsuo** [comment]
思ったように設定できないのは良くないですね。

4と同じようにVisualタブだけにして
Fontタブから外そうと思います。

**Comment by zmatsuo** [comment]
修正しました。

次のURLからバイナリを取得できます。
お試しください。
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts

**Comment by kattyo-abk** [comment]
ありがとうございます。問題はなさそうです。

**Comment by zmatsuo** [comment]
😄
クローズします。
