### ISSUE TITLE
テーマを適用すると Application fault で落ちる

### ISSUE THREAD

**Issue by h3zjp** [TeraTermProject/teraterm#66]
その他の設定 → 表示 →  Theme を Enable に、startup を 固定テーマ にして ini ファイルを指定した後設定ファイルを保存。
その後の起動で「Application fault」が表示され正常に起動しません。
同設定画面にある Theme Editor 画面で theme file を読み込もうとした際にも同様のエラーが表示され、TeraTerm が強制終了します。
- インストール直後の ini ファイルで確認
- 下記バージョンの Windows で確認
1. Win10 22H2 Ver. 5.0
1. Win11 23H2 Ver.5.0
1. Win11 23H2 Ver.5.1

![2023-1226-195722(536x307)](https://github.com/TeraTermProject/teraterm/assets/2877128/8975d29c-46c8-4790-b02a-57438efb8b36)

ご確認頂ければと思います。

**Comment by zmatsuo** [comment]
お知らせいただきありがとうございます。

手もとで動作をチェックすると何か動作がおかしいようでした。
調査します。

**Comment by zmatsuo** [comment]
Application fault を修正しました。
次のURLに修正したバイナリがあります。
https://ci.appveyor.com/project/teraterm/github-main/builds/48838610/artifacts

ファイル指定時に *.jpgなどワイルドカードを使用すると発生していました。

また、背景と色両方の設定が入ったテーマファイルが
読めなかったので修正しました。

テーマ関連はあまり使われていないのでまだ何か潜んでいるかもしれません。

修正履歴は後日入れます。

**Comment by zmatsuo** [comment]
履歴を追記した。
クローズします。
