### ISSUE TITLE
TTXCommandLineOpt の /FG=, /BG= が効かない

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#7]
cf. https://github.com/TeraTermProject/osdn-download/issues/30

プラグインは VTColor[0], VTColor[1] を書き替えている

**Comment by zmatsuo** [comment]
修正しました。
次のURLからスナップショットをダウンロードできます。
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts
問題がありましたら、再度オープンしてください。
