### ISSUE TITLE
HTML ヘルプの構成見直し（トップページ）

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#73]
- [x] 参考資料の各ライセンスへのリンクを削除
  - ライセンスへのリンクは copyright にあるため

- [x] Keycode の扱い

- もともとの「Tera Termのヘルプ(hlp)」「マクロのヘルプ(hlp)」「keycodeのヘルプ(text)」を、1つのHTMLヘルプに統合している
- Keycode は 参考資料 ではなく、MACROヘルプと同レベルと考える

![ttermpro-2_3](https://github.com/TeraTermProject/teraterm/assets/5668936/3a35301d-0a82-4861-ab7d-dfc566c4795d)

- [x] 「開発者向け」を分割する案がどこかで出ていた気がする

こんな構成？
  - 環境構築（いまの 開発者向け 1,2）
  - 開発メモ（いまの 開発者向け 3）
  - TeraTerm Project 用リリース手順（いまの 開発者向け 4）
  - ソースコード解説

**Comment by zmatsuo** [comment]
Windowsの動作(Unicode版iniファイルのページ)や
pluginを作る人向けの情報を置くいい場所があればよいですね。

最近ちょっと悩んだんので TTXKanjiMenu などのプラグインの
ドキュメントも欲しいと思いました。
プラグイン、別プログラム(Tera Term Menu)なども
Keycode と同レベルがいいのかなと思います。
でも、インストールしない場合もあるのでどうしたらいいのか悩むところです。

**Comment by nmaya** [comment]
SSHやCygTerm+はインストーラで選択しないこともできますが、メニュー・コマンドライン・設定ファイルの説明で同列に扱われています。
ttermpro.exeを起動したらその中にありうる（インストーラで選択ていれば「ある」）ものだからです。
また、マクロはメニューから起動できますが.ttlファイルから実行することが多そうですし、Tera Term の操作に関する内容ではなく、なによりボリュームがあります。keycodeは単体で起動するしかありません。
私は上記のような線引きをしているので、「設定ファイル」までを分割することは考えておらず、一方 keycode は別にしたいと考えています。

**Comment by zmatsuo** [comment]
TTXKanjiMenu(など、他のプラグインも)の
ドキュメントを置くなら
フォルダ構成だと、

- doc\(ja|en)\html\usage

トップページは、

- 使い方 の 追加プラグイン

が妥当そうですね。
