### ISSUE TITLE
TeraTerm Menu の設定名に5Cを含む文字が使えない

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#8]
cf. https://github.com/TeraTermProject/osdn-download/issues/30

**Comment by zmatsuo** [comment]
TeraTerm Menuの内部のUnicode化を進めています。
登録名 "github😄"(ttpmenu.exe上ではカラー絵文字ではないです) などもokです。

ただし、ファイル名長制限(MAX_PATH)や文字長制限は変更前のままです。

ANSIで2byte目が5Cになる文字は、Unicode化で問題なくなるはずです。

見ていて気になった点

- ttpmenu.exeのカレントディレクトリの扱い
  - ttermpro.exeの参照
- GetProfileString()の使用
- portable版動作
  - ttpmenu.iniの場所

すぐに直せそうならこのまま直して、
ちょっと手間ならissueにしておこうと思います。

2c66dee1 の snapshot です。(ビルド中です)
https://ci.appveyor.com/project/teraterm/github-snapshot/build/artifacts

**Comment by zmatsuo** [comment]
Unicode化の修正を main にマージしました。
他に気づいた点を修正しました。
- ポータブル版対応
- 起動プログラムの引数長上限をなくした
などです。

わからなかった部分を issue (#45)にしました。

dd94c48 でバイナリを作りました。
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts

このissueはクローズします。
