### ISSUE TITLE
Broadcast command で選択済みのホストを前面に表示したい

### ISSUE THREAD

**Issue by kattyo-abk** [TeraTermProject/teraterm#83]
Broadcast command で現在選択済みのホストを前面に表示するボタンが欲しいです。

ウィンドウを沢山開いて作業するときに Broadcast command の対象を切り替えて作業をしており、
その時にコマンド送信対象ホストのウィンドウを前面に戻して表示したいです。
最小化していなくても他のウィンドウに隠れている場合があって、
それを前面にもってくる動作（BringWindowToTop相当？）です。
主に、全てのウィンドウを並べて表示にすると狭すぎる時に使用したいのです。

**Comment by sempreff** [comment]
割り込み失礼します。ボタンを追加する形でやってみました。ご確認いただければ幸甚です。 ＞ @zmatsuo @nmaya

**Comment by nmaya** [comment]
@kattyo-abk

> コマンド送信対象ホストのウィンドウ

Broadcast command は、コマンド送信対象ホストを複数選択することができます。
そのよう場合にはどうなって欲しいですか？

@sempreff ありがとうございます。

コードをパッと見た感じこうなりそうですが、あっていますか？
- 一覧を上からなめていって、選択されているウィンドウ（複数ありうる）に Fore になるよう指示する
  - 後ろにいたウィンドウは手前に来る。最小化されているウィンドウは「元のサイズ」にされ、手前に来る。
  - 最終的に一番手前に来るのは「一覧で選択されているなかの一番下にあるウィンドウ」

To all
複数のホストを選択することが可能ですが、どういう仕様がもっともユーザにとって便利だ/わかりやすい/戸惑わないと思いますか？

- PR #185 の動作
- （あるルールで1つを選び、その）1つだけ Fore にする
- 複数選択されている場合は Fore を効かなくする
- その他

**Comment by sempreff** [comment]
ご確認ありがとうございます。
> コードをパッと見た感じこうなりそうですが、あっていますか？
はい、書いていただいた通りです。

> どういう仕様がもっともユーザにとって便利だ/わかりやすい
想定している（自分もよくそうなる）ユースケースは、以下のようなシナリオです：
- 画面を覆い尽くし重なりあうほどのたくさんのウィンドウを開いて作業している
- それらのウィンドウは複数の作業対象のグループに分類できる
- それぞれのグループから代表のウィンドウを選んで Broadcast command ダイアログを出して、グループごとに対象を選択している（画面上に Broadcast command ダイアログは複数ある）
- いずれかの Broadcast command を選ぶことで作業対象のグループを切り替えて作業ができる
  - いずれかの Broadcast command を選択すると、そのダイアログの元となったウィンドウは前面に出る
  - 同ダイアログで選択しているその他の（複数の）ウィンドウも、簡単に前面に出したい
なので、自分としては PR の動作が妥当だと考えています。

その他として、仮想デスクトップを使う（重なり合わないように使う）という回避も考えられます。
また、単一の対象を前に出す方法についてはいくらでもあるので、その手段は増やさなくてよいでしょう。

ブランチからスナップショットを出せると、元投稿者さんにもお試しいただけるのではないかと思います。

**Comment by nmaya** [comment]
> 想定している（自分もよくそうなる）ユースケースは、以下のようなシナリオです：

説明ありがとうございます。@sempreff さんが考えるニーズを理解しました。

> ブランチからスナップショットを出せると、元投稿者さんにもお試しいただけるのではないかと思います。

うちのリポジトリにはまだブランチが存在せず PR しかありませんが、TeraTerm Project の AppVeyor アカウントで sempreff さんのリポジトリのブランチのスナップショットを作ってほしい、ということですか？
とりあえず走らせてみました https://ci.appveyor.com/project/teraterm/github-snapshot/builds/49506498

**Comment by nmaya** [comment]
### menu/control-broadcast.html, about/history.html

前面に来るのが「選択されている**複数**のウィンドウ」であることが分かるとよいと思います。

### Fore/前面

日英とも Submit や Close と異なり、動詞的な単語ではありません。
Word の図形だと「前面へ移動」のように言いますが、いい表現はないでしょうか。

### teraterm/ttermpro.rc

rc ファイル内の IDC_FORE_RECEIVER の位置ですが、ボタンの並び順と同じに（自然に）なるようにしていただけるでしょうか。
rc ファイル内のDIALOG内のリソースの順序が、ダイアログ内のタブオーダーになるためです。
このダイアログではタブオーダーが効かないようなのであまり関係ありませんが、今後のために書きました。

**Comment by sempreff** [comment]
PR #185 を更新しました。サイズ変更時のボタンが取り残されていたので揃って動くようにしました。

### 文言

ドキュメントの表現は同一ページ内で整うよう改めてみました。
ボタンのキャプションは to Fore / 前面へ ではどうでしょう。
（日英以外の言語ファイルは決まってから反映とさせてください）

### rc

このダイアログ部分は（今回追加のボタン以外も）整えてみました。

**Comment by zmatsuo** [comment]
私自身は Broadcast command を常用したことがありません。

たくさんTera Term を開いて作業していて
「前面に表示」機能がほしいのはそうだなと思います。

ボタンにするとテキストを長くしにくいのと、
機能が増やす毎にボタン分ダイアログの面積が必要になるので、
右ボタンでポップアップが出てきて
- bring fore (英語は適当です)
- iconify
- max
- restore
   :
とかどうでしょうか?
設定/設定フォルダ ダイアログみたいな感じです。

**Comment by nmaya** [comment]
> 右ボタンでポップアップが出てきて

これは操作が2段階になるので地味にストレスだと思います。

**Comment by sempreff** [comment]
操作にボタンを使うのも悪くないと思っていますが、コンテキストメニューを使うのも悪くないと思います。Broadcast command ダイアログの操作は主にマウスで行われることが多いですから、ウィンドウリストで対象ウィンドウの選択/解除をした流れで（ボタンまでマウスを運ばずに、その場で）右クリックから操作できるのは便利です。
コンテキストメニューの場合は操作が二段階になるのはおっしゃる通りですが、ボタンとコンテキストメニューの両方の UI を提供することでも良いと思います。

Broadcast command ダイアログには改善したい箇所が他にもいくつかあって、そのうちの１つが「ウィンドウリストの更新」です。これはコンテキストメニューから指示できるのが直感的で良いと思います。ブランチを分けて作業していましたが、この issue (PR 185)に相乗りしても良いでしょうか。

**Comment by sempreff** [comment]
PE #185 を更新しました。自分の使い方としては違和感なくなりました。

**Comment by nmaya** [comment]
何度も押すものではないので、ボタンでなくてもいいような気がしてきました。

ドキュメントに書けば解決する話ではあるのですが、操作者としても私の感覚では、右クリックするといまされている選択が壊れそうに思います。

- いまされている選択が全解除されそう
- クリックした選択肢が選択状態なら、そこだけ解除されそう
- クリックした選択肢が非選択状態なら、そこが選択状態になりそう。

なので右クリックしようと思わず、コンテキストメニューがあることに気づきにくいかもしれません。

**Comment by sempreff** [comment]
control-broadcast.html にコンテキストメニューの件を追記しておきました。

**Comment by zmatsuo** [comment]
このissue(#83)の修正+α #185 が main にマージされました。

続きは #188 ということでどうでしょう。
このissueはクローズします。
