### ISSUE TITLE
TTL: foldersearchがフォルダが存在しないときにもシステム変数returnに1を返す 

### ISSUE THREAD

**Issue by ryuten0819** [TeraTermProject/teraterm#85]
開発ありがとうございます。

ver4.106→ver5.0以降にアップデートしたところ、TTLコマンドのfoldersearchがうまく機能しなくなってしまいました。
どうやらフォルダが存在しないときにも、システム変数returnに1を返しているようです。

ttl.cppを確認したのですが、フォルダが存在しない場合に、GetFileAttributesW()がINVALID_FILE_ATTRIBUTES（おそらく-1）を返すことが原因ではないかと考えています。
こちらの挙動について確認していただけないでしょうか。

よろしくお願いいたします。

**Comment by zmatsuo** [comment]
指摘ありがとうございます。

フォルダ(/ファイル)がない場合の戻り値 INVALID_FILE_ATTRIBUTES の
チェックを追加しました。

修正したバイナリを作りました。
https://ci.appveyor.com/project/teraterm/github-main/build/artifacts
ご利用ください。

**Comment by ryuten0819** [comment]
ご対応いただきありがとうございます。
問題無く動作しました。

**Comment by zmatsuo** [comment]
ありがとうございます。
クローズします。
