### ISSUE TITLE
SSH認証バナーのエンコーディング変換

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/teraterm#94]
### 現状の問題点
SSH認証バナー(SSH_MSG_USERAUTH_BANNER)に含まれるメッセージのエンコーディングはUTF-8となっているが、TTSSH ではエンコーディングの変換を行っていない。
その為、バナーメッセージにUS-ASCII以外の文字が含まれていた場合に文字化けが発生する場合がある。

### 対処案
[AuthBanner設定](https://ttssh2.osdn.jp/manual/ja/setup/teraterm-ssh.html#AuthBanner)に応じて以下の変換を行う
- AuthBanner=1: 受信漢字コード設定に従って変換する(UTF-8の時は無変換)
- AuthBanner=2/3: ローカル(システム)のエンコーディングに従って変換する。もしくはUnicode版のAPIが使えるならばUnicodeに変換して表示する

### 2019-12-09 09:54 doda
4.105 では修正済み。
5.0 では内部エンコーディングが変更になる為、別途対応が必要。

### origin
https://osdn.net/projects/ttssh2/ticket/39724

**Comment by zmatsuo** [comment]
問題は解決できていますが、
実装が妥当なところか悩むところです。
評価していただきたくpushしたbranchです。
(ブランチ名 "#94" です)

実装の方向はこんな感じです。
- 内部文字列から必要な文字コードに変換するモジュールを複数個所から使えるようにする
- 送信、ローカルエコーに使用
- ttxsshプラグインから API 経由で文字コード変換に使用

プラグインから使用できる API は、
初期化時にコールされる TTXBind() の新版 TTXBind3() の引数から取得します。

TTXBind3() は引数が3つになることから命名しました。
最初は TTXBind() のままにしようとしたのですが、できませんでした。

#63 送受信用の漢字エンコードの選択について
もAPIから変更するようにしています。

mainにマージすることなく捨ててしまうかもしれない
(ブランチを削除するかもしれない)ので
ソースにコメントを付けてもきえてしまうかもしれません。
このissueにコメントをいただくほうが良いと思います。

**Comment by zmatsuo** [comment]
実装を変更しました。#94_2 ブランチです。
エンコーディング変換をttxsshに組み込んで、
プラグインは使用していません。

問題なさそうなら改版履歴を追加して
main にマージしようと思います。

**Comment by nmaya** [comment]
ありがとうございます。
受信文字コードが「UTF8」「SJIS」「EUC」「JIS」のどれでも、VTウィンドウに文字化けせず表示されることを確認しました。

**Comment by zmatsuo** [comment]
ありがとうございます。

main にマージしました。

SSH認証バナーのメッセージ表示方法すべて([AuthBanner設定](https://teratermproject.github.io//manual/5/ja/setup/teraterm-ssh.html#AuthBanner)の1,2,3)で
Unicode対応/エンコーディング変換に対応できていると思います。

クローズします。
